// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"context"
	"github.com/google/wire"
	"zk8s.com/rca-api/internal/apiserver/biz"
	"zk8s.com/rca-api/internal/apiserver/handler"
	"zk8s.com/rca-api/internal/apiserver/pkg/validation"
	"zk8s.com/rca-api/internal/apiserver/store"
)

// Injectors from wire.go:

// NewServer initializes and creates the web server with all necessary dependencies using Wire.
func NewServer(contextContext context.Context, config *Config) (*Server, error) {
	dependencies := NewDependencies(contextContext)
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	storeStore := store.NewStore(db)
	bizBiz := biz.NewBiz(storeStore)
	validator := validation.New(storeStore)
	handlerHandler := handler.NewHandler(bizBiz, validator)
	serverConfig := &ServerConfig{
		Config:       config,
		Dependencies: dependencies,
		Handler:      handlerHandler,
	}
	server, err := NewWebServer(serverConfig)
	if err != nil {
		return nil, err
	}
	apiserverServer := &Server{
		cfg: serverConfig,
		srv: server,
	}
	return apiserverServer, nil
}

// wire.go:

// infrastructureSet groups all infrastructure-related providers.
// This keeps the main wire.Build call clean.
var infrastructureSet = wire.NewSet(
	ProvideDB,
)
