version: 1

defaults:
  on_ingest:
    enabled: false
  on_escalation:
    enabled: false
  scheduled:
    enabled: false

triggers:
  on_ingest:
    rules:
      - name: "default"
        match: {}
        action:
          run: false

  on_escalation:
    rules:
      - name: "default"
        match: {}
        action:
          run: false

  scheduled:
    rules:
      - name: "default"
        match: {}
        action:
          run: false
