// AI Job and ToolCall API messages for P0 RCA orchestration.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apiserver/v1/ai_job.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AIJob represents one RCA orchestration run.
type AIJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobID is the business resource ID (e.g. ai-job-xxxxxx).
	JobID string `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	// incidentID is the bound incident.
	IncidentID string `protobuf:"bytes,2,opt,name=incidentID,proto3" json:"incidentID,omitempty"`
	// pipeline is the orchestration pipeline name, e.g. basic_rca.
	Pipeline string `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// trigger is one of manual|on_ingest|on_escalation|scheduled.
	Trigger string `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// status is queued|running|succeeded|failed|canceled.
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// timeRangeStart/timeRangeEnd define fixed analysis window.
	TimeRangeStart *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timeRangeStart,proto3" json:"timeRangeStart,omitempty"`
	TimeRangeEnd   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timeRangeEnd,proto3" json:"timeRangeEnd,omitempty"`
	// inputHintsJSON stores optional hints provided by caller.
	InputHintsJSON *string `protobuf:"bytes,8,opt,name=inputHintsJSON,proto3,oneof" json:"inputHintsJSON,omitempty"`
	// outputSummary stores human-readable final summary.
	OutputSummary *string `protobuf:"bytes,9,opt,name=outputSummary,proto3,oneof" json:"outputSummary,omitempty"`
	// outputJSON stores structured run output.
	OutputJSON *string `protobuf:"bytes,10,opt,name=outputJSON,proto3,oneof" json:"outputJSON,omitempty"`
	// evidenceIDsJSON stores referenced/generated evidence ids.
	EvidenceIDsJSON *string `protobuf:"bytes,11,opt,name=evidenceIDsJSON,proto3,oneof" json:"evidenceIDsJSON,omitempty"`
	// errorMessage stores terminal error text.
	ErrorMessage *string `protobuf:"bytes,12,opt,name=errorMessage,proto3,oneof" json:"errorMessage,omitempty"`
	// createdAt/startedAt/finishedAt are lifecycle timestamps.
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	StartedAt  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=startedAt,proto3,oneof" json:"startedAt,omitempty"`
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=finishedAt,proto3,oneof" json:"finishedAt,omitempty"`
	// createdBy is actor identifier: system|user:{id}|ai:{job_id}.
	CreatedBy string `protobuf:"bytes,16,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// sessionID is the reusable RCA session identifier associated with this run.
	SessionID     *string `protobuf:"bytes,17,opt,name=sessionID,proto3,oneof" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIJob) Reset() {
	*x = AIJob{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIJob) ProtoMessage() {}

func (x *AIJob) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIJob.ProtoReflect.Descriptor instead.
func (*AIJob) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{0}
}

func (x *AIJob) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *AIJob) GetIncidentID() string {
	if x != nil {
		return x.IncidentID
	}
	return ""
}

func (x *AIJob) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *AIJob) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *AIJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AIJob) GetTimeRangeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeRangeStart
	}
	return nil
}

func (x *AIJob) GetTimeRangeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeRangeEnd
	}
	return nil
}

func (x *AIJob) GetInputHintsJSON() string {
	if x != nil && x.InputHintsJSON != nil {
		return *x.InputHintsJSON
	}
	return ""
}

func (x *AIJob) GetOutputSummary() string {
	if x != nil && x.OutputSummary != nil {
		return *x.OutputSummary
	}
	return ""
}

func (x *AIJob) GetOutputJSON() string {
	if x != nil && x.OutputJSON != nil {
		return *x.OutputJSON
	}
	return ""
}

func (x *AIJob) GetEvidenceIDsJSON() string {
	if x != nil && x.EvidenceIDsJSON != nil {
		return *x.EvidenceIDsJSON
	}
	return ""
}

func (x *AIJob) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AIJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AIJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AIJob) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *AIJob) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AIJob) GetSessionID() string {
	if x != nil && x.SessionID != nil {
		return *x.SessionID
	}
	return ""
}

// RunAIJobRequest creates one AI job for an incident.
type RunAIJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incidentID identifies incident in URI.
	// @gotags: uri:"incidentID"
	IncidentID string `protobuf:"bytes,1,opt,name=incidentID,proto3" json:"incidentID,omitempty" uri:"incidentID"`
	// idempotencyKey supports idempotent run retries.
	IdempotencyKey *string `protobuf:"bytes,2,opt,name=idempotencyKey,proto3,oneof" json:"idempotencyKey,omitempty"`
	// pipeline defaults to basic_rca when omitted.
	Pipeline *string `protobuf:"bytes,3,opt,name=pipeline,proto3,oneof" json:"pipeline,omitempty"`
	// trigger defaults to manual when omitted.
	Trigger        *string                `protobuf:"bytes,4,opt,name=trigger,proto3,oneof" json:"trigger,omitempty"`
	TimeRangeStart *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timeRangeStart,proto3" json:"timeRangeStart,omitempty"`
	TimeRangeEnd   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timeRangeEnd,proto3" json:"timeRangeEnd,omitempty"`
	InputHintsJSON *string                `protobuf:"bytes,7,opt,name=inputHintsJSON,proto3,oneof" json:"inputHintsJSON,omitempty"`
	CreatedBy      *string                `protobuf:"bytes,8,opt,name=createdBy,proto3,oneof" json:"createdBy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunAIJobRequest) Reset() {
	*x = RunAIJobRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAIJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAIJobRequest) ProtoMessage() {}

func (x *RunAIJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAIJobRequest.ProtoReflect.Descriptor instead.
func (*RunAIJobRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{1}
}

func (x *RunAIJobRequest) GetIncidentID() string {
	if x != nil {
		return x.IncidentID
	}
	return ""
}

func (x *RunAIJobRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *RunAIJobRequest) GetPipeline() string {
	if x != nil && x.Pipeline != nil {
		return *x.Pipeline
	}
	return ""
}

func (x *RunAIJobRequest) GetTrigger() string {
	if x != nil && x.Trigger != nil {
		return *x.Trigger
	}
	return ""
}

func (x *RunAIJobRequest) GetTimeRangeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeRangeStart
	}
	return nil
}

func (x *RunAIJobRequest) GetTimeRangeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeRangeEnd
	}
	return nil
}

func (x *RunAIJobRequest) GetInputHintsJSON() string {
	if x != nil && x.InputHintsJSON != nil {
		return *x.InputHintsJSON
	}
	return ""
}

func (x *RunAIJobRequest) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

// RunAIJobResponse returns created/reused job id.
type RunAIJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobID         string                 `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAIJobResponse) Reset() {
	*x = RunAIJobResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAIJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAIJobResponse) ProtoMessage() {}

func (x *RunAIJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAIJobResponse.ProtoReflect.Descriptor instead.
func (*RunAIJobResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{2}
}

func (x *RunAIJobResponse) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

// GetAIJobRequest fetches one AI job.
type GetAIJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobID identifies AI job in URI.
	// @gotags: uri:"jobID"
	JobID         string `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty" uri:"jobID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIJobRequest) Reset() {
	*x = GetAIJobRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIJobRequest) ProtoMessage() {}

func (x *GetAIJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIJobRequest.ProtoReflect.Descriptor instead.
func (*GetAIJobRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{3}
}

func (x *GetAIJobRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

// GetAIJobResponse returns one AI job.
type GetAIJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *AIJob                 `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIJobResponse) Reset() {
	*x = GetAIJobResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIJobResponse) ProtoMessage() {}

func (x *GetAIJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIJobResponse.ProtoReflect.Descriptor instead.
func (*GetAIJobResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetAIJobResponse) GetJob() *AIJob {
	if x != nil {
		return x.Job
	}
	return nil
}

// ListAIJobsRequest lists jobs with status filter for orchestrator queue pull.
type ListAIJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is exact status filter; P0 queue pull requires queued.
	// @gotags: form:"status"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty" form:"status"`
	// offset for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit for pagination.
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIJobsRequest) Reset() {
	*x = ListAIJobsRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIJobsRequest) ProtoMessage() {}

func (x *ListAIJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIJobsRequest.ProtoReflect.Descriptor instead.
func (*ListAIJobsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{5}
}

func (x *ListAIJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAIJobsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAIJobsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListAIJobsResponse lists jobs with status filter.
type ListAIJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Jobs          []*AIJob               `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIJobsResponse) Reset() {
	*x = ListAIJobsResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIJobsResponse) ProtoMessage() {}

func (x *ListAIJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIJobsResponse.ProtoReflect.Descriptor instead.
func (*ListAIJobsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{6}
}

func (x *ListAIJobsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAIJobsResponse) GetJobs() []*AIJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// ListIncidentAIJobsRequest lists jobs for an incident.
type ListIncidentAIJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incidentID identifies incident in URI.
	// @gotags: uri:"incidentID"
	IncidentID string `protobuf:"bytes,1,opt,name=incidentID,proto3" json:"incidentID,omitempty" uri:"incidentID"`
	// offset for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit for pagination.
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentAIJobsRequest) Reset() {
	*x = ListIncidentAIJobsRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentAIJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentAIJobsRequest) ProtoMessage() {}

func (x *ListIncidentAIJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentAIJobsRequest.ProtoReflect.Descriptor instead.
func (*ListIncidentAIJobsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{7}
}

func (x *ListIncidentAIJobsRequest) GetIncidentID() string {
	if x != nil {
		return x.IncidentID
	}
	return ""
}

func (x *ListIncidentAIJobsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListIncidentAIJobsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListIncidentAIJobsResponse lists jobs for an incident.
type ListIncidentAIJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Jobs          []*AIJob               `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentAIJobsResponse) Reset() {
	*x = ListIncidentAIJobsResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentAIJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentAIJobsResponse) ProtoMessage() {}

func (x *ListIncidentAIJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentAIJobsResponse.ProtoReflect.Descriptor instead.
func (*ListIncidentAIJobsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{8}
}

func (x *ListIncidentAIJobsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListIncidentAIJobsResponse) GetJobs() []*AIJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// StartAIJobRequest transitions job queued -> running.
type StartAIJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobID identifies AI job in URI.
	// @gotags: uri:"jobID"
	JobID         string `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty" uri:"jobID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAIJobRequest) Reset() {
	*x = StartAIJobRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAIJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAIJobRequest) ProtoMessage() {}

func (x *StartAIJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAIJobRequest.ProtoReflect.Descriptor instead.
func (*StartAIJobRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{9}
}

func (x *StartAIJobRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

// StartAIJobResponse indicates transition result.
type StartAIJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skillsetsJSON contains resolved skillset configuration for the job's pipeline.
	// Follows the ResolveOrchestratorSkillsetsResponse format.
	SkillsetsJSON *string `protobuf:"bytes,1,opt,name=skillsetsJSON,proto3,oneof" json:"skillsetsJSON,omitempty"`
	// resolvedToolProviders is the canonical field containing structured provider snapshot.
	// This is materialized at claim time from toolset_provider_bindings + mcp_servers + tool_metadata.
	ResolvedToolProviders []*ResolvedToolProvider `protobuf:"bytes,2,rep,name=resolvedToolProviders,proto3" json:"resolvedToolProviders,omitempty"`
	// agentContextJSON is the unified agent context snapshot for hybrid multi-agent.
	// Contains job_id, pipeline, template_id, session_snapshot, tool_surface, skill_surface,
	// platform_hints, and run_policies.
	AgentContextJSON *string `protobuf:"bytes,3,opt,name=agentContextJSON,proto3,oneof" json:"agentContextJSON,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartAIJobResponse) Reset() {
	*x = StartAIJobResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAIJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAIJobResponse) ProtoMessage() {}

func (x *StartAIJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAIJobResponse.ProtoReflect.Descriptor instead.
func (*StartAIJobResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{10}
}

func (x *StartAIJobResponse) GetSkillsetsJSON() string {
	if x != nil && x.SkillsetsJSON != nil {
		return *x.SkillsetsJSON
	}
	return ""
}

func (x *StartAIJobResponse) GetResolvedToolProviders() []*ResolvedToolProvider {
	if x != nil {
		return x.ResolvedToolProviders
	}
	return nil
}

func (x *StartAIJobResponse) GetAgentContextJSON() string {
	if x != nil && x.AgentContextJSON != nil {
		return *x.AgentContextJSON
	}
	return ""
}

// ResolvedToolProvider represents a fully resolved tool provider with all metadata.
// This is the single source of truth for worker tool execution.
type ResolvedToolProvider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// providerID is a unique identifier for this provider instance within the job.
	ProviderID string `protobuf:"bytes,1,opt,name=providerID,proto3" json:"providerID,omitempty"`
	// mcpServerID references the mcp_servers table.
	McpServerID string `protobuf:"bytes,2,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty"`
	// name is the display name of the provider.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// providerType indicates the provider type (e.g., mcp_http).
	ProviderType string `protobuf:"bytes,4,opt,name=providerType,proto3" json:"providerType,omitempty"`
	// serverKind is builtin or external.
	ServerKind string `protobuf:"bytes,5,opt,name=serverKind,proto3" json:"serverKind,omitempty"`
	// baseURL is the endpoint for the provider.
	BaseURL string `protobuf:"bytes,6,opt,name=baseURL,proto3" json:"baseURL,omitempty"`
	// allowedTools is the filtered list of tools available for this job.
	AllowedTools []string `protobuf:"bytes,7,rep,name=allowedTools,proto3" json:"allowedTools,omitempty"`
	// toolMetadata contains metadata for each allowed tool.
	ToolMetadata []*ToolMetadataRef `protobuf:"bytes,8,rep,name=toolMetadata,proto3" json:"toolMetadata,omitempty"`
	// priority determines execution order (lower = higher priority).
	Priority int32 `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	// scopes contains optional scope information.
	Scopes *string `protobuf:"bytes,10,opt,name=scopes,proto3,oneof" json:"scopes,omitempty"`
	// timeoutSec is the timeout for calls to this provider.
	TimeoutSec    *int32 `protobuf:"varint,11,opt,name=timeoutSec,proto3,oneof" json:"timeoutSec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedToolProvider) Reset() {
	*x = ResolvedToolProvider{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedToolProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedToolProvider) ProtoMessage() {}

func (x *ResolvedToolProvider) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedToolProvider.ProtoReflect.Descriptor instead.
func (*ResolvedToolProvider) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{11}
}

func (x *ResolvedToolProvider) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *ResolvedToolProvider) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

func (x *ResolvedToolProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedToolProvider) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *ResolvedToolProvider) GetServerKind() string {
	if x != nil {
		return x.ServerKind
	}
	return ""
}

func (x *ResolvedToolProvider) GetBaseURL() string {
	if x != nil {
		return x.BaseURL
	}
	return ""
}

func (x *ResolvedToolProvider) GetAllowedTools() []string {
	if x != nil {
		return x.AllowedTools
	}
	return nil
}

func (x *ResolvedToolProvider) GetToolMetadata() []*ToolMetadataRef {
	if x != nil {
		return x.ToolMetadata
	}
	return nil
}

func (x *ResolvedToolProvider) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ResolvedToolProvider) GetScopes() string {
	if x != nil && x.Scopes != nil {
		return *x.Scopes
	}
	return ""
}

func (x *ResolvedToolProvider) GetTimeoutSec() int32 {
	if x != nil && x.TimeoutSec != nil {
		return *x.TimeoutSec
	}
	return 0
}

// ToolMetadataRef is a lightweight reference to tool metadata.
// Used to pass tool classification info to the orchestrator.
type ToolMetadataRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// toolName is the canonical dotted name (e.g., incident.get).
	ToolName string `protobuf:"bytes,1,opt,name=toolName,proto3" json:"toolName,omitempty"`
	// kind is the tool category (e.g., metrics, logs, traces, incident).
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// domain is the logical domain (e.g., observability, platform).
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// readOnly indicates whether the tool only reads data.
	ReadOnly bool `protobuf:"varint,4,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	// riskLevel is low, medium, or high.
	RiskLevel string `protobuf:"bytes,5,opt,name=riskLevel,proto3" json:"riskLevel,omitempty"`
	// toolClass is fc_selectable (A-class) or runtime_owned (B-class).
	ToolClass string `protobuf:"bytes,6,opt,name=toolClass,proto3" json:"toolClass,omitempty"`
	// aliases contains legacy underscore names for backward compatibility.
	Aliases []string `protobuf:"bytes,7,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// allowedForPromptSkill indicates visibility to prompt-first Skills.
	// Optional to preserve explicit false values in JSON serialization.
	AllowedForPromptSkill *bool `protobuf:"varint,8,opt,name=allowedForPromptSkill,proto3,oneof" json:"allowedForPromptSkill,omitempty"`
	// allowedForGraphAgent indicates visibility to LangGraph FC agent.
	// Optional to preserve explicit false values in JSON serialization.
	AllowedForGraphAgent *bool `protobuf:"varint,9,opt,name=allowedForGraphAgent,proto3,oneof" json:"allowedForGraphAgent,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolMetadataRef) Reset() {
	*x = ToolMetadataRef{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolMetadataRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolMetadataRef) ProtoMessage() {}

func (x *ToolMetadataRef) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolMetadataRef.ProtoReflect.Descriptor instead.
func (*ToolMetadataRef) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{12}
}

func (x *ToolMetadataRef) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolMetadataRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ToolMetadataRef) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ToolMetadataRef) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *ToolMetadataRef) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ToolMetadataRef) GetToolClass() string {
	if x != nil {
		return x.ToolClass
	}
	return ""
}

func (x *ToolMetadataRef) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ToolMetadataRef) GetAllowedForPromptSkill() bool {
	if x != nil && x.AllowedForPromptSkill != nil {
		return *x.AllowedForPromptSkill
	}
	return false
}

func (x *ToolMetadataRef) GetAllowedForGraphAgent() bool {
	if x != nil && x.AllowedForGraphAgent != nil {
		return *x.AllowedForGraphAgent
	}
	return false
}

// CancelAIJobRequest transitions job to canceled.
type CancelAIJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobID identifies AI job in URI.
	// @gotags: uri:"jobID"
	JobID         string  `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty" uri:"jobID"`
	Reason        *string `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAIJobRequest) Reset() {
	*x = CancelAIJobRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAIJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAIJobRequest) ProtoMessage() {}

func (x *CancelAIJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAIJobRequest.ProtoReflect.Descriptor instead.
func (*CancelAIJobRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{13}
}

func (x *CancelAIJobRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *CancelAIJobRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// CancelAIJobResponse indicates transition result.
type CancelAIJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAIJobResponse) Reset() {
	*x = CancelAIJobResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAIJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAIJobResponse) ProtoMessage() {}

func (x *CancelAIJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAIJobResponse.ProtoReflect.Descriptor instead.
func (*CancelAIJobResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{14}
}

// FinalizeAIJobRequest finalizes a running job and writes back incident RCA.
type FinalizeAIJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobID identifies AI job in URI.
	// @gotags: uri:"jobID"
	JobID string `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty" uri:"jobID"`
	// status accepts succeeded|failed|canceled.
	Status        string  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OutputSummary *string `protobuf:"bytes,3,opt,name=outputSummary,proto3,oneof" json:"outputSummary,omitempty"`
	// diagnosisJSON follows Appendix J2 when status=succeeded.
	DiagnosisJSON *string  `protobuf:"bytes,4,opt,name=diagnosisJSON,proto3,oneof" json:"diagnosisJSON,omitempty"`
	EvidenceIDs   []string `protobuf:"bytes,5,rep,name=evidenceIDs,proto3" json:"evidenceIDs,omitempty"`
	ErrorMessage  *string  `protobuf:"bytes,6,opt,name=errorMessage,proto3,oneof" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeAIJobRequest) Reset() {
	*x = FinalizeAIJobRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeAIJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeAIJobRequest) ProtoMessage() {}

func (x *FinalizeAIJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeAIJobRequest.ProtoReflect.Descriptor instead.
func (*FinalizeAIJobRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{15}
}

func (x *FinalizeAIJobRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *FinalizeAIJobRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FinalizeAIJobRequest) GetOutputSummary() string {
	if x != nil && x.OutputSummary != nil {
		return *x.OutputSummary
	}
	return ""
}

func (x *FinalizeAIJobRequest) GetDiagnosisJSON() string {
	if x != nil && x.DiagnosisJSON != nil {
		return *x.DiagnosisJSON
	}
	return ""
}

func (x *FinalizeAIJobRequest) GetEvidenceIDs() []string {
	if x != nil {
		return x.EvidenceIDs
	}
	return nil
}

func (x *FinalizeAIJobRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// FinalizeAIJobResponse indicates finalize result.
type FinalizeAIJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeAIJobResponse) Reset() {
	*x = FinalizeAIJobResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeAIJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeAIJobResponse) ProtoMessage() {}

func (x *FinalizeAIJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeAIJobResponse.ProtoReflect.Descriptor instead.
func (*FinalizeAIJobResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{16}
}

// AIToolCall records one tool invocation audit.
type AIToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// toolCallID is the business id (e.g. tool-call-xxxxxx).
	ToolCallID string `protobuf:"bytes,1,opt,name=toolCallID,proto3" json:"toolCallID,omitempty"`
	// jobID binds this call to AI job.
	JobID string `protobuf:"bytes,2,opt,name=jobID,proto3" json:"jobID,omitempty"`
	// seq is monotonically increasing in one job.
	Seq int64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// nodeName is LangGraph node identity.
	NodeName string `protobuf:"bytes,4,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	// toolName is tool identifier such as evidence.queryMetrics.
	ToolName string `protobuf:"bytes,5,opt,name=toolName,proto3" json:"toolName,omitempty"`
	// requestJSON is tool request payload.
	RequestJSON string `protobuf:"bytes,6,opt,name=requestJSON,proto3" json:"requestJSON,omitempty"`
	// responseJSON is tool response payload or preview.
	ResponseJSON *string `protobuf:"bytes,7,opt,name=responseJSON,proto3,oneof" json:"responseJSON,omitempty"`
	// responseRef is external reference when response is too large.
	ResponseRef       *string `protobuf:"bytes,8,opt,name=responseRef,proto3,oneof" json:"responseRef,omitempty"`
	ResponseSizeBytes int64   `protobuf:"varint,9,opt,name=responseSizeBytes,proto3" json:"responseSizeBytes,omitempty"`
	// status is ok|error|timeout|canceled.
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,11,opt,name=latencyMs,proto3" json:"latencyMs,omitempty"`
	ErrorMessage    *string                `protobuf:"bytes,12,opt,name=errorMessage,proto3,oneof" json:"errorMessage,omitempty"`
	EvidenceIDsJSON *string                `protobuf:"bytes,13,opt,name=evidenceIDsJSON,proto3,oneof" json:"evidenceIDsJSON,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AIToolCall) Reset() {
	*x = AIToolCall{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolCall) ProtoMessage() {}

func (x *AIToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolCall.ProtoReflect.Descriptor instead.
func (*AIToolCall) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{17}
}

func (x *AIToolCall) GetToolCallID() string {
	if x != nil {
		return x.ToolCallID
	}
	return ""
}

func (x *AIToolCall) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *AIToolCall) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AIToolCall) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AIToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AIToolCall) GetRequestJSON() string {
	if x != nil {
		return x.RequestJSON
	}
	return ""
}

func (x *AIToolCall) GetResponseJSON() string {
	if x != nil && x.ResponseJSON != nil {
		return *x.ResponseJSON
	}
	return ""
}

func (x *AIToolCall) GetResponseRef() string {
	if x != nil && x.ResponseRef != nil {
		return *x.ResponseRef
	}
	return ""
}

func (x *AIToolCall) GetResponseSizeBytes() int64 {
	if x != nil {
		return x.ResponseSizeBytes
	}
	return 0
}

func (x *AIToolCall) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AIToolCall) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AIToolCall) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AIToolCall) GetEvidenceIDsJSON() string {
	if x != nil && x.EvidenceIDsJSON != nil {
		return *x.EvidenceIDsJSON
	}
	return ""
}

func (x *AIToolCall) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateAIToolCallRequest appends one tool call audit record.
type CreateAIToolCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobID identifies AI job in URI.
	// @gotags: uri:"jobID"
	JobID        string  `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty" uri:"jobID"`
	Seq          int64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	NodeName     string  `protobuf:"bytes,3,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	ToolName     string  `protobuf:"bytes,4,opt,name=toolName,proto3" json:"toolName,omitempty"`
	RequestJSON  string  `protobuf:"bytes,5,opt,name=requestJSON,proto3" json:"requestJSON,omitempty"`
	ResponseJSON *string `protobuf:"bytes,6,opt,name=responseJSON,proto3,oneof" json:"responseJSON,omitempty"`
	// responseRef points to external object storage when response is large.
	ResponseRef *string `protobuf:"bytes,7,opt,name=responseRef,proto3,oneof" json:"responseRef,omitempty"`
	// status is ok|error|timeout|canceled.
	Status        string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs     int64    `protobuf:"varint,9,opt,name=latencyMs,proto3" json:"latencyMs,omitempty"`
	ErrorMessage  *string  `protobuf:"bytes,10,opt,name=errorMessage,proto3,oneof" json:"errorMessage,omitempty"`
	EvidenceIDs   []string `protobuf:"bytes,11,rep,name=evidenceIDs,proto3" json:"evidenceIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAIToolCallRequest) Reset() {
	*x = CreateAIToolCallRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAIToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIToolCallRequest) ProtoMessage() {}

func (x *CreateAIToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIToolCallRequest.ProtoReflect.Descriptor instead.
func (*CreateAIToolCallRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{18}
}

func (x *CreateAIToolCallRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CreateAIToolCallRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetRequestJSON() string {
	if x != nil {
		return x.RequestJSON
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetResponseJSON() string {
	if x != nil && x.ResponseJSON != nil {
		return *x.ResponseJSON
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetResponseRef() string {
	if x != nil && x.ResponseRef != nil {
		return *x.ResponseRef
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *CreateAIToolCallRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *CreateAIToolCallRequest) GetEvidenceIDs() []string {
	if x != nil {
		return x.EvidenceIDs
	}
	return nil
}

// CreateAIToolCallResponse returns created tool call id.
type CreateAIToolCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallID    string                 `protobuf:"bytes,1,opt,name=toolCallID,proto3" json:"toolCallID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAIToolCallResponse) Reset() {
	*x = CreateAIToolCallResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAIToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIToolCallResponse) ProtoMessage() {}

func (x *CreateAIToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIToolCallResponse.ProtoReflect.Descriptor instead.
func (*CreateAIToolCallResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{19}
}

func (x *CreateAIToolCallResponse) GetToolCallID() string {
	if x != nil {
		return x.ToolCallID
	}
	return ""
}

// ListAIToolCallsRequest lists tool call audits for one job.
type ListAIToolCallsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// jobID identifies AI job in URI.
	// @gotags: uri:"jobID"
	JobID string `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty" uri:"jobID"`
	// offset for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit for pagination.
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// optional exact seq filter.
	// @gotags: form:"seq"
	Seq           *int64 `protobuf:"varint,4,opt,name=seq,proto3,oneof" json:"seq,omitempty" form:"seq"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIToolCallsRequest) Reset() {
	*x = ListAIToolCallsRequest{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIToolCallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIToolCallsRequest) ProtoMessage() {}

func (x *ListAIToolCallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIToolCallsRequest.ProtoReflect.Descriptor instead.
func (*ListAIToolCallsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{20}
}

func (x *ListAIToolCallsRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *ListAIToolCallsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAIToolCallsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAIToolCallsRequest) GetSeq() int64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

// ListAIToolCallsResponse lists tool call audits.
type ListAIToolCallsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	ToolCalls     []*AIToolCall          `protobuf:"bytes,2,rep,name=toolCalls,proto3" json:"toolCalls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAIToolCallsResponse) Reset() {
	*x = ListAIToolCallsResponse{}
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAIToolCallsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAIToolCallsResponse) ProtoMessage() {}

func (x *ListAIToolCallsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_ai_job_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAIToolCallsResponse.ProtoReflect.Descriptor instead.
func (*ListAIToolCallsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_ai_job_proto_rawDescGZIP(), []int{21}
}

func (x *ListAIToolCallsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAIToolCallsResponse) GetToolCalls() []*AIToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

var File_apiserver_v1_ai_job_proto protoreflect.FileDescriptor

const file_apiserver_v1_ai_job_proto_rawDesc = "" +
	"\n" +
	"\x19apiserver/v1/ai_job.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x06\n" +
	"\x05AIJob\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\x12\x1e\n" +
	"\n" +
	"incidentID\x18\x02 \x01(\tR\n" +
	"incidentID\x12\x1a\n" +
	"\bpipeline\x18\x03 \x01(\tR\bpipeline\x12\x18\n" +
	"\atrigger\x18\x04 \x01(\tR\atrigger\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12B\n" +
	"\x0etimeRangeStart\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimeRangeStart\x12>\n" +
	"\ftimeRangeEnd\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ftimeRangeEnd\x12+\n" +
	"\x0einputHintsJSON\x18\b \x01(\tH\x00R\x0einputHintsJSON\x88\x01\x01\x12)\n" +
	"\routputSummary\x18\t \x01(\tH\x01R\routputSummary\x88\x01\x01\x12#\n" +
	"\n" +
	"outputJSON\x18\n" +
	" \x01(\tH\x02R\n" +
	"outputJSON\x88\x01\x01\x12-\n" +
	"\x0fevidenceIDsJSON\x18\v \x01(\tH\x03R\x0fevidenceIDsJSON\x88\x01\x01\x12'\n" +
	"\ferrorMessage\x18\f \x01(\tH\x04R\ferrorMessage\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\tstartedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\x05R\tstartedAt\x88\x01\x01\x12?\n" +
	"\n" +
	"finishedAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\x06R\n" +
	"finishedAt\x88\x01\x01\x12\x1c\n" +
	"\tcreatedBy\x18\x10 \x01(\tR\tcreatedBy\x12!\n" +
	"\tsessionID\x18\x11 \x01(\tH\aR\tsessionID\x88\x01\x01B\x11\n" +
	"\x0f_inputHintsJSONB\x10\n" +
	"\x0e_outputSummaryB\r\n" +
	"\v_outputJSONB\x12\n" +
	"\x10_evidenceIDsJSONB\x0f\n" +
	"\r_errorMessageB\f\n" +
	"\n" +
	"_startedAtB\r\n" +
	"\v_finishedAtB\f\n" +
	"\n" +
	"_sessionID\"\xbf\x03\n" +
	"\x0fRunAIJobRequest\x12\x1e\n" +
	"\n" +
	"incidentID\x18\x01 \x01(\tR\n" +
	"incidentID\x12+\n" +
	"\x0eidempotencyKey\x18\x02 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01\x12\x1f\n" +
	"\bpipeline\x18\x03 \x01(\tH\x01R\bpipeline\x88\x01\x01\x12\x1d\n" +
	"\atrigger\x18\x04 \x01(\tH\x02R\atrigger\x88\x01\x01\x12B\n" +
	"\x0etimeRangeStart\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimeRangeStart\x12>\n" +
	"\ftimeRangeEnd\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ftimeRangeEnd\x12+\n" +
	"\x0einputHintsJSON\x18\a \x01(\tH\x03R\x0einputHintsJSON\x88\x01\x01\x12!\n" +
	"\tcreatedBy\x18\b \x01(\tH\x04R\tcreatedBy\x88\x01\x01B\x11\n" +
	"\x0f_idempotencyKeyB\v\n" +
	"\t_pipelineB\n" +
	"\n" +
	"\b_triggerB\x11\n" +
	"\x0f_inputHintsJSONB\f\n" +
	"\n" +
	"_createdBy\"(\n" +
	"\x10RunAIJobResponse\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\"'\n" +
	"\x0fGetAIJobRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\"9\n" +
	"\x10GetAIJobResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.apiserver.v1.AIJobR\x03job\"Y\n" +
	"\x11ListAIJobsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"]\n" +
	"\x12ListAIJobsResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12'\n" +
	"\x04jobs\x18\x02 \x03(\v2\x13.apiserver.v1.AIJobR\x04jobs\"i\n" +
	"\x19ListIncidentAIJobsRequest\x12\x1e\n" +
	"\n" +
	"incidentID\x18\x01 \x01(\tR\n" +
	"incidentID\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"e\n" +
	"\x1aListIncidentAIJobsResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12'\n" +
	"\x04jobs\x18\x02 \x03(\v2\x13.apiserver.v1.AIJobR\x04jobs\")\n" +
	"\x11StartAIJobRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\"\xf1\x01\n" +
	"\x12StartAIJobResponse\x12)\n" +
	"\rskillsetsJSON\x18\x01 \x01(\tH\x00R\rskillsetsJSON\x88\x01\x01\x12X\n" +
	"\x15resolvedToolProviders\x18\x02 \x03(\v2\".apiserver.v1.ResolvedToolProviderR\x15resolvedToolProviders\x12/\n" +
	"\x10agentContextJSON\x18\x03 \x01(\tH\x01R\x10agentContextJSON\x88\x01\x01B\x10\n" +
	"\x0e_skillsetsJSONB\x13\n" +
	"\x11_agentContextJSON\"\xa9\x03\n" +
	"\x14ResolvedToolProvider\x12\x1e\n" +
	"\n" +
	"providerID\x18\x01 \x01(\tR\n" +
	"providerID\x12 \n" +
	"\vmcpServerID\x18\x02 \x01(\tR\vmcpServerID\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\fproviderType\x18\x04 \x01(\tR\fproviderType\x12\x1e\n" +
	"\n" +
	"serverKind\x18\x05 \x01(\tR\n" +
	"serverKind\x12\x18\n" +
	"\abaseURL\x18\x06 \x01(\tR\abaseURL\x12\"\n" +
	"\fallowedTools\x18\a \x03(\tR\fallowedTools\x12A\n" +
	"\ftoolMetadata\x18\b \x03(\v2\x1d.apiserver.v1.ToolMetadataRefR\ftoolMetadata\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x1b\n" +
	"\x06scopes\x18\n" +
	" \x01(\tH\x00R\x06scopes\x88\x01\x01\x12#\n" +
	"\n" +
	"timeoutSec\x18\v \x01(\x05H\x01R\n" +
	"timeoutSec\x88\x01\x01B\t\n" +
	"\a_scopesB\r\n" +
	"\v_timeoutSec\"\xf2\x02\n" +
	"\x0fToolMetadataRef\x12\x1a\n" +
	"\btoolName\x18\x01 \x01(\tR\btoolName\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1a\n" +
	"\breadOnly\x18\x04 \x01(\bR\breadOnly\x12\x1c\n" +
	"\triskLevel\x18\x05 \x01(\tR\triskLevel\x12\x1c\n" +
	"\ttoolClass\x18\x06 \x01(\tR\ttoolClass\x12\x18\n" +
	"\aaliases\x18\a \x03(\tR\aaliases\x129\n" +
	"\x15allowedForPromptSkill\x18\b \x01(\bH\x00R\x15allowedForPromptSkill\x88\x01\x01\x127\n" +
	"\x14allowedForGraphAgent\x18\t \x01(\bH\x01R\x14allowedForGraphAgent\x88\x01\x01B\x18\n" +
	"\x16_allowedForPromptSkillB\x17\n" +
	"\x15_allowedForGraphAgent\"R\n" +
	"\x12CancelAIJobRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\x15\n" +
	"\x13CancelAIJobResponse\"\x9a\x02\n" +
	"\x14FinalizeAIJobRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\routputSummary\x18\x03 \x01(\tH\x00R\routputSummary\x88\x01\x01\x12)\n" +
	"\rdiagnosisJSON\x18\x04 \x01(\tH\x01R\rdiagnosisJSON\x88\x01\x01\x12 \n" +
	"\vevidenceIDs\x18\x05 \x03(\tR\vevidenceIDs\x12'\n" +
	"\ferrorMessage\x18\x06 \x01(\tH\x02R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_outputSummaryB\x10\n" +
	"\x0e_diagnosisJSONB\x0f\n" +
	"\r_errorMessage\"\x17\n" +
	"\x15FinalizeAIJobResponse\"\xba\x04\n" +
	"\n" +
	"AIToolCall\x12\x1e\n" +
	"\n" +
	"toolCallID\x18\x01 \x01(\tR\n" +
	"toolCallID\x12\x14\n" +
	"\x05jobID\x18\x02 \x01(\tR\x05jobID\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1a\n" +
	"\bnodeName\x18\x04 \x01(\tR\bnodeName\x12\x1a\n" +
	"\btoolName\x18\x05 \x01(\tR\btoolName\x12 \n" +
	"\vrequestJSON\x18\x06 \x01(\tR\vrequestJSON\x12'\n" +
	"\fresponseJSON\x18\a \x01(\tH\x00R\fresponseJSON\x88\x01\x01\x12%\n" +
	"\vresponseRef\x18\b \x01(\tH\x01R\vresponseRef\x88\x01\x01\x12,\n" +
	"\x11responseSizeBytes\x18\t \x01(\x03R\x11responseSizeBytes\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1c\n" +
	"\tlatencyMs\x18\v \x01(\x03R\tlatencyMs\x12'\n" +
	"\ferrorMessage\x18\f \x01(\tH\x02R\ferrorMessage\x88\x01\x01\x12-\n" +
	"\x0fevidenceIDsJSON\x18\r \x01(\tH\x03R\x0fevidenceIDsJSON\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0f\n" +
	"\r_responseJSONB\x0e\n" +
	"\f_responseRefB\x0f\n" +
	"\r_errorMessageB\x12\n" +
	"\x10_evidenceIDsJSON\"\x9e\x03\n" +
	"\x17CreateAIToolCallRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x1a\n" +
	"\bnodeName\x18\x03 \x01(\tR\bnodeName\x12\x1a\n" +
	"\btoolName\x18\x04 \x01(\tR\btoolName\x12 \n" +
	"\vrequestJSON\x18\x05 \x01(\tR\vrequestJSON\x12'\n" +
	"\fresponseJSON\x18\x06 \x01(\tH\x00R\fresponseJSON\x88\x01\x01\x12%\n" +
	"\vresponseRef\x18\a \x01(\tH\x01R\vresponseRef\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1c\n" +
	"\tlatencyMs\x18\t \x01(\x03R\tlatencyMs\x12'\n" +
	"\ferrorMessage\x18\n" +
	" \x01(\tH\x02R\ferrorMessage\x88\x01\x01\x12 \n" +
	"\vevidenceIDs\x18\v \x03(\tR\vevidenceIDsB\x0f\n" +
	"\r_responseJSONB\x0e\n" +
	"\f_responseRefB\x0f\n" +
	"\r_errorMessage\":\n" +
	"\x18CreateAIToolCallResponse\x12\x1e\n" +
	"\n" +
	"toolCallID\x18\x01 \x01(\tR\n" +
	"toolCallID\"{\n" +
	"\x16ListAIToolCallsRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x15\n" +
	"\x03seq\x18\x04 \x01(\x03H\x00R\x03seq\x88\x01\x01B\x06\n" +
	"\x04_seq\"q\n" +
	"\x17ListAIToolCallsResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x126\n" +
	"\ttoolCalls\x18\x02 \x03(\v2\x18.apiserver.v1.AIToolCallR\ttoolCallsB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_ai_job_proto_rawDescOnce sync.Once
	file_apiserver_v1_ai_job_proto_rawDescData []byte
)

func file_apiserver_v1_ai_job_proto_rawDescGZIP() []byte {
	file_apiserver_v1_ai_job_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_ai_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_ai_job_proto_rawDesc), len(file_apiserver_v1_ai_job_proto_rawDesc)))
	})
	return file_apiserver_v1_ai_job_proto_rawDescData
}

var file_apiserver_v1_ai_job_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_apiserver_v1_ai_job_proto_goTypes = []any{
	(*AIJob)(nil),                      // 0: apiserver.v1.AIJob
	(*RunAIJobRequest)(nil),            // 1: apiserver.v1.RunAIJobRequest
	(*RunAIJobResponse)(nil),           // 2: apiserver.v1.RunAIJobResponse
	(*GetAIJobRequest)(nil),            // 3: apiserver.v1.GetAIJobRequest
	(*GetAIJobResponse)(nil),           // 4: apiserver.v1.GetAIJobResponse
	(*ListAIJobsRequest)(nil),          // 5: apiserver.v1.ListAIJobsRequest
	(*ListAIJobsResponse)(nil),         // 6: apiserver.v1.ListAIJobsResponse
	(*ListIncidentAIJobsRequest)(nil),  // 7: apiserver.v1.ListIncidentAIJobsRequest
	(*ListIncidentAIJobsResponse)(nil), // 8: apiserver.v1.ListIncidentAIJobsResponse
	(*StartAIJobRequest)(nil),          // 9: apiserver.v1.StartAIJobRequest
	(*StartAIJobResponse)(nil),         // 10: apiserver.v1.StartAIJobResponse
	(*ResolvedToolProvider)(nil),       // 11: apiserver.v1.ResolvedToolProvider
	(*ToolMetadataRef)(nil),            // 12: apiserver.v1.ToolMetadataRef
	(*CancelAIJobRequest)(nil),         // 13: apiserver.v1.CancelAIJobRequest
	(*CancelAIJobResponse)(nil),        // 14: apiserver.v1.CancelAIJobResponse
	(*FinalizeAIJobRequest)(nil),       // 15: apiserver.v1.FinalizeAIJobRequest
	(*FinalizeAIJobResponse)(nil),      // 16: apiserver.v1.FinalizeAIJobResponse
	(*AIToolCall)(nil),                 // 17: apiserver.v1.AIToolCall
	(*CreateAIToolCallRequest)(nil),    // 18: apiserver.v1.CreateAIToolCallRequest
	(*CreateAIToolCallResponse)(nil),   // 19: apiserver.v1.CreateAIToolCallResponse
	(*ListAIToolCallsRequest)(nil),     // 20: apiserver.v1.ListAIToolCallsRequest
	(*ListAIToolCallsResponse)(nil),    // 21: apiserver.v1.ListAIToolCallsResponse
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
}
var file_apiserver_v1_ai_job_proto_depIdxs = []int32{
	22, // 0: apiserver.v1.AIJob.timeRangeStart:type_name -> google.protobuf.Timestamp
	22, // 1: apiserver.v1.AIJob.timeRangeEnd:type_name -> google.protobuf.Timestamp
	22, // 2: apiserver.v1.AIJob.createdAt:type_name -> google.protobuf.Timestamp
	22, // 3: apiserver.v1.AIJob.startedAt:type_name -> google.protobuf.Timestamp
	22, // 4: apiserver.v1.AIJob.finishedAt:type_name -> google.protobuf.Timestamp
	22, // 5: apiserver.v1.RunAIJobRequest.timeRangeStart:type_name -> google.protobuf.Timestamp
	22, // 6: apiserver.v1.RunAIJobRequest.timeRangeEnd:type_name -> google.protobuf.Timestamp
	0,  // 7: apiserver.v1.GetAIJobResponse.job:type_name -> apiserver.v1.AIJob
	0,  // 8: apiserver.v1.ListAIJobsResponse.jobs:type_name -> apiserver.v1.AIJob
	0,  // 9: apiserver.v1.ListIncidentAIJobsResponse.jobs:type_name -> apiserver.v1.AIJob
	11, // 10: apiserver.v1.StartAIJobResponse.resolvedToolProviders:type_name -> apiserver.v1.ResolvedToolProvider
	12, // 11: apiserver.v1.ResolvedToolProvider.toolMetadata:type_name -> apiserver.v1.ToolMetadataRef
	22, // 12: apiserver.v1.AIToolCall.createdAt:type_name -> google.protobuf.Timestamp
	17, // 13: apiserver.v1.ListAIToolCallsResponse.toolCalls:type_name -> apiserver.v1.AIToolCall
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_apiserver_v1_ai_job_proto_init() }
func file_apiserver_v1_ai_job_proto_init() {
	if File_apiserver_v1_ai_job_proto != nil {
		return
	}
	file_apiserver_v1_ai_job_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[10].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[11].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[12].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[13].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[15].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[17].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[18].OneofWrappers = []any{}
	file_apiserver_v1_ai_job_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_ai_job_proto_rawDesc), len(file_apiserver_v1_ai_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_ai_job_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_ai_job_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_ai_job_proto_msgTypes,
	}.Build()
	File_apiserver_v1_ai_job_proto = out.File
	file_apiserver_v1_ai_job_proto_goTypes = nil
	file_apiserver_v1_ai_job_proto_depIdxs = nil
}
