// AlertingPolicy API 定义：告警策略的请求和响应消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apiserver/v1/alerting_policy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertingPolicy 表示告警策略配置
// 支持版本管理和激活/回滚机制
type AlertingPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示策略唯一标识（自增主键）
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name 表示策略名称（唯一）
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description 表示策略描述
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// lineageID 表示逻辑策略版本链归属 ID（用于关联同一策略的多个版本）
	LineageID string `protobuf:"bytes,4,opt,name=lineageID,proto3" json:"lineageID,omitempty"`
	// version 表示版本号（自动递增）
	Version int32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// configJSON 表示策略配置 JSON
	ConfigJSON string `protobuf:"bytes,6,opt,name=configJSON,proto3" json:"configJSON,omitempty"`
	// active 表示是否激活（同一时间只能有一个激活）
	Active bool `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	// activatedAt 表示激活时间
	ActivatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=activatedAt,proto3,oneof" json:"activatedAt,omitempty"`
	// activatedBy 表示激活人
	ActivatedBy *string `protobuf:"bytes,9,opt,name=activatedBy,proto3,oneof" json:"activatedBy,omitempty"`
	// previousVersion 表示前一个版本号（用于回滚）
	PreviousVersion *int32 `protobuf:"varint,10,opt,name=previousVersion,proto3,oneof" json:"previousVersion,omitempty"`
	// createdBy 表示创建人
	CreatedBy string `protobuf:"bytes,11,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// updatedBy 表示更新人
	UpdatedBy *string `protobuf:"bytes,12,opt,name=updatedBy,proto3,oneof" json:"updatedBy,omitempty"`
	// createdAt 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertingPolicy) Reset() {
	*x = AlertingPolicy{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertingPolicy) ProtoMessage() {}

func (x *AlertingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertingPolicy.ProtoReflect.Descriptor instead.
func (*AlertingPolicy) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{0}
}

func (x *AlertingPolicy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlertingPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertingPolicy) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AlertingPolicy) GetLineageID() string {
	if x != nil {
		return x.LineageID
	}
	return ""
}

func (x *AlertingPolicy) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AlertingPolicy) GetConfigJSON() string {
	if x != nil {
		return x.ConfigJSON
	}
	return ""
}

func (x *AlertingPolicy) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AlertingPolicy) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *AlertingPolicy) GetActivatedBy() string {
	if x != nil && x.ActivatedBy != nil {
		return *x.ActivatedBy
	}
	return ""
}

func (x *AlertingPolicy) GetPreviousVersion() int32 {
	if x != nil && x.PreviousVersion != nil {
		return *x.PreviousVersion
	}
	return 0
}

func (x *AlertingPolicy) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AlertingPolicy) GetUpdatedBy() string {
	if x != nil && x.UpdatedBy != nil {
		return *x.UpdatedBy
	}
	return ""
}

func (x *AlertingPolicy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AlertingPolicy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateAlertingPolicyRequest 表示创建告警策略请求
type CreateAlertingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 表示策略名称（必填）
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description 表示策略描述
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// configJSON 表示策略配置 JSON（必填）
	ConfigJSON    string `protobuf:"bytes,3,opt,name=configJSON,proto3" json:"configJSON,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertingPolicyRequest) Reset() {
	*x = CreateAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertingPolicyRequest) ProtoMessage() {}

func (x *CreateAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlertingPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertingPolicyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateAlertingPolicyRequest) GetConfigJSON() string {
	if x != nil {
		return x.ConfigJSON
	}
	return ""
}

// CreateAlertingPolicyResponse 表示创建告警策略响应
type CreateAlertingPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// alertingPolicy 表示创建的告警策略信息
	AlertingPolicy *AlertingPolicy `protobuf:"bytes,1,opt,name=alertingPolicy,proto3" json:"alertingPolicy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAlertingPolicyResponse) Reset() {
	*x = CreateAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertingPolicyResponse) ProtoMessage() {}

func (x *CreateAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAlertingPolicyResponse) GetAlertingPolicy() *AlertingPolicy {
	if x != nil {
		return x.AlertingPolicy
	}
	return nil
}

// GetAlertingPolicyRequest 表示获取告警策略请求
type GetAlertingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示要获取的告警策略 ID
	// @gotags: uri:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertingPolicyRequest) Reset() {
	*x = GetAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertingPolicyRequest) ProtoMessage() {}

func (x *GetAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertingPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetAlertingPolicyResponse 表示获取告警策略响应
type GetAlertingPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// alertingPolicy 表示返回的告警策略信息
	AlertingPolicy *AlertingPolicy `protobuf:"bytes,1,opt,name=alertingPolicy,proto3" json:"alertingPolicy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAlertingPolicyResponse) Reset() {
	*x = GetAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertingPolicyResponse) ProtoMessage() {}

func (x *GetAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertingPolicyResponse) GetAlertingPolicy() *AlertingPolicy {
	if x != nil {
		return x.AlertingPolicy
	}
	return nil
}

// ListAlertingPoliciesRequest 表示获取告警策略列表请求
type ListAlertingPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// name 表示可选的名称过滤
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// active 表示可选的激活状态过滤
	Active        *bool `protobuf:"varint,4,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertingPoliciesRequest) Reset() {
	*x = ListAlertingPoliciesRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertingPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertingPoliciesRequest) ProtoMessage() {}

func (x *ListAlertingPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertingPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListAlertingPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{5}
}

func (x *ListAlertingPoliciesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAlertingPoliciesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAlertingPoliciesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListAlertingPoliciesRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

// ListAlertingPoliciesResponse 表示获取告警策略列表响应
type ListAlertingPoliciesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示总数
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// alertingPolicies 表示告警策略列表
	AlertingPolicies []*AlertingPolicy `protobuf:"bytes,2,rep,name=alertingPolicies,proto3" json:"alertingPolicies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListAlertingPoliciesResponse) Reset() {
	*x = ListAlertingPoliciesResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertingPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertingPoliciesResponse) ProtoMessage() {}

func (x *ListAlertingPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertingPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListAlertingPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ListAlertingPoliciesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAlertingPoliciesResponse) GetAlertingPolicies() []*AlertingPolicy {
	if x != nil {
		return x.AlertingPolicies
	}
	return nil
}

// UpdateAlertingPolicyRequest 表示更新告警策略请求
type UpdateAlertingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示要更新的告警策略 ID
	// @gotags: uri:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	// name 表示策略名称
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// description 表示策略描述
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// configJSON 表示策略配置 JSON
	ConfigJSON *string `protobuf:"bytes,4,opt,name=configJSON,proto3,oneof" json:"configJSON,omitempty"`
	// expectedVersion 表示期望的版本号（用于乐观锁）
	ExpectedVersion *int32 `protobuf:"varint,5,opt,name=expectedVersion,proto3,oneof" json:"expectedVersion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateAlertingPolicyRequest) Reset() {
	*x = UpdateAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertingPolicyRequest) ProtoMessage() {}

func (x *UpdateAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAlertingPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAlertingPolicyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAlertingPolicyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateAlertingPolicyRequest) GetConfigJSON() string {
	if x != nil && x.ConfigJSON != nil {
		return *x.ConfigJSON
	}
	return ""
}

func (x *UpdateAlertingPolicyRequest) GetExpectedVersion() int32 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

// UpdateAlertingPolicyResponse 表示更新告警策略响应
type UpdateAlertingPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// alertingPolicy 表示更新后的告警策略信息
	AlertingPolicy *AlertingPolicy `protobuf:"bytes,1,opt,name=alertingPolicy,proto3" json:"alertingPolicy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAlertingPolicyResponse) Reset() {
	*x = UpdateAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertingPolicyResponse) ProtoMessage() {}

func (x *UpdateAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAlertingPolicyResponse) GetAlertingPolicy() *AlertingPolicy {
	if x != nil {
		return x.AlertingPolicy
	}
	return nil
}

// DeleteAlertingPolicyRequest 表示删除告警策略请求
type DeleteAlertingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示要删除的告警策略 ID
	// @gotags: uri:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertingPolicyRequest) Reset() {
	*x = DeleteAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertingPolicyRequest) ProtoMessage() {}

func (x *DeleteAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAlertingPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteAlertingPolicyResponse 表示删除告警策略响应
type DeleteAlertingPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertingPolicyResponse) Reset() {
	*x = DeleteAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertingPolicyResponse) ProtoMessage() {}

func (x *DeleteAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{10}
}

// ActivateAlertingPolicyRequest 表示激活告警策略请求
type ActivateAlertingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示要激活的告警策略 ID
	// @gotags: uri:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	// operator 表示操作者（可选，默认从上下文获取）
	Operator      *string `protobuf:"bytes,2,opt,name=operator,proto3,oneof" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAlertingPolicyRequest) Reset() {
	*x = ActivateAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAlertingPolicyRequest) ProtoMessage() {}

func (x *ActivateAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*ActivateAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{11}
}

func (x *ActivateAlertingPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivateAlertingPolicyRequest) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

// ActivateAlertingPolicyResponse 表示激活告警策略响应
type ActivateAlertingPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAlertingPolicyResponse) Reset() {
	*x = ActivateAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAlertingPolicyResponse) ProtoMessage() {}

func (x *ActivateAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*ActivateAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{12}
}

// DeactivateAlertingPolicyRequest 表示停用告警策略请求
type DeactivateAlertingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示要停用的告警策略 ID
	// @gotags: uri:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateAlertingPolicyRequest) Reset() {
	*x = DeactivateAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateAlertingPolicyRequest) ProtoMessage() {}

func (x *DeactivateAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*DeactivateAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{13}
}

func (x *DeactivateAlertingPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeactivateAlertingPolicyResponse 表示停用告警策略响应
type DeactivateAlertingPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateAlertingPolicyResponse) Reset() {
	*x = DeactivateAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateAlertingPolicyResponse) ProtoMessage() {}

func (x *DeactivateAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*DeactivateAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{14}
}

// RollbackAlertingPolicyRequest 表示回滚告警策略请求
type RollbackAlertingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示要回滚的告警策略 ID
	// @gotags: uri:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" uri:"id"`
	// version 表示要回滚到的版本号（必填）
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// operator 表示操作者（可选，默认从上下文获取）
	Operator      *string `protobuf:"bytes,3,opt,name=operator,proto3,oneof" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackAlertingPolicyRequest) Reset() {
	*x = RollbackAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackAlertingPolicyRequest) ProtoMessage() {}

func (x *RollbackAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*RollbackAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{15}
}

func (x *RollbackAlertingPolicyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RollbackAlertingPolicyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RollbackAlertingPolicyRequest) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

// RollbackAlertingPolicyResponse 表示回滚告警策略响应
type RollbackAlertingPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackAlertingPolicyResponse) Reset() {
	*x = RollbackAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackAlertingPolicyResponse) ProtoMessage() {}

func (x *RollbackAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*RollbackAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{16}
}

// GetActiveAlertingPolicyRequest 表示获取当前激活的告警策略请求
type GetActiveAlertingPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAlertingPolicyRequest) Reset() {
	*x = GetActiveAlertingPolicyRequest{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAlertingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAlertingPolicyRequest) ProtoMessage() {}

func (x *GetActiveAlertingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAlertingPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetActiveAlertingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{17}
}

// GetActiveAlertingPolicyResponse 表示获取当前激活的告警策略响应
type GetActiveAlertingPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// alertingPolicy 表示当前激活的告警策略
	AlertingPolicy *AlertingPolicy `protobuf:"bytes,1,opt,name=alertingPolicy,proto3" json:"alertingPolicy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetActiveAlertingPolicyResponse) Reset() {
	*x = GetActiveAlertingPolicyResponse{}
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAlertingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAlertingPolicyResponse) ProtoMessage() {}

func (x *GetActiveAlertingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alerting_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAlertingPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetActiveAlertingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alerting_policy_proto_rawDescGZIP(), []int{18}
}

func (x *GetActiveAlertingPolicyResponse) GetAlertingPolicy() *AlertingPolicy {
	if x != nil {
		return x.AlertingPolicy
	}
	return nil
}

var File_apiserver_v1_alerting_policy_proto protoreflect.FileDescriptor

const file_apiserver_v1_alerting_policy_proto_rawDesc = "" +
	"\n" +
	"\"apiserver/v1/alerting_policy.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x04\n" +
	"\x0eAlertingPolicy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1c\n" +
	"\tlineageID\x18\x04 \x01(\tR\tlineageID\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12\x1e\n" +
	"\n" +
	"configJSON\x18\x06 \x01(\tR\n" +
	"configJSON\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\x12A\n" +
	"\vactivatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vactivatedAt\x88\x01\x01\x12%\n" +
	"\vactivatedBy\x18\t \x01(\tH\x02R\vactivatedBy\x88\x01\x01\x12-\n" +
	"\x0fpreviousVersion\x18\n" +
	" \x01(\x05H\x03R\x0fpreviousVersion\x88\x01\x01\x12\x1c\n" +
	"\tcreatedBy\x18\v \x01(\tR\tcreatedBy\x12!\n" +
	"\tupdatedBy\x18\f \x01(\tH\x04R\tupdatedBy\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_activatedAtB\x0e\n" +
	"\f_activatedByB\x12\n" +
	"\x10_previousVersionB\f\n" +
	"\n" +
	"_updatedBy\"\x88\x01\n" +
	"\x1bCreateAlertingPolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"configJSON\x18\x03 \x01(\tR\n" +
	"configJSONB\x0e\n" +
	"\f_description\"d\n" +
	"\x1cCreateAlertingPolicyResponse\x12D\n" +
	"\x0ealertingPolicy\x18\x01 \x01(\v2\x1c.apiserver.v1.AlertingPolicyR\x0ealertingPolicy\"*\n" +
	"\x18GetAlertingPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"a\n" +
	"\x19GetAlertingPolicyResponse\x12D\n" +
	"\x0ealertingPolicy\x18\x01 \x01(\v2\x1c.apiserver.v1.AlertingPolicyR\x0ealertingPolicy\"\x95\x01\n" +
	"\x1bListAlertingPoliciesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x04 \x01(\bH\x01R\x06active\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_active\"\x88\x01\n" +
	"\x1cListAlertingPoliciesResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12H\n" +
	"\x10alertingPolicies\x18\x02 \x03(\v2\x1c.apiserver.v1.AlertingPolicyR\x10alertingPolicies\"\xfd\x01\n" +
	"\x1bUpdateAlertingPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12#\n" +
	"\n" +
	"configJSON\x18\x04 \x01(\tH\x02R\n" +
	"configJSON\x88\x01\x01\x12-\n" +
	"\x0fexpectedVersion\x18\x05 \x01(\x05H\x03R\x0fexpectedVersion\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_configJSONB\x12\n" +
	"\x10_expectedVersion\"d\n" +
	"\x1cUpdateAlertingPolicyResponse\x12D\n" +
	"\x0ealertingPolicy\x18\x01 \x01(\v2\x1c.apiserver.v1.AlertingPolicyR\x0ealertingPolicy\"-\n" +
	"\x1bDeleteAlertingPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1e\n" +
	"\x1cDeleteAlertingPolicyResponse\"]\n" +
	"\x1dActivateAlertingPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\boperator\x18\x02 \x01(\tH\x00R\boperator\x88\x01\x01B\v\n" +
	"\t_operator\" \n" +
	"\x1eActivateAlertingPolicyResponse\"1\n" +
	"\x1fDeactivateAlertingPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\"\n" +
	" DeactivateAlertingPolicyResponse\"w\n" +
	"\x1dRollbackAlertingPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1f\n" +
	"\boperator\x18\x03 \x01(\tH\x00R\boperator\x88\x01\x01B\v\n" +
	"\t_operator\" \n" +
	"\x1eRollbackAlertingPolicyResponse\" \n" +
	"\x1eGetActiveAlertingPolicyRequest\"g\n" +
	"\x1fGetActiveAlertingPolicyResponse\x12D\n" +
	"\x0ealertingPolicy\x18\x01 \x01(\v2\x1c.apiserver.v1.AlertingPolicyR\x0ealertingPolicyB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_alerting_policy_proto_rawDescOnce sync.Once
	file_apiserver_v1_alerting_policy_proto_rawDescData []byte
)

func file_apiserver_v1_alerting_policy_proto_rawDescGZIP() []byte {
	file_apiserver_v1_alerting_policy_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_alerting_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_alerting_policy_proto_rawDesc), len(file_apiserver_v1_alerting_policy_proto_rawDesc)))
	})
	return file_apiserver_v1_alerting_policy_proto_rawDescData
}

var file_apiserver_v1_alerting_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_apiserver_v1_alerting_policy_proto_goTypes = []any{
	(*AlertingPolicy)(nil),                   // 0: apiserver.v1.AlertingPolicy
	(*CreateAlertingPolicyRequest)(nil),      // 1: apiserver.v1.CreateAlertingPolicyRequest
	(*CreateAlertingPolicyResponse)(nil),     // 2: apiserver.v1.CreateAlertingPolicyResponse
	(*GetAlertingPolicyRequest)(nil),         // 3: apiserver.v1.GetAlertingPolicyRequest
	(*GetAlertingPolicyResponse)(nil),        // 4: apiserver.v1.GetAlertingPolicyResponse
	(*ListAlertingPoliciesRequest)(nil),      // 5: apiserver.v1.ListAlertingPoliciesRequest
	(*ListAlertingPoliciesResponse)(nil),     // 6: apiserver.v1.ListAlertingPoliciesResponse
	(*UpdateAlertingPolicyRequest)(nil),      // 7: apiserver.v1.UpdateAlertingPolicyRequest
	(*UpdateAlertingPolicyResponse)(nil),     // 8: apiserver.v1.UpdateAlertingPolicyResponse
	(*DeleteAlertingPolicyRequest)(nil),      // 9: apiserver.v1.DeleteAlertingPolicyRequest
	(*DeleteAlertingPolicyResponse)(nil),     // 10: apiserver.v1.DeleteAlertingPolicyResponse
	(*ActivateAlertingPolicyRequest)(nil),    // 11: apiserver.v1.ActivateAlertingPolicyRequest
	(*ActivateAlertingPolicyResponse)(nil),   // 12: apiserver.v1.ActivateAlertingPolicyResponse
	(*DeactivateAlertingPolicyRequest)(nil),  // 13: apiserver.v1.DeactivateAlertingPolicyRequest
	(*DeactivateAlertingPolicyResponse)(nil), // 14: apiserver.v1.DeactivateAlertingPolicyResponse
	(*RollbackAlertingPolicyRequest)(nil),    // 15: apiserver.v1.RollbackAlertingPolicyRequest
	(*RollbackAlertingPolicyResponse)(nil),   // 16: apiserver.v1.RollbackAlertingPolicyResponse
	(*GetActiveAlertingPolicyRequest)(nil),   // 17: apiserver.v1.GetActiveAlertingPolicyRequest
	(*GetActiveAlertingPolicyResponse)(nil),  // 18: apiserver.v1.GetActiveAlertingPolicyResponse
	(*timestamppb.Timestamp)(nil),            // 19: google.protobuf.Timestamp
}
var file_apiserver_v1_alerting_policy_proto_depIdxs = []int32{
	19, // 0: apiserver.v1.AlertingPolicy.activatedAt:type_name -> google.protobuf.Timestamp
	19, // 1: apiserver.v1.AlertingPolicy.createdAt:type_name -> google.protobuf.Timestamp
	19, // 2: apiserver.v1.AlertingPolicy.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: apiserver.v1.CreateAlertingPolicyResponse.alertingPolicy:type_name -> apiserver.v1.AlertingPolicy
	0,  // 4: apiserver.v1.GetAlertingPolicyResponse.alertingPolicy:type_name -> apiserver.v1.AlertingPolicy
	0,  // 5: apiserver.v1.ListAlertingPoliciesResponse.alertingPolicies:type_name -> apiserver.v1.AlertingPolicy
	0,  // 6: apiserver.v1.UpdateAlertingPolicyResponse.alertingPolicy:type_name -> apiserver.v1.AlertingPolicy
	0,  // 7: apiserver.v1.GetActiveAlertingPolicyResponse.alertingPolicy:type_name -> apiserver.v1.AlertingPolicy
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_apiserver_v1_alerting_policy_proto_init() }
func file_apiserver_v1_alerting_policy_proto_init() {
	if File_apiserver_v1_alerting_policy_proto != nil {
		return
	}
	file_apiserver_v1_alerting_policy_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_alerting_policy_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_alerting_policy_proto_msgTypes[5].OneofWrappers = []any{}
	file_apiserver_v1_alerting_policy_proto_msgTypes[7].OneofWrappers = []any{}
	file_apiserver_v1_alerting_policy_proto_msgTypes[11].OneofWrappers = []any{}
	file_apiserver_v1_alerting_policy_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_alerting_policy_proto_rawDesc), len(file_apiserver_v1_alerting_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_alerting_policy_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_alerting_policy_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_alerting_policy_proto_msgTypes,
	}.Build()
	File_apiserver_v1_alerting_policy_proto = out.File
	file_apiserver_v1_alerting_policy_proto_goTypes = nil
	file_apiserver_v1_alerting_policy_proto_depIdxs = nil
}
