// AlertEvent API messages for ingest/current/history/ack.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apiserver/v1/alert_event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertEvent is one normalized alert event row (history/current in same table).
type AlertEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// eventID is the business event id, e.g. alert-event-xxxxxx.
	EventID string `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	// incidentID is linked incident id (optional).
	IncidentID *string `protobuf:"bytes,2,opt,name=incidentID,proto3,oneof" json:"incidentID,omitempty"`
	// fingerprint is the dedup/merge key.
	Fingerprint string `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// dedupKey defaults to fingerprint in P0.
	DedupKey *string `protobuf:"bytes,4,opt,name=dedupKey,proto3,oneof" json:"dedupKey,omitempty"`
	// source is alertmanager|watchalert|custom.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// status is firing|resolved|suppressed|invalid.
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// severity is normalized severity.
	Severity        string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	AlertName       *string                `protobuf:"bytes,8,opt,name=alertName,proto3,oneof" json:"alertName,omitempty"`
	Service         *string                `protobuf:"bytes,9,opt,name=service,proto3,oneof" json:"service,omitempty"`
	Cluster         *string                `protobuf:"bytes,10,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	Namespace       *string                `protobuf:"bytes,11,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Workload        *string                `protobuf:"bytes,12,opt,name=workload,proto3,oneof" json:"workload,omitempty"`
	StartsAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=startsAt,proto3,oneof" json:"startsAt,omitempty"`
	EndsAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=endsAt,proto3,oneof" json:"endsAt,omitempty"`
	LastSeenAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=lastSeenAt,proto3" json:"lastSeenAt,omitempty"`
	LabelsJSON      *string                `protobuf:"bytes,16,opt,name=labelsJSON,proto3,oneof" json:"labelsJSON,omitempty"`
	AnnotationsJSON *string                `protobuf:"bytes,17,opt,name=annotationsJSON,proto3,oneof" json:"annotationsJSON,omitempty"`
	GeneratorURL    *string                `protobuf:"bytes,18,opt,name=generatorURL,proto3,oneof" json:"generatorURL,omitempty"`
	RawEventJSON    *string                `protobuf:"bytes,19,opt,name=rawEventJSON,proto3,oneof" json:"rawEventJSON,omitempty"`
	IsCurrent       bool                   `protobuf:"varint,20,opt,name=isCurrent,proto3" json:"isCurrent,omitempty"`
	AckedAt         *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=ackedAt,proto3,oneof" json:"ackedAt,omitempty"`
	AckedBy         *string                `protobuf:"bytes,22,opt,name=ackedBy,proto3,oneof" json:"ackedBy,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// isSilenced indicates this event matched an active silence window.
	IsSilenced bool `protobuf:"varint,25,opt,name=isSilenced,proto3" json:"isSilenced,omitempty"`
	// silenceID is present when isSilenced=true.
	SilenceID     *string `protobuf:"bytes,26,opt,name=silenceID,proto3,oneof" json:"silenceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEvent) Reset() {
	*x = AlertEvent{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvent) ProtoMessage() {}

func (x *AlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvent.ProtoReflect.Descriptor instead.
func (*AlertEvent) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{0}
}

func (x *AlertEvent) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *AlertEvent) GetIncidentID() string {
	if x != nil && x.IncidentID != nil {
		return *x.IncidentID
	}
	return ""
}

func (x *AlertEvent) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *AlertEvent) GetDedupKey() string {
	if x != nil && x.DedupKey != nil {
		return *x.DedupKey
	}
	return ""
}

func (x *AlertEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AlertEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlertEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertEvent) GetAlertName() string {
	if x != nil && x.AlertName != nil {
		return *x.AlertName
	}
	return ""
}

func (x *AlertEvent) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *AlertEvent) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *AlertEvent) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *AlertEvent) GetWorkload() string {
	if x != nil && x.Workload != nil {
		return *x.Workload
	}
	return ""
}

func (x *AlertEvent) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *AlertEvent) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *AlertEvent) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *AlertEvent) GetLabelsJSON() string {
	if x != nil && x.LabelsJSON != nil {
		return *x.LabelsJSON
	}
	return ""
}

func (x *AlertEvent) GetAnnotationsJSON() string {
	if x != nil && x.AnnotationsJSON != nil {
		return *x.AnnotationsJSON
	}
	return ""
}

func (x *AlertEvent) GetGeneratorURL() string {
	if x != nil && x.GeneratorURL != nil {
		return *x.GeneratorURL
	}
	return ""
}

func (x *AlertEvent) GetRawEventJSON() string {
	if x != nil && x.RawEventJSON != nil {
		return *x.RawEventJSON
	}
	return ""
}

func (x *AlertEvent) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *AlertEvent) GetAckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AckedAt
	}
	return nil
}

func (x *AlertEvent) GetAckedBy() string {
	if x != nil && x.AckedBy != nil {
		return *x.AckedBy
	}
	return ""
}

func (x *AlertEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AlertEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AlertEvent) GetIsSilenced() bool {
	if x != nil {
		return x.IsSilenced
	}
	return false
}

func (x *AlertEvent) GetSilenceID() string {
	if x != nil && x.SilenceID != nil {
		return *x.SilenceID
	}
	return ""
}

// IngestAlertEventRequest ingests one normalized alert payload.
type IngestAlertEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// idempotencyKey supports retry-safe ingest.
	IdempotencyKey *string `protobuf:"bytes,1,opt,name=idempotencyKey,proto3,oneof" json:"idempotencyKey,omitempty"`
	// fingerprint may be omitted and derived deterministically.
	Fingerprint *string `protobuf:"bytes,2,opt,name=fingerprint,proto3,oneof" json:"fingerprint,omitempty"`
	// dedupKey defaults to fingerprint in P0.
	DedupKey *string `protobuf:"bytes,3,opt,name=dedupKey,proto3,oneof" json:"dedupKey,omitempty"`
	Source   *string `protobuf:"bytes,4,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// status is firing|resolved|suppressed.
	Status    string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Severity  string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	AlertName *string                `protobuf:"bytes,7,opt,name=alertName,proto3,oneof" json:"alertName,omitempty"`
	Service   *string                `protobuf:"bytes,8,opt,name=service,proto3,oneof" json:"service,omitempty"`
	Cluster   *string                `protobuf:"bytes,9,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	Namespace *string                `protobuf:"bytes,10,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Workload  *string                `protobuf:"bytes,11,opt,name=workload,proto3,oneof" json:"workload,omitempty"`
	StartsAt  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=startsAt,proto3,oneof" json:"startsAt,omitempty"`
	EndsAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=endsAt,proto3,oneof" json:"endsAt,omitempty"`
	// lastSeenAt defaults to now when omitted.
	LastSeenAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=lastSeenAt,proto3,oneof" json:"lastSeenAt,omitempty"`
	LabelsJSON      *string                `protobuf:"bytes,15,opt,name=labelsJSON,proto3,oneof" json:"labelsJSON,omitempty"`
	AnnotationsJSON *string                `protobuf:"bytes,16,opt,name=annotationsJSON,proto3,oneof" json:"annotationsJSON,omitempty"`
	GeneratorURL    *string                `protobuf:"bytes,17,opt,name=generatorURL,proto3,oneof" json:"generatorURL,omitempty"`
	RawEventJSON    *string                `protobuf:"bytes,18,opt,name=rawEventJSON,proto3,oneof" json:"rawEventJSON,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestAlertEventRequest) Reset() {
	*x = IngestAlertEventRequest{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAlertEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAlertEventRequest) ProtoMessage() {}

func (x *IngestAlertEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAlertEventRequest.ProtoReflect.Descriptor instead.
func (*IngestAlertEventRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{1}
}

func (x *IngestAlertEventRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *IngestAlertEventRequest) GetFingerprint() string {
	if x != nil && x.Fingerprint != nil {
		return *x.Fingerprint
	}
	return ""
}

func (x *IngestAlertEventRequest) GetDedupKey() string {
	if x != nil && x.DedupKey != nil {
		return *x.DedupKey
	}
	return ""
}

func (x *IngestAlertEventRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *IngestAlertEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestAlertEventRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *IngestAlertEventRequest) GetAlertName() string {
	if x != nil && x.AlertName != nil {
		return *x.AlertName
	}
	return ""
}

func (x *IngestAlertEventRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *IngestAlertEventRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *IngestAlertEventRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *IngestAlertEventRequest) GetWorkload() string {
	if x != nil && x.Workload != nil {
		return *x.Workload
	}
	return ""
}

func (x *IngestAlertEventRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *IngestAlertEventRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *IngestAlertEventRequest) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *IngestAlertEventRequest) GetLabelsJSON() string {
	if x != nil && x.LabelsJSON != nil {
		return *x.LabelsJSON
	}
	return ""
}

func (x *IngestAlertEventRequest) GetAnnotationsJSON() string {
	if x != nil && x.AnnotationsJSON != nil {
		return *x.AnnotationsJSON
	}
	return ""
}

func (x *IngestAlertEventRequest) GetGeneratorURL() string {
	if x != nil && x.GeneratorURL != nil {
		return *x.GeneratorURL
	}
	return ""
}

func (x *IngestAlertEventRequest) GetRawEventJSON() string {
	if x != nil && x.RawEventJSON != nil {
		return *x.RawEventJSON
	}
	return ""
}

// IngestAlertEventResponse returns created/reused event result.
type IngestAlertEventResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventID     string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	IncidentID  *string                `protobuf:"bytes,2,opt,name=incidentID,proto3,oneof" json:"incidentID,omitempty"`
	Fingerprint string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Status      string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Reused      bool                   `protobuf:"varint,5,opt,name=reused,proto3" json:"reused,omitempty"`
	// mergeResult explains how current view changed.
	MergeResult string `protobuf:"bytes,6,opt,name=mergeResult,proto3" json:"mergeResult,omitempty"`
	// silenced indicates whether this ingest matched an active silence.
	Silenced bool `protobuf:"varint,7,opt,name=silenced,proto3" json:"silenced,omitempty"`
	// silenceID is present when silenced=true.
	SilenceID     *string `protobuf:"bytes,8,opt,name=silenceID,proto3,oneof" json:"silenceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAlertEventResponse) Reset() {
	*x = IngestAlertEventResponse{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAlertEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAlertEventResponse) ProtoMessage() {}

func (x *IngestAlertEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAlertEventResponse.ProtoReflect.Descriptor instead.
func (*IngestAlertEventResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{2}
}

func (x *IngestAlertEventResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *IngestAlertEventResponse) GetIncidentID() string {
	if x != nil && x.IncidentID != nil {
		return *x.IncidentID
	}
	return ""
}

func (x *IngestAlertEventResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *IngestAlertEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestAlertEventResponse) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

func (x *IngestAlertEventResponse) GetMergeResult() string {
	if x != nil {
		return x.MergeResult
	}
	return ""
}

func (x *IngestAlertEventResponse) GetSilenced() bool {
	if x != nil {
		return x.Silenced
	}
	return false
}

func (x *IngestAlertEventResponse) GetSilenceID() string {
	if x != nil && x.SilenceID != nil {
		return *x.SilenceID
	}
	return ""
}

// ListCurrentAlertEventsRequest lists current alert view.
type ListCurrentAlertEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// @gotags: form:"severity"
	Severity *string `protobuf:"bytes,3,opt,name=severity,proto3,oneof" json:"severity,omitempty" form:"severity"`
	// @gotags: form:"service"
	Service *string `protobuf:"bytes,4,opt,name=service,proto3,oneof" json:"service,omitempty" form:"service"`
	// @gotags: form:"cluster"
	Cluster *string `protobuf:"bytes,5,opt,name=cluster,proto3,oneof" json:"cluster,omitempty" form:"cluster"`
	// @gotags: form:"namespace"
	Namespace *string `protobuf:"bytes,6,opt,name=namespace,proto3,oneof" json:"namespace,omitempty" form:"namespace"`
	// @gotags: form:"fingerprint"
	Fingerprint *string `protobuf:"bytes,7,opt,name=fingerprint,proto3,oneof" json:"fingerprint,omitempty" form:"fingerprint"`
	// @gotags: form:"status"
	Status *string `protobuf:"bytes,8,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status"`
	// @gotags: form:"lastSeenStart"
	LastSeenStart *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=lastSeenStart,proto3,oneof" json:"lastSeenStart,omitempty" form:"lastSeenStart"`
	// @gotags: form:"lastSeenEnd"
	LastSeenEnd   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=lastSeenEnd,proto3,oneof" json:"lastSeenEnd,omitempty" form:"lastSeenEnd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrentAlertEventsRequest) Reset() {
	*x = ListCurrentAlertEventsRequest{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrentAlertEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrentAlertEventsRequest) ProtoMessage() {}

func (x *ListCurrentAlertEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrentAlertEventsRequest.ProtoReflect.Descriptor instead.
func (*ListCurrentAlertEventsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{3}
}

func (x *ListCurrentAlertEventsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCurrentAlertEventsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCurrentAlertEventsRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ListCurrentAlertEventsRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *ListCurrentAlertEventsRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ListCurrentAlertEventsRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ListCurrentAlertEventsRequest) GetFingerprint() string {
	if x != nil && x.Fingerprint != nil {
		return *x.Fingerprint
	}
	return ""
}

func (x *ListCurrentAlertEventsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListCurrentAlertEventsRequest) GetLastSeenStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenStart
	}
	return nil
}

func (x *ListCurrentAlertEventsRequest) GetLastSeenEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenEnd
	}
	return nil
}

// ListCurrentAlertEventsResponse returns current alert list.
type ListCurrentAlertEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Events        []*AlertEvent          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrentAlertEventsResponse) Reset() {
	*x = ListCurrentAlertEventsResponse{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrentAlertEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrentAlertEventsResponse) ProtoMessage() {}

func (x *ListCurrentAlertEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrentAlertEventsResponse.ProtoReflect.Descriptor instead.
func (*ListCurrentAlertEventsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{4}
}

func (x *ListCurrentAlertEventsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListCurrentAlertEventsResponse) GetEvents() []*AlertEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// ListHistoryAlertEventsRequest lists history events.
type ListHistoryAlertEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// @gotags: form:"severity"
	Severity *string `protobuf:"bytes,3,opt,name=severity,proto3,oneof" json:"severity,omitempty" form:"severity"`
	// @gotags: form:"service"
	Service *string `protobuf:"bytes,4,opt,name=service,proto3,oneof" json:"service,omitempty" form:"service"`
	// @gotags: form:"cluster"
	Cluster *string `protobuf:"bytes,5,opt,name=cluster,proto3,oneof" json:"cluster,omitempty" form:"cluster"`
	// @gotags: form:"namespace"
	Namespace *string `protobuf:"bytes,6,opt,name=namespace,proto3,oneof" json:"namespace,omitempty" form:"namespace"`
	// @gotags: form:"fingerprint"
	Fingerprint *string `protobuf:"bytes,7,opt,name=fingerprint,proto3,oneof" json:"fingerprint,omitempty" form:"fingerprint"`
	// @gotags: form:"status"
	Status *string `protobuf:"bytes,8,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status"`
	// @gotags: form:"incidentID"
	IncidentID *string `protobuf:"bytes,9,opt,name=incidentID,proto3,oneof" json:"incidentID,omitempty" form:"incidentID"`
	// @gotags: form:"lastSeenStart"
	LastSeenStart *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=lastSeenStart,proto3,oneof" json:"lastSeenStart,omitempty" form:"lastSeenStart"`
	// @gotags: form:"lastSeenEnd"
	LastSeenEnd   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=lastSeenEnd,proto3,oneof" json:"lastSeenEnd,omitempty" form:"lastSeenEnd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryAlertEventsRequest) Reset() {
	*x = ListHistoryAlertEventsRequest{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryAlertEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryAlertEventsRequest) ProtoMessage() {}

func (x *ListHistoryAlertEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryAlertEventsRequest.ProtoReflect.Descriptor instead.
func (*ListHistoryAlertEventsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{5}
}

func (x *ListHistoryAlertEventsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListHistoryAlertEventsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListHistoryAlertEventsRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ListHistoryAlertEventsRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *ListHistoryAlertEventsRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *ListHistoryAlertEventsRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ListHistoryAlertEventsRequest) GetFingerprint() string {
	if x != nil && x.Fingerprint != nil {
		return *x.Fingerprint
	}
	return ""
}

func (x *ListHistoryAlertEventsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListHistoryAlertEventsRequest) GetIncidentID() string {
	if x != nil && x.IncidentID != nil {
		return *x.IncidentID
	}
	return ""
}

func (x *ListHistoryAlertEventsRequest) GetLastSeenStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenStart
	}
	return nil
}

func (x *ListHistoryAlertEventsRequest) GetLastSeenEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenEnd
	}
	return nil
}

// ListHistoryAlertEventsResponse returns history list.
type ListHistoryAlertEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Events        []*AlertEvent          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryAlertEventsResponse) Reset() {
	*x = ListHistoryAlertEventsResponse{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryAlertEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryAlertEventsResponse) ProtoMessage() {}

func (x *ListHistoryAlertEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryAlertEventsResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryAlertEventsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{6}
}

func (x *ListHistoryAlertEventsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListHistoryAlertEventsResponse) GetEvents() []*AlertEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// AckAlertEventRequest acknowledges one alert event.
type AckAlertEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"eventID"
	EventID       string  `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty" uri:"eventID"`
	AckedBy       *string `protobuf:"bytes,2,opt,name=ackedBy,proto3,oneof" json:"ackedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckAlertEventRequest) Reset() {
	*x = AckAlertEventRequest{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAlertEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAlertEventRequest) ProtoMessage() {}

func (x *AckAlertEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAlertEventRequest.ProtoReflect.Descriptor instead.
func (*AckAlertEventRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{7}
}

func (x *AckAlertEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *AckAlertEventRequest) GetAckedBy() string {
	if x != nil && x.AckedBy != nil {
		return *x.AckedBy
	}
	return ""
}

// AckAlertEventResponse returns ack result.
type AckAlertEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	IncidentID    *string                `protobuf:"bytes,2,opt,name=incidentID,proto3,oneof" json:"incidentID,omitempty"`
	AckedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ackedAt,proto3" json:"ackedAt,omitempty"`
	AckedBy       string                 `protobuf:"bytes,4,opt,name=ackedBy,proto3" json:"ackedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckAlertEventResponse) Reset() {
	*x = AckAlertEventResponse{}
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAlertEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAlertEventResponse) ProtoMessage() {}

func (x *AckAlertEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_alert_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAlertEventResponse.ProtoReflect.Descriptor instead.
func (*AckAlertEventResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_alert_event_proto_rawDescGZIP(), []int{8}
}

func (x *AckAlertEventResponse) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *AckAlertEventResponse) GetIncidentID() string {
	if x != nil && x.IncidentID != nil {
		return *x.IncidentID
	}
	return ""
}

func (x *AckAlertEventResponse) GetAckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AckedAt
	}
	return nil
}

func (x *AckAlertEventResponse) GetAckedBy() string {
	if x != nil {
		return x.AckedBy
	}
	return ""
}

var File_apiserver_v1_alert_event_proto protoreflect.FileDescriptor

const file_apiserver_v1_alert_event_proto_rawDesc = "" +
	"\n" +
	"\x1eapiserver/v1/alert_event.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\t\n" +
	"\n" +
	"AlertEvent\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12#\n" +
	"\n" +
	"incidentID\x18\x02 \x01(\tH\x00R\n" +
	"incidentID\x88\x01\x01\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x12\x1f\n" +
	"\bdedupKey\x18\x04 \x01(\tH\x01R\bdedupKey\x88\x01\x01\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12!\n" +
	"\talertName\x18\b \x01(\tH\x02R\talertName\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\t \x01(\tH\x03R\aservice\x88\x01\x01\x12\x1d\n" +
	"\acluster\x18\n" +
	" \x01(\tH\x04R\acluster\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\v \x01(\tH\x05R\tnamespace\x88\x01\x01\x12\x1f\n" +
	"\bworkload\x18\f \x01(\tH\x06R\bworkload\x88\x01\x01\x12;\n" +
	"\bstartsAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\aR\bstartsAt\x88\x01\x01\x127\n" +
	"\x06endsAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\bR\x06endsAt\x88\x01\x01\x12:\n" +
	"\n" +
	"lastSeenAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12#\n" +
	"\n" +
	"labelsJSON\x18\x10 \x01(\tH\tR\n" +
	"labelsJSON\x88\x01\x01\x12-\n" +
	"\x0fannotationsJSON\x18\x11 \x01(\tH\n" +
	"R\x0fannotationsJSON\x88\x01\x01\x12'\n" +
	"\fgeneratorURL\x18\x12 \x01(\tH\vR\fgeneratorURL\x88\x01\x01\x12'\n" +
	"\frawEventJSON\x18\x13 \x01(\tH\fR\frawEventJSON\x88\x01\x01\x12\x1c\n" +
	"\tisCurrent\x18\x14 \x01(\bR\tisCurrent\x129\n" +
	"\aackedAt\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampH\rR\aackedAt\x88\x01\x01\x12\x1d\n" +
	"\aackedBy\x18\x16 \x01(\tH\x0eR\aackedBy\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1e\n" +
	"\n" +
	"isSilenced\x18\x19 \x01(\bR\n" +
	"isSilenced\x12!\n" +
	"\tsilenceID\x18\x1a \x01(\tH\x0fR\tsilenceID\x88\x01\x01B\r\n" +
	"\v_incidentIDB\v\n" +
	"\t_dedupKeyB\f\n" +
	"\n" +
	"_alertNameB\n" +
	"\n" +
	"\b_serviceB\n" +
	"\n" +
	"\b_clusterB\f\n" +
	"\n" +
	"_namespaceB\v\n" +
	"\t_workloadB\v\n" +
	"\t_startsAtB\t\n" +
	"\a_endsAtB\r\n" +
	"\v_labelsJSONB\x12\n" +
	"\x10_annotationsJSONB\x0f\n" +
	"\r_generatorURLB\x0f\n" +
	"\r_rawEventJSONB\n" +
	"\n" +
	"\b_ackedAtB\n" +
	"\n" +
	"\b_ackedByB\f\n" +
	"\n" +
	"_silenceID\"\xc9\a\n" +
	"\x17IngestAlertEventRequest\x12+\n" +
	"\x0eidempotencyKey\x18\x01 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01\x12%\n" +
	"\vfingerprint\x18\x02 \x01(\tH\x01R\vfingerprint\x88\x01\x01\x12\x1f\n" +
	"\bdedupKey\x18\x03 \x01(\tH\x02R\bdedupKey\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x04 \x01(\tH\x03R\x06source\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12!\n" +
	"\talertName\x18\a \x01(\tH\x04R\talertName\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\b \x01(\tH\x05R\aservice\x88\x01\x01\x12\x1d\n" +
	"\acluster\x18\t \x01(\tH\x06R\acluster\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\n" +
	" \x01(\tH\aR\tnamespace\x88\x01\x01\x12\x1f\n" +
	"\bworkload\x18\v \x01(\tH\bR\bworkload\x88\x01\x01\x12;\n" +
	"\bstartsAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\tR\bstartsAt\x88\x01\x01\x127\n" +
	"\x06endsAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\n" +
	"R\x06endsAt\x88\x01\x01\x12?\n" +
	"\n" +
	"lastSeenAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\vR\n" +
	"lastSeenAt\x88\x01\x01\x12#\n" +
	"\n" +
	"labelsJSON\x18\x0f \x01(\tH\fR\n" +
	"labelsJSON\x88\x01\x01\x12-\n" +
	"\x0fannotationsJSON\x18\x10 \x01(\tH\rR\x0fannotationsJSON\x88\x01\x01\x12'\n" +
	"\fgeneratorURL\x18\x11 \x01(\tH\x0eR\fgeneratorURL\x88\x01\x01\x12'\n" +
	"\frawEventJSON\x18\x12 \x01(\tH\x0fR\frawEventJSON\x88\x01\x01B\x11\n" +
	"\x0f_idempotencyKeyB\x0e\n" +
	"\f_fingerprintB\v\n" +
	"\t_dedupKeyB\t\n" +
	"\a_sourceB\f\n" +
	"\n" +
	"_alertNameB\n" +
	"\n" +
	"\b_serviceB\n" +
	"\n" +
	"\b_clusterB\f\n" +
	"\n" +
	"_namespaceB\v\n" +
	"\t_workloadB\v\n" +
	"\t_startsAtB\t\n" +
	"\a_endsAtB\r\n" +
	"\v_lastSeenAtB\r\n" +
	"\v_labelsJSONB\x12\n" +
	"\x10_annotationsJSONB\x0f\n" +
	"\r_generatorURLB\x0f\n" +
	"\r_rawEventJSON\"\xa9\x02\n" +
	"\x18IngestAlertEventResponse\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12#\n" +
	"\n" +
	"incidentID\x18\x02 \x01(\tH\x00R\n" +
	"incidentID\x88\x01\x01\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06reused\x18\x05 \x01(\bR\x06reused\x12 \n" +
	"\vmergeResult\x18\x06 \x01(\tR\vmergeResult\x12\x1a\n" +
	"\bsilenced\x18\a \x01(\bR\bsilenced\x12!\n" +
	"\tsilenceID\x18\b \x01(\tH\x01R\tsilenceID\x88\x01\x01B\r\n" +
	"\v_incidentIDB\f\n" +
	"\n" +
	"_silenceID\"\x8d\x04\n" +
	"\x1dListCurrentAlertEventsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1f\n" +
	"\bseverity\x18\x03 \x01(\tH\x00R\bseverity\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\x04 \x01(\tH\x01R\aservice\x88\x01\x01\x12\x1d\n" +
	"\acluster\x18\x05 \x01(\tH\x02R\acluster\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x06 \x01(\tH\x03R\tnamespace\x88\x01\x01\x12%\n" +
	"\vfingerprint\x18\a \x01(\tH\x04R\vfingerprint\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\b \x01(\tH\x05R\x06status\x88\x01\x01\x12E\n" +
	"\rlastSeenStart\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x06R\rlastSeenStart\x88\x01\x01\x12A\n" +
	"\vlastSeenEnd\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\aR\vlastSeenEnd\x88\x01\x01B\v\n" +
	"\t_severityB\n" +
	"\n" +
	"\b_serviceB\n" +
	"\n" +
	"\b_clusterB\f\n" +
	"\n" +
	"_namespaceB\x0e\n" +
	"\f_fingerprintB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_lastSeenStartB\x0e\n" +
	"\f_lastSeenEnd\"r\n" +
	"\x1eListCurrentAlertEventsResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x120\n" +
	"\x06events\x18\x02 \x03(\v2\x18.apiserver.v1.AlertEventR\x06events\"\xc1\x04\n" +
	"\x1dListHistoryAlertEventsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1f\n" +
	"\bseverity\x18\x03 \x01(\tH\x00R\bseverity\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\x04 \x01(\tH\x01R\aservice\x88\x01\x01\x12\x1d\n" +
	"\acluster\x18\x05 \x01(\tH\x02R\acluster\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x06 \x01(\tH\x03R\tnamespace\x88\x01\x01\x12%\n" +
	"\vfingerprint\x18\a \x01(\tH\x04R\vfingerprint\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\b \x01(\tH\x05R\x06status\x88\x01\x01\x12#\n" +
	"\n" +
	"incidentID\x18\t \x01(\tH\x06R\n" +
	"incidentID\x88\x01\x01\x12E\n" +
	"\rlastSeenStart\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\aR\rlastSeenStart\x88\x01\x01\x12A\n" +
	"\vlastSeenEnd\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\bR\vlastSeenEnd\x88\x01\x01B\v\n" +
	"\t_severityB\n" +
	"\n" +
	"\b_serviceB\n" +
	"\n" +
	"\b_clusterB\f\n" +
	"\n" +
	"_namespaceB\x0e\n" +
	"\f_fingerprintB\t\n" +
	"\a_statusB\r\n" +
	"\v_incidentIDB\x10\n" +
	"\x0e_lastSeenStartB\x0e\n" +
	"\f_lastSeenEnd\"r\n" +
	"\x1eListHistoryAlertEventsResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x120\n" +
	"\x06events\x18\x02 \x03(\v2\x18.apiserver.v1.AlertEventR\x06events\"[\n" +
	"\x14AckAlertEventRequest\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12\x1d\n" +
	"\aackedBy\x18\x02 \x01(\tH\x00R\aackedBy\x88\x01\x01B\n" +
	"\n" +
	"\b_ackedBy\"\xb5\x01\n" +
	"\x15AckAlertEventResponse\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12#\n" +
	"\n" +
	"incidentID\x18\x02 \x01(\tH\x00R\n" +
	"incidentID\x88\x01\x01\x124\n" +
	"\aackedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aackedAt\x12\x18\n" +
	"\aackedBy\x18\x04 \x01(\tR\aackedByB\r\n" +
	"\v_incidentIDB*Z(zk8s.com/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_alert_event_proto_rawDescOnce sync.Once
	file_apiserver_v1_alert_event_proto_rawDescData []byte
)

func file_apiserver_v1_alert_event_proto_rawDescGZIP() []byte {
	file_apiserver_v1_alert_event_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_alert_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_alert_event_proto_rawDesc), len(file_apiserver_v1_alert_event_proto_rawDesc)))
	})
	return file_apiserver_v1_alert_event_proto_rawDescData
}

var file_apiserver_v1_alert_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apiserver_v1_alert_event_proto_goTypes = []any{
	(*AlertEvent)(nil),                     // 0: apiserver.v1.AlertEvent
	(*IngestAlertEventRequest)(nil),        // 1: apiserver.v1.IngestAlertEventRequest
	(*IngestAlertEventResponse)(nil),       // 2: apiserver.v1.IngestAlertEventResponse
	(*ListCurrentAlertEventsRequest)(nil),  // 3: apiserver.v1.ListCurrentAlertEventsRequest
	(*ListCurrentAlertEventsResponse)(nil), // 4: apiserver.v1.ListCurrentAlertEventsResponse
	(*ListHistoryAlertEventsRequest)(nil),  // 5: apiserver.v1.ListHistoryAlertEventsRequest
	(*ListHistoryAlertEventsResponse)(nil), // 6: apiserver.v1.ListHistoryAlertEventsResponse
	(*AckAlertEventRequest)(nil),           // 7: apiserver.v1.AckAlertEventRequest
	(*AckAlertEventResponse)(nil),          // 8: apiserver.v1.AckAlertEventResponse
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_apiserver_v1_alert_event_proto_depIdxs = []int32{
	9,  // 0: apiserver.v1.AlertEvent.startsAt:type_name -> google.protobuf.Timestamp
	9,  // 1: apiserver.v1.AlertEvent.endsAt:type_name -> google.protobuf.Timestamp
	9,  // 2: apiserver.v1.AlertEvent.lastSeenAt:type_name -> google.protobuf.Timestamp
	9,  // 3: apiserver.v1.AlertEvent.ackedAt:type_name -> google.protobuf.Timestamp
	9,  // 4: apiserver.v1.AlertEvent.createdAt:type_name -> google.protobuf.Timestamp
	9,  // 5: apiserver.v1.AlertEvent.updatedAt:type_name -> google.protobuf.Timestamp
	9,  // 6: apiserver.v1.IngestAlertEventRequest.startsAt:type_name -> google.protobuf.Timestamp
	9,  // 7: apiserver.v1.IngestAlertEventRequest.endsAt:type_name -> google.protobuf.Timestamp
	9,  // 8: apiserver.v1.IngestAlertEventRequest.lastSeenAt:type_name -> google.protobuf.Timestamp
	9,  // 9: apiserver.v1.ListCurrentAlertEventsRequest.lastSeenStart:type_name -> google.protobuf.Timestamp
	9,  // 10: apiserver.v1.ListCurrentAlertEventsRequest.lastSeenEnd:type_name -> google.protobuf.Timestamp
	0,  // 11: apiserver.v1.ListCurrentAlertEventsResponse.events:type_name -> apiserver.v1.AlertEvent
	9,  // 12: apiserver.v1.ListHistoryAlertEventsRequest.lastSeenStart:type_name -> google.protobuf.Timestamp
	9,  // 13: apiserver.v1.ListHistoryAlertEventsRequest.lastSeenEnd:type_name -> google.protobuf.Timestamp
	0,  // 14: apiserver.v1.ListHistoryAlertEventsResponse.events:type_name -> apiserver.v1.AlertEvent
	9,  // 15: apiserver.v1.AckAlertEventResponse.ackedAt:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_apiserver_v1_alert_event_proto_init() }
func file_apiserver_v1_alert_event_proto_init() {
	if File_apiserver_v1_alert_event_proto != nil {
		return
	}
	file_apiserver_v1_alert_event_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_alert_event_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_alert_event_proto_msgTypes[2].OneofWrappers = []any{}
	file_apiserver_v1_alert_event_proto_msgTypes[3].OneofWrappers = []any{}
	file_apiserver_v1_alert_event_proto_msgTypes[5].OneofWrappers = []any{}
	file_apiserver_v1_alert_event_proto_msgTypes[7].OneofWrappers = []any{}
	file_apiserver_v1_alert_event_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_alert_event_proto_rawDesc), len(file_apiserver_v1_alert_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_alert_event_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_alert_event_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_alert_event_proto_msgTypes,
	}.Build()
	File_apiserver_v1_alert_event_proto = out.File
	file_apiserver_v1_alert_event_proto_goTypes = nil
	file_apiserver_v1_alert_event_proto_depIdxs = nil
}
