// Datasource API messages for evidence query backends.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apiserver/v1/datasource.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Datasource represents a query backend (prometheus/loki/elasticsearch/tempo).
type Datasource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// datasourceID is the business resource ID (e.g. ds-xxxxxx).
	DatasourceID string `protobuf:"bytes,1,opt,name=datasourceID,proto3" json:"datasourceID,omitempty"`
	// type is datasource type: prometheus|loki|elasticsearch|tempo.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// name is display name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// baseURL is endpoint root.
	BaseURL string `protobuf:"bytes,4,opt,name=baseURL,proto3" json:"baseURL,omitempty"`
	// authType is auth strategy: none|basic|bearer|api_key.
	AuthType string `protobuf:"bytes,5,opt,name=authType,proto3" json:"authType,omitempty"`
	// authSecretRef stores secret reference only (not plain secret).
	AuthSecretRef *string `protobuf:"bytes,6,opt,name=authSecretRef,proto3,oneof" json:"authSecretRef,omitempty"`
	// timeoutMs controls per-request timeout to the upstream datasource.
	TimeoutMs int64 `protobuf:"varint,7,opt,name=timeoutMs,proto3" json:"timeoutMs,omitempty"`
	// isEnabled controls whether this datasource can be used.
	IsEnabled bool `protobuf:"varint,8,opt,name=isEnabled,proto3" json:"isEnabled,omitempty"`
	// labelsJSON helps routing by cluster/env/tenant.
	LabelsJSON *string `protobuf:"bytes,9,opt,name=labelsJSON,proto3,oneof" json:"labelsJSON,omitempty"`
	// defaultHeadersJSON stores optional default headers.
	DefaultHeadersJSON *string `protobuf:"bytes,10,opt,name=defaultHeadersJSON,proto3,oneof" json:"defaultHeadersJSON,omitempty"`
	// tlsConfigJSON stores optional TLS config.
	TlsConfigJSON *string `protobuf:"bytes,11,opt,name=tlsConfigJSON,proto3,oneof" json:"tlsConfigJSON,omitempty"`
	// createdAt is create timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt is update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Datasource) Reset() {
	*x = Datasource{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datasource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datasource) ProtoMessage() {}

func (x *Datasource) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datasource.ProtoReflect.Descriptor instead.
func (*Datasource) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *Datasource) GetDatasourceID() string {
	if x != nil {
		return x.DatasourceID
	}
	return ""
}

func (x *Datasource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Datasource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Datasource) GetBaseURL() string {
	if x != nil {
		return x.BaseURL
	}
	return ""
}

func (x *Datasource) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *Datasource) GetAuthSecretRef() string {
	if x != nil && x.AuthSecretRef != nil {
		return *x.AuthSecretRef
	}
	return ""
}

func (x *Datasource) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Datasource) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *Datasource) GetLabelsJSON() string {
	if x != nil && x.LabelsJSON != nil {
		return *x.LabelsJSON
	}
	return ""
}

func (x *Datasource) GetDefaultHeadersJSON() string {
	if x != nil && x.DefaultHeadersJSON != nil {
		return *x.DefaultHeadersJSON
	}
	return ""
}

func (x *Datasource) GetTlsConfigJSON() string {
	if x != nil && x.TlsConfigJSON != nil {
		return *x.TlsConfigJSON
	}
	return ""
}

func (x *Datasource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Datasource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateDatasourceRequest creates a datasource.
type CreateDatasourceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BaseURL            string                 `protobuf:"bytes,3,opt,name=baseURL,proto3" json:"baseURL,omitempty"`
	AuthType           *string                `protobuf:"bytes,4,opt,name=authType,proto3,oneof" json:"authType,omitempty"`
	AuthSecretRef      *string                `protobuf:"bytes,5,opt,name=authSecretRef,proto3,oneof" json:"authSecretRef,omitempty"`
	TimeoutMs          *int64                 `protobuf:"varint,6,opt,name=timeoutMs,proto3,oneof" json:"timeoutMs,omitempty"`
	IsEnabled          *bool                  `protobuf:"varint,7,opt,name=isEnabled,proto3,oneof" json:"isEnabled,omitempty"`
	LabelsJSON         *string                `protobuf:"bytes,8,opt,name=labelsJSON,proto3,oneof" json:"labelsJSON,omitempty"`
	DefaultHeadersJSON *string                `protobuf:"bytes,9,opt,name=defaultHeadersJSON,proto3,oneof" json:"defaultHeadersJSON,omitempty"`
	TlsConfigJSON      *string                `protobuf:"bytes,10,opt,name=tlsConfigJSON,proto3,oneof" json:"tlsConfigJSON,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateDatasourceRequest) Reset() {
	*x = CreateDatasourceRequest{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatasourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatasourceRequest) ProtoMessage() {}

func (x *CreateDatasourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatasourceRequest.ProtoReflect.Descriptor instead.
func (*CreateDatasourceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDatasourceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateDatasourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatasourceRequest) GetBaseURL() string {
	if x != nil {
		return x.BaseURL
	}
	return ""
}

func (x *CreateDatasourceRequest) GetAuthType() string {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return ""
}

func (x *CreateDatasourceRequest) GetAuthSecretRef() string {
	if x != nil && x.AuthSecretRef != nil {
		return *x.AuthSecretRef
	}
	return ""
}

func (x *CreateDatasourceRequest) GetTimeoutMs() int64 {
	if x != nil && x.TimeoutMs != nil {
		return *x.TimeoutMs
	}
	return 0
}

func (x *CreateDatasourceRequest) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *CreateDatasourceRequest) GetLabelsJSON() string {
	if x != nil && x.LabelsJSON != nil {
		return *x.LabelsJSON
	}
	return ""
}

func (x *CreateDatasourceRequest) GetDefaultHeadersJSON() string {
	if x != nil && x.DefaultHeadersJSON != nil {
		return *x.DefaultHeadersJSON
	}
	return ""
}

func (x *CreateDatasourceRequest) GetTlsConfigJSON() string {
	if x != nil && x.TlsConfigJSON != nil {
		return *x.TlsConfigJSON
	}
	return ""
}

// CreateDatasourceResponse returns created datasource id.
type CreateDatasourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasourceID  string                 `protobuf:"bytes,1,opt,name=datasourceID,proto3" json:"datasourceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatasourceResponse) Reset() {
	*x = CreateDatasourceResponse{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatasourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatasourceResponse) ProtoMessage() {}

func (x *CreateDatasourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatasourceResponse.ProtoReflect.Descriptor instead.
func (*CreateDatasourceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDatasourceResponse) GetDatasourceID() string {
	if x != nil {
		return x.DatasourceID
	}
	return ""
}

// UpdateDatasourceRequest patches a datasource with field whitelist.
type UpdateDatasourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// datasourceID identifies datasource in URI.
	// @gotags: uri:"datasourceID"
	DatasourceID       string  `protobuf:"bytes,1,opt,name=datasourceID,proto3" json:"datasourceID,omitempty" uri:"datasourceID"`
	Name               *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BaseURL            *string `protobuf:"bytes,3,opt,name=baseURL,proto3,oneof" json:"baseURL,omitempty"`
	AuthType           *string `protobuf:"bytes,4,opt,name=authType,proto3,oneof" json:"authType,omitempty"`
	AuthSecretRef      *string `protobuf:"bytes,5,opt,name=authSecretRef,proto3,oneof" json:"authSecretRef,omitempty"`
	TimeoutMs          *int64  `protobuf:"varint,6,opt,name=timeoutMs,proto3,oneof" json:"timeoutMs,omitempty"`
	IsEnabled          *bool   `protobuf:"varint,7,opt,name=isEnabled,proto3,oneof" json:"isEnabled,omitempty"`
	LabelsJSON         *string `protobuf:"bytes,8,opt,name=labelsJSON,proto3,oneof" json:"labelsJSON,omitempty"`
	DefaultHeadersJSON *string `protobuf:"bytes,9,opt,name=defaultHeadersJSON,proto3,oneof" json:"defaultHeadersJSON,omitempty"`
	TlsConfigJSON      *string `protobuf:"bytes,10,opt,name=tlsConfigJSON,proto3,oneof" json:"tlsConfigJSON,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateDatasourceRequest) Reset() {
	*x = UpdateDatasourceRequest{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatasourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatasourceRequest) ProtoMessage() {}

func (x *UpdateDatasourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatasourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatasourceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDatasourceRequest) GetDatasourceID() string {
	if x != nil {
		return x.DatasourceID
	}
	return ""
}

func (x *UpdateDatasourceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateDatasourceRequest) GetBaseURL() string {
	if x != nil && x.BaseURL != nil {
		return *x.BaseURL
	}
	return ""
}

func (x *UpdateDatasourceRequest) GetAuthType() string {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return ""
}

func (x *UpdateDatasourceRequest) GetAuthSecretRef() string {
	if x != nil && x.AuthSecretRef != nil {
		return *x.AuthSecretRef
	}
	return ""
}

func (x *UpdateDatasourceRequest) GetTimeoutMs() int64 {
	if x != nil && x.TimeoutMs != nil {
		return *x.TimeoutMs
	}
	return 0
}

func (x *UpdateDatasourceRequest) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *UpdateDatasourceRequest) GetLabelsJSON() string {
	if x != nil && x.LabelsJSON != nil {
		return *x.LabelsJSON
	}
	return ""
}

func (x *UpdateDatasourceRequest) GetDefaultHeadersJSON() string {
	if x != nil && x.DefaultHeadersJSON != nil {
		return *x.DefaultHeadersJSON
	}
	return ""
}

func (x *UpdateDatasourceRequest) GetTlsConfigJSON() string {
	if x != nil && x.TlsConfigJSON != nil {
		return *x.TlsConfigJSON
	}
	return ""
}

// UpdateDatasourceResponse indicates update success.
type UpdateDatasourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDatasourceResponse) Reset() {
	*x = UpdateDatasourceResponse{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDatasourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatasourceResponse) ProtoMessage() {}

func (x *UpdateDatasourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatasourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatasourceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{4}
}

// DeleteDatasourceRequest soft-deletes(disables) datasource.
type DeleteDatasourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// datasourceID identifies datasource in URI.
	// @gotags: uri:"datasourceID"
	DatasourceID  string `protobuf:"bytes,1,opt,name=datasourceID,proto3" json:"datasourceID,omitempty" uri:"datasourceID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatasourceRequest) Reset() {
	*x = DeleteDatasourceRequest{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasourceRequest) ProtoMessage() {}

func (x *DeleteDatasourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatasourceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDatasourceRequest) GetDatasourceID() string {
	if x != nil {
		return x.DatasourceID
	}
	return ""
}

// DeleteDatasourceResponse indicates delete success.
type DeleteDatasourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDatasourceResponse) Reset() {
	*x = DeleteDatasourceResponse{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDatasourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasourceResponse) ProtoMessage() {}

func (x *DeleteDatasourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatasourceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{6}
}

// GetDatasourceRequest fetches one datasource.
type GetDatasourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// datasourceID identifies datasource in URI.
	// @gotags: uri:"datasourceID"
	DatasourceID  string `protobuf:"bytes,1,opt,name=datasourceID,proto3" json:"datasourceID,omitempty" uri:"datasourceID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasourceRequest) Reset() {
	*x = GetDatasourceRequest{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasourceRequest) ProtoMessage() {}

func (x *GetDatasourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasourceRequest.ProtoReflect.Descriptor instead.
func (*GetDatasourceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{7}
}

func (x *GetDatasourceRequest) GetDatasourceID() string {
	if x != nil {
		return x.DatasourceID
	}
	return ""
}

// GetDatasourceResponse contains one datasource.
type GetDatasourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasource    *Datasource            `protobuf:"bytes,1,opt,name=datasource,proto3" json:"datasource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasourceResponse) Reset() {
	*x = GetDatasourceResponse{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasourceResponse) ProtoMessage() {}

func (x *GetDatasourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasourceResponse.ProtoReflect.Descriptor instead.
func (*GetDatasourceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{8}
}

func (x *GetDatasourceResponse) GetDatasource() *Datasource {
	if x != nil {
		return x.Datasource
	}
	return nil
}

// ListDatasourceRequest lists datasources with paging and filters.
type ListDatasourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit for pagination.
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// filter by datasource type.
	Type *string `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// filter by enabled flag.
	IsEnabled *bool `protobuf:"varint,4,opt,name=isEnabled,proto3,oneof" json:"isEnabled,omitempty"`
	// fuzzy filter by datasource name.
	Name          *string `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasourceRequest) Reset() {
	*x = ListDatasourceRequest{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasourceRequest) ProtoMessage() {}

func (x *ListDatasourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasourceRequest.ProtoReflect.Descriptor instead.
func (*ListDatasourceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{9}
}

func (x *ListDatasourceRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDatasourceRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDatasourceRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListDatasourceRequest) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *ListDatasourceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// ListDatasourceResponse lists datasources.
type ListDatasourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Datasources   []*Datasource          `protobuf:"bytes,2,rep,name=datasources,proto3" json:"datasources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasourceResponse) Reset() {
	*x = ListDatasourceResponse{}
	mi := &file_apiserver_v1_datasource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasourceResponse) ProtoMessage() {}

func (x *ListDatasourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_datasource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasourceResponse.ProtoReflect.Descriptor instead.
func (*ListDatasourceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_datasource_proto_rawDescGZIP(), []int{10}
}

func (x *ListDatasourceResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDatasourceResponse) GetDatasources() []*Datasource {
	if x != nil {
		return x.Datasources
	}
	return nil
}

var File_apiserver_v1_datasource_proto protoreflect.FileDescriptor

const file_apiserver_v1_datasource_proto_rawDesc = "" +
	"\n" +
	"\x1dapiserver/v1/datasource.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x04\n" +
	"\n" +
	"Datasource\x12\"\n" +
	"\fdatasourceID\x18\x01 \x01(\tR\fdatasourceID\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\abaseURL\x18\x04 \x01(\tR\abaseURL\x12\x1a\n" +
	"\bauthType\x18\x05 \x01(\tR\bauthType\x12)\n" +
	"\rauthSecretRef\x18\x06 \x01(\tH\x00R\rauthSecretRef\x88\x01\x01\x12\x1c\n" +
	"\ttimeoutMs\x18\a \x01(\x03R\ttimeoutMs\x12\x1c\n" +
	"\tisEnabled\x18\b \x01(\bR\tisEnabled\x12#\n" +
	"\n" +
	"labelsJSON\x18\t \x01(\tH\x01R\n" +
	"labelsJSON\x88\x01\x01\x123\n" +
	"\x12defaultHeadersJSON\x18\n" +
	" \x01(\tH\x02R\x12defaultHeadersJSON\x88\x01\x01\x12)\n" +
	"\rtlsConfigJSON\x18\v \x01(\tH\x03R\rtlsConfigJSON\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x10\n" +
	"\x0e_authSecretRefB\r\n" +
	"\v_labelsJSONB\x15\n" +
	"\x13_defaultHeadersJSONB\x10\n" +
	"\x0e_tlsConfigJSON\"\xe5\x03\n" +
	"\x17CreateDatasourceRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\abaseURL\x18\x03 \x01(\tR\abaseURL\x12\x1f\n" +
	"\bauthType\x18\x04 \x01(\tH\x00R\bauthType\x88\x01\x01\x12)\n" +
	"\rauthSecretRef\x18\x05 \x01(\tH\x01R\rauthSecretRef\x88\x01\x01\x12!\n" +
	"\ttimeoutMs\x18\x06 \x01(\x03H\x02R\ttimeoutMs\x88\x01\x01\x12!\n" +
	"\tisEnabled\x18\a \x01(\bH\x03R\tisEnabled\x88\x01\x01\x12#\n" +
	"\n" +
	"labelsJSON\x18\b \x01(\tH\x04R\n" +
	"labelsJSON\x88\x01\x01\x123\n" +
	"\x12defaultHeadersJSON\x18\t \x01(\tH\x05R\x12defaultHeadersJSON\x88\x01\x01\x12)\n" +
	"\rtlsConfigJSON\x18\n" +
	" \x01(\tH\x06R\rtlsConfigJSON\x88\x01\x01B\v\n" +
	"\t_authTypeB\x10\n" +
	"\x0e_authSecretRefB\f\n" +
	"\n" +
	"_timeoutMsB\f\n" +
	"\n" +
	"_isEnabledB\r\n" +
	"\v_labelsJSONB\x15\n" +
	"\x13_defaultHeadersJSONB\x10\n" +
	"\x0e_tlsConfigJSON\">\n" +
	"\x18CreateDatasourceResponse\x12\"\n" +
	"\fdatasourceID\x18\x01 \x01(\tR\fdatasourceID\"\x94\x04\n" +
	"\x17UpdateDatasourceRequest\x12\"\n" +
	"\fdatasourceID\x18\x01 \x01(\tR\fdatasourceID\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\abaseURL\x18\x03 \x01(\tH\x01R\abaseURL\x88\x01\x01\x12\x1f\n" +
	"\bauthType\x18\x04 \x01(\tH\x02R\bauthType\x88\x01\x01\x12)\n" +
	"\rauthSecretRef\x18\x05 \x01(\tH\x03R\rauthSecretRef\x88\x01\x01\x12!\n" +
	"\ttimeoutMs\x18\x06 \x01(\x03H\x04R\ttimeoutMs\x88\x01\x01\x12!\n" +
	"\tisEnabled\x18\a \x01(\bH\x05R\tisEnabled\x88\x01\x01\x12#\n" +
	"\n" +
	"labelsJSON\x18\b \x01(\tH\x06R\n" +
	"labelsJSON\x88\x01\x01\x123\n" +
	"\x12defaultHeadersJSON\x18\t \x01(\tH\aR\x12defaultHeadersJSON\x88\x01\x01\x12)\n" +
	"\rtlsConfigJSON\x18\n" +
	" \x01(\tH\bR\rtlsConfigJSON\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_baseURLB\v\n" +
	"\t_authTypeB\x10\n" +
	"\x0e_authSecretRefB\f\n" +
	"\n" +
	"_timeoutMsB\f\n" +
	"\n" +
	"_isEnabledB\r\n" +
	"\v_labelsJSONB\x15\n" +
	"\x13_defaultHeadersJSONB\x10\n" +
	"\x0e_tlsConfigJSON\"\x1a\n" +
	"\x18UpdateDatasourceResponse\"=\n" +
	"\x17DeleteDatasourceRequest\x12\"\n" +
	"\fdatasourceID\x18\x01 \x01(\tR\fdatasourceID\"\x1a\n" +
	"\x18DeleteDatasourceResponse\":\n" +
	"\x14GetDatasourceRequest\x12\"\n" +
	"\fdatasourceID\x18\x01 \x01(\tR\fdatasourceID\"Q\n" +
	"\x15GetDatasourceResponse\x128\n" +
	"\n" +
	"datasource\x18\x01 \x01(\v2\x18.apiserver.v1.DatasourceR\n" +
	"datasource\"\xba\x01\n" +
	"\x15ListDatasourceRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x00R\x04type\x88\x01\x01\x12!\n" +
	"\tisEnabled\x18\x04 \x01(\bH\x01R\tisEnabled\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x02R\x04name\x88\x01\x01B\a\n" +
	"\x05_typeB\f\n" +
	"\n" +
	"_isEnabledB\a\n" +
	"\x05_name\"t\n" +
	"\x16ListDatasourceResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12:\n" +
	"\vdatasources\x18\x02 \x03(\v2\x18.apiserver.v1.DatasourceR\vdatasourcesB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_datasource_proto_rawDescOnce sync.Once
	file_apiserver_v1_datasource_proto_rawDescData []byte
)

func file_apiserver_v1_datasource_proto_rawDescGZIP() []byte {
	file_apiserver_v1_datasource_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_datasource_proto_rawDesc), len(file_apiserver_v1_datasource_proto_rawDesc)))
	})
	return file_apiserver_v1_datasource_proto_rawDescData
}

var file_apiserver_v1_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_datasource_proto_goTypes = []any{
	(*Datasource)(nil),               // 0: apiserver.v1.Datasource
	(*CreateDatasourceRequest)(nil),  // 1: apiserver.v1.CreateDatasourceRequest
	(*CreateDatasourceResponse)(nil), // 2: apiserver.v1.CreateDatasourceResponse
	(*UpdateDatasourceRequest)(nil),  // 3: apiserver.v1.UpdateDatasourceRequest
	(*UpdateDatasourceResponse)(nil), // 4: apiserver.v1.UpdateDatasourceResponse
	(*DeleteDatasourceRequest)(nil),  // 5: apiserver.v1.DeleteDatasourceRequest
	(*DeleteDatasourceResponse)(nil), // 6: apiserver.v1.DeleteDatasourceResponse
	(*GetDatasourceRequest)(nil),     // 7: apiserver.v1.GetDatasourceRequest
	(*GetDatasourceResponse)(nil),    // 8: apiserver.v1.GetDatasourceResponse
	(*ListDatasourceRequest)(nil),    // 9: apiserver.v1.ListDatasourceRequest
	(*ListDatasourceResponse)(nil),   // 10: apiserver.v1.ListDatasourceResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_apiserver_v1_datasource_proto_depIdxs = []int32{
	11, // 0: apiserver.v1.Datasource.createdAt:type_name -> google.protobuf.Timestamp
	11, // 1: apiserver.v1.Datasource.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: apiserver.v1.GetDatasourceResponse.datasource:type_name -> apiserver.v1.Datasource
	0,  // 3: apiserver.v1.ListDatasourceResponse.datasources:type_name -> apiserver.v1.Datasource
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_apiserver_v1_datasource_proto_init() }
func file_apiserver_v1_datasource_proto_init() {
	if File_apiserver_v1_datasource_proto != nil {
		return
	}
	file_apiserver_v1_datasource_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_datasource_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_datasource_proto_msgTypes[3].OneofWrappers = []any{}
	file_apiserver_v1_datasource_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_datasource_proto_rawDesc), len(file_apiserver_v1_datasource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_datasource_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_datasource_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_datasource_proto_msgTypes,
	}.Build()
	File_apiserver_v1_datasource_proto = out.File
	file_apiserver_v1_datasource_proto_goTypes = nil
	file_apiserver_v1_datasource_proto_depIdxs = nil
}
