// Incident API 定义：事件单的请求和响应消息

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Incident) Default() {
}

func (x *CreateIncidentRequest) Default() {
}

func (x *CreateIncidentResponse) Default() {
}

func (x *UpdateIncidentRequest) Default() {
}

func (x *UpdateIncidentResponse) Default() {
}

func (x *DeleteIncidentRequest) Default() {
}

func (x *DeleteIncidentResponse) Default() {
}

func (x *GetIncidentRequest) Default() {
}

func (x *GetIncidentResponse) Default() {
}

func (x *ListIncidentRequest) Default() {
}

func (x *ListIncidentResponse) Default() {
}
