// Incident API 定义：事件单的请求和响应消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apiserver/v1/incident.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Incident 表示事件单（告警聚合后的事件元数据 + 诊断/处置闭环索引）
type Incident struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incidentID 表示事件单业务 ID（如 incident-xxxxxx）
	IncidentID string `protobuf:"bytes,1,opt,name=incidentID,proto3" json:"incidentID,omitempty"`
	// tenantID 表示租户/业务线标识
	TenantID string `protobuf:"bytes,2,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	// cluster 表示集群标识（如 prod-cn1 / staging）
	Cluster string `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// environment 表示环境（prod/staging/dev）
	Environment string `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	// namespace 表示 K8s 命名空间
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// workloadKind 表示工作负载类型（Deployment/StatefulSet/...）
	WorkloadKind string `protobuf:"bytes,6,opt,name=workloadKind,proto3" json:"workloadKind,omitempty"`
	// workloadName 表示工作负载名称
	WorkloadName string `protobuf:"bytes,7,opt,name=workloadName,proto3" json:"workloadName,omitempty"`
	// service 表示服务名（微服务维度）
	Service string `protobuf:"bytes,8,opt,name=service,proto3" json:"service,omitempty"`
	// severity 表示严重级别（P0/P1/P2 或 critical/warn/info）
	Severity string `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	// status 表示事件状态（open/ack/mitigating/closed/silenced 等）
	Status string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// source 表示事件来源（alertmanager/grafana/manual/api 等）
	Source *string `protobuf:"bytes,11,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// alertName 表示告警名称
	AlertName *string `protobuf:"bytes,12,opt,name=alertName,proto3,oneof" json:"alertName,omitempty"`
	// fingerprint 表示告警聚合指纹（用于合并同类告警）
	Fingerprint *string `protobuf:"bytes,13,opt,name=fingerprint,proto3,oneof" json:"fingerprint,omitempty"`
	// ruleID 表示告警规则 ID
	RuleID *string `protobuf:"bytes,14,opt,name=ruleID,proto3,oneof" json:"ruleID,omitempty"`
	// traceID 表示关联 TraceID
	TraceID *string `protobuf:"bytes,15,opt,name=traceID,proto3,oneof" json:"traceID,omitempty"`
	// logTraceKey 表示日志检索关键字/trace key
	LogTraceKey *string `protobuf:"bytes,16,opt,name=logTraceKey,proto3,oneof" json:"logTraceKey,omitempty"`
	// changeID 表示关联变更 ID（发布单/工单/流水线 run id）
	ChangeID *string `protobuf:"bytes,17,opt,name=changeID,proto3,oneof" json:"changeID,omitempty"`
	// startAt 表示事件开始时间（首次触发/窗口开始）
	StartAt *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=startAt,proto3,oneof" json:"startAt,omitempty"`
	// endAt 表示事件结束时间（恢复/关闭）
	EndAt *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=endAt,proto3,oneof" json:"endAt,omitempty"`
	// createdAt 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetIncidentID() string {
	if x != nil {
		return x.IncidentID
	}
	return ""
}

func (x *Incident) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *Incident) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Incident) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Incident) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Incident) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *Incident) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *Incident) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Incident) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Incident) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Incident) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Incident) GetAlertName() string {
	if x != nil && x.AlertName != nil {
		return *x.AlertName
	}
	return ""
}

func (x *Incident) GetFingerprint() string {
	if x != nil && x.Fingerprint != nil {
		return *x.Fingerprint
	}
	return ""
}

func (x *Incident) GetRuleID() string {
	if x != nil && x.RuleID != nil {
		return *x.RuleID
	}
	return ""
}

func (x *Incident) GetTraceID() string {
	if x != nil && x.TraceID != nil {
		return *x.TraceID
	}
	return ""
}

func (x *Incident) GetLogTraceKey() string {
	if x != nil && x.LogTraceKey != nil {
		return *x.LogTraceKey
	}
	return ""
}

func (x *Incident) GetChangeID() string {
	if x != nil && x.ChangeID != nil {
		return *x.ChangeID
	}
	return ""
}

func (x *Incident) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Incident) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Incident) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Incident) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateIncidentRequest 表示创建事件单请求
type CreateIncidentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenantID 表示租户/业务线标识（可选，默认 default）
	TenantID *string `protobuf:"bytes,1,opt,name=tenantID,proto3,oneof" json:"tenantID,omitempty"`
	// cluster 表示集群标识（可选，默认 default）
	Cluster *string `protobuf:"bytes,2,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	// environment 表示环境（可选，默认 prod）
	Environment *string `protobuf:"bytes,3,opt,name=environment,proto3,oneof" json:"environment,omitempty"`
	// namespace 表示 K8s 命名空间
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// workloadKind 表示工作负载类型
	WorkloadKind string `protobuf:"bytes,5,opt,name=workloadKind,proto3" json:"workloadKind,omitempty"`
	// workloadName 表示工作负载名称
	WorkloadName string `protobuf:"bytes,6,opt,name=workloadName,proto3" json:"workloadName,omitempty"`
	// service 表示服务名
	Service string `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	// severity 表示严重级别
	Severity string `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"`
	// source 表示事件来源（可选）
	Source *string `protobuf:"bytes,9,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// alertName 表示告警名称（可选）
	AlertName *string `protobuf:"bytes,10,opt,name=alertName,proto3,oneof" json:"alertName,omitempty"`
	// fingerprint 表示告警聚合指纹（可选）
	Fingerprint *string `protobuf:"bytes,11,opt,name=fingerprint,proto3,oneof" json:"fingerprint,omitempty"`
	// ruleID 表示告警规则 ID（可选）
	RuleID *string `protobuf:"bytes,12,opt,name=ruleID,proto3,oneof" json:"ruleID,omitempty"`
	// traceID 表示关联 TraceID（可选）
	TraceID *string `protobuf:"bytes,13,opt,name=traceID,proto3,oneof" json:"traceID,omitempty"`
	// logTraceKey 表示日志检索 key（可选）
	LogTraceKey *string `protobuf:"bytes,14,opt,name=logTraceKey,proto3,oneof" json:"logTraceKey,omitempty"`
	// changeID 表示关联变更 ID（可选）
	ChangeID *string `protobuf:"bytes,15,opt,name=changeID,proto3,oneof" json:"changeID,omitempty"`
	// startAt 表示事件开始时间（可选）
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=startAt,proto3,oneof" json:"startAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncidentRequest) Reset() {
	*x = CreateIncidentRequest{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentRequest) ProtoMessage() {}

func (x *CreateIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentRequest.ProtoReflect.Descriptor instead.
func (*CreateIncidentRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIncidentRequest) GetTenantID() string {
	if x != nil && x.TenantID != nil {
		return *x.TenantID
	}
	return ""
}

func (x *CreateIncidentRequest) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

func (x *CreateIncidentRequest) GetEnvironment() string {
	if x != nil && x.Environment != nil {
		return *x.Environment
	}
	return ""
}

func (x *CreateIncidentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateIncidentRequest) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *CreateIncidentRequest) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *CreateIncidentRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CreateIncidentRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CreateIncidentRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *CreateIncidentRequest) GetAlertName() string {
	if x != nil && x.AlertName != nil {
		return *x.AlertName
	}
	return ""
}

func (x *CreateIncidentRequest) GetFingerprint() string {
	if x != nil && x.Fingerprint != nil {
		return *x.Fingerprint
	}
	return ""
}

func (x *CreateIncidentRequest) GetRuleID() string {
	if x != nil && x.RuleID != nil {
		return *x.RuleID
	}
	return ""
}

func (x *CreateIncidentRequest) GetTraceID() string {
	if x != nil && x.TraceID != nil {
		return *x.TraceID
	}
	return ""
}

func (x *CreateIncidentRequest) GetLogTraceKey() string {
	if x != nil && x.LogTraceKey != nil {
		return *x.LogTraceKey
	}
	return ""
}

func (x *CreateIncidentRequest) GetChangeID() string {
	if x != nil && x.ChangeID != nil {
		return *x.ChangeID
	}
	return ""
}

func (x *CreateIncidentRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

// CreateIncidentResponse 表示创建事件单响应
type CreateIncidentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incidentID 表示创建的事件单 ID
	IncidentID    string `protobuf:"bytes,1,opt,name=incidentID,proto3" json:"incidentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncidentResponse) Reset() {
	*x = CreateIncidentResponse{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentResponse) ProtoMessage() {}

func (x *CreateIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentResponse.ProtoReflect.Descriptor instead.
func (*CreateIncidentResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIncidentResponse) GetIncidentID() string {
	if x != nil {
		return x.IncidentID
	}
	return ""
}

// UpdateIncidentRequest 表示更新事件单请求
type UpdateIncidentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incidentID 表示要更新的事件单 ID，对应 {incidentID}
	// @gotags: uri:"incidentID"
	IncidentID string `protobuf:"bytes,1,opt,name=incidentID,proto3" json:"incidentID,omitempty" uri:"incidentID"`
	// severity 表示更新后的严重级别（可选）
	Severity *string `protobuf:"bytes,2,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	// status 表示更新后的事件状态（可选）
	Status *string `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// startAt/endAt 可用于补齐窗口时间（可选）
	StartAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=startAt,proto3,oneof" json:"startAt,omitempty"`
	EndAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=endAt,proto3,oneof" json:"endAt,omitempty"`
	// 可选：关联信息更新
	TraceID       *string `protobuf:"bytes,6,opt,name=traceID,proto3,oneof" json:"traceID,omitempty"`
	LogTraceKey   *string `protobuf:"bytes,7,opt,name=logTraceKey,proto3,oneof" json:"logTraceKey,omitempty"`
	ChangeID      *string `protobuf:"bytes,8,opt,name=changeID,proto3,oneof" json:"changeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentRequest) Reset() {
	*x = UpdateIncidentRequest{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentRequest) ProtoMessage() {}

func (x *UpdateIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentRequest.ProtoReflect.Descriptor instead.
func (*UpdateIncidentRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateIncidentRequest) GetIncidentID() string {
	if x != nil {
		return x.IncidentID
	}
	return ""
}

func (x *UpdateIncidentRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *UpdateIncidentRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateIncidentRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *UpdateIncidentRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *UpdateIncidentRequest) GetTraceID() string {
	if x != nil && x.TraceID != nil {
		return *x.TraceID
	}
	return ""
}

func (x *UpdateIncidentRequest) GetLogTraceKey() string {
	if x != nil && x.LogTraceKey != nil {
		return *x.LogTraceKey
	}
	return ""
}

func (x *UpdateIncidentRequest) GetChangeID() string {
	if x != nil && x.ChangeID != nil {
		return *x.ChangeID
	}
	return ""
}

// UpdateIncidentResponse 表示更新事件单响应
type UpdateIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentResponse) Reset() {
	*x = UpdateIncidentResponse{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentResponse) ProtoMessage() {}

func (x *UpdateIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentResponse.ProtoReflect.Descriptor instead.
func (*UpdateIncidentResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{4}
}

// DeleteIncidentRequest 表示删除事件单请求
type DeleteIncidentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incidentIDs 表示要删除的事件单 ID 列表
	IncidentIDs   []string `protobuf:"bytes,1,rep,name=incidentIDs,proto3" json:"incidentIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIncidentRequest) Reset() {
	*x = DeleteIncidentRequest{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIncidentRequest) ProtoMessage() {}

func (x *DeleteIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIncidentRequest.ProtoReflect.Descriptor instead.
func (*DeleteIncidentRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteIncidentRequest) GetIncidentIDs() []string {
	if x != nil {
		return x.IncidentIDs
	}
	return nil
}

// DeleteIncidentResponse 表示删除事件单响应
type DeleteIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIncidentResponse) Reset() {
	*x = DeleteIncidentResponse{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIncidentResponse) ProtoMessage() {}

func (x *DeleteIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIncidentResponse.ProtoReflect.Descriptor instead.
func (*DeleteIncidentResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{6}
}

// GetIncidentRequest 表示获取事件单请求
type GetIncidentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incidentID 表示要获取的事件单 ID
	// @gotags: uri:"incidentID"
	IncidentID    string `protobuf:"bytes,1,opt,name=incidentID,proto3" json:"incidentID,omitempty" uri:"incidentID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentRequest) Reset() {
	*x = GetIncidentRequest{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentRequest) ProtoMessage() {}

func (x *GetIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentRequest.ProtoReflect.Descriptor instead.
func (*GetIncidentRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{7}
}

func (x *GetIncidentRequest) GetIncidentID() string {
	if x != nil {
		return x.IncidentID
	}
	return ""
}

// GetIncidentResponse 表示获取事件单响应
type GetIncidentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// incident 表示返回的事件单信息
	Incident      *Incident `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentResponse) Reset() {
	*x = GetIncidentResponse{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentResponse) ProtoMessage() {}

func (x *GetIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentResponse.ProtoReflect.Descriptor instead.
func (*GetIncidentResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{8}
}

func (x *GetIncidentResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

// ListIncidentRequest 表示获取事件单列表请求
type ListIncidentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// service 表示可选的服务过滤
	Service *string `protobuf:"bytes,3,opt,name=service,proto3,oneof" json:"service,omitempty"`
	// namespace 表示可选的命名空间过滤
	Namespace *string `protobuf:"bytes,4,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	// status 表示可选的状态过滤
	Status *string `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// severity 表示可选的级别过滤
	Severity *string `protobuf:"bytes,6,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	// createdAtStart/createdAtEnd 表示可选的创建时间范围过滤
	CreatedAtStart *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAtStart,proto3,oneof" json:"createdAtStart,omitempty"`
	CreatedAtEnd   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAtEnd,proto3,oneof" json:"createdAtEnd,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListIncidentRequest) Reset() {
	*x = ListIncidentRequest{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentRequest) ProtoMessage() {}

func (x *ListIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentRequest.ProtoReflect.Descriptor instead.
func (*ListIncidentRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{9}
}

func (x *ListIncidentRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListIncidentRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListIncidentRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *ListIncidentRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ListIncidentRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListIncidentRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ListIncidentRequest) GetCreatedAtStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtStart
	}
	return nil
}

func (x *ListIncidentRequest) GetCreatedAtEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtEnd
	}
	return nil
}

// ListIncidentResponse 表示获取事件单列表响应
type ListIncidentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_count 表示总事件单数
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// incidents 表示事件单列表
	Incidents     []*Incident `protobuf:"bytes,2,rep,name=incidents,proto3" json:"incidents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentResponse) Reset() {
	*x = ListIncidentResponse{}
	mi := &file_apiserver_v1_incident_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentResponse) ProtoMessage() {}

func (x *ListIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_incident_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentResponse.ProtoReflect.Descriptor instead.
func (*ListIncidentResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_incident_proto_rawDescGZIP(), []int{10}
}

func (x *ListIncidentResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListIncidentResponse) GetIncidents() []*Incident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

var File_apiserver_v1_incident_proto protoreflect.FileDescriptor

const file_apiserver_v1_incident_proto_rawDesc = "" +
	"\n" +
	"\x1bapiserver/v1/incident.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x06\n" +
	"\bIncident\x12\x1e\n" +
	"\n" +
	"incidentID\x18\x01 \x01(\tR\n" +
	"incidentID\x12\x1a\n" +
	"\btenantID\x18\x02 \x01(\tR\btenantID\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\"\n" +
	"\fworkloadKind\x18\x06 \x01(\tR\fworkloadKind\x12\"\n" +
	"\fworkloadName\x18\a \x01(\tR\fworkloadName\x12\x18\n" +
	"\aservice\x18\b \x01(\tR\aservice\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1b\n" +
	"\x06source\x18\v \x01(\tH\x00R\x06source\x88\x01\x01\x12!\n" +
	"\talertName\x18\f \x01(\tH\x01R\talertName\x88\x01\x01\x12%\n" +
	"\vfingerprint\x18\r \x01(\tH\x02R\vfingerprint\x88\x01\x01\x12\x1b\n" +
	"\x06ruleID\x18\x0e \x01(\tH\x03R\x06ruleID\x88\x01\x01\x12\x1d\n" +
	"\atraceID\x18\x0f \x01(\tH\x04R\atraceID\x88\x01\x01\x12%\n" +
	"\vlogTraceKey\x18\x10 \x01(\tH\x05R\vlogTraceKey\x88\x01\x01\x12\x1f\n" +
	"\bchangeID\x18\x11 \x01(\tH\x06R\bchangeID\x88\x01\x01\x129\n" +
	"\astartAt\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampH\aR\astartAt\x88\x01\x01\x125\n" +
	"\x05endAt\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampH\bR\x05endAt\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\t\n" +
	"\a_sourceB\f\n" +
	"\n" +
	"_alertNameB\x0e\n" +
	"\f_fingerprintB\t\n" +
	"\a_ruleIDB\n" +
	"\n" +
	"\b_traceIDB\x0e\n" +
	"\f_logTraceKeyB\v\n" +
	"\t_changeIDB\n" +
	"\n" +
	"\b_startAtB\b\n" +
	"\x06_endAt\"\xd2\x05\n" +
	"\x15CreateIncidentRequest\x12\x1f\n" +
	"\btenantID\x18\x01 \x01(\tH\x00R\btenantID\x88\x01\x01\x12\x1d\n" +
	"\acluster\x18\x02 \x01(\tH\x01R\acluster\x88\x01\x01\x12%\n" +
	"\venvironment\x18\x03 \x01(\tH\x02R\venvironment\x88\x01\x01\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\"\n" +
	"\fworkloadKind\x18\x05 \x01(\tR\fworkloadKind\x12\"\n" +
	"\fworkloadName\x18\x06 \x01(\tR\fworkloadName\x12\x18\n" +
	"\aservice\x18\a \x01(\tR\aservice\x12\x1a\n" +
	"\bseverity\x18\b \x01(\tR\bseverity\x12\x1b\n" +
	"\x06source\x18\t \x01(\tH\x03R\x06source\x88\x01\x01\x12!\n" +
	"\talertName\x18\n" +
	" \x01(\tH\x04R\talertName\x88\x01\x01\x12%\n" +
	"\vfingerprint\x18\v \x01(\tH\x05R\vfingerprint\x88\x01\x01\x12\x1b\n" +
	"\x06ruleID\x18\f \x01(\tH\x06R\x06ruleID\x88\x01\x01\x12\x1d\n" +
	"\atraceID\x18\r \x01(\tH\aR\atraceID\x88\x01\x01\x12%\n" +
	"\vlogTraceKey\x18\x0e \x01(\tH\bR\vlogTraceKey\x88\x01\x01\x12\x1f\n" +
	"\bchangeID\x18\x0f \x01(\tH\tR\bchangeID\x88\x01\x01\x129\n" +
	"\astartAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\n" +
	"R\astartAt\x88\x01\x01B\v\n" +
	"\t_tenantIDB\n" +
	"\n" +
	"\b_clusterB\x0e\n" +
	"\f_environmentB\t\n" +
	"\a_sourceB\f\n" +
	"\n" +
	"_alertNameB\x0e\n" +
	"\f_fingerprintB\t\n" +
	"\a_ruleIDB\n" +
	"\n" +
	"\b_traceIDB\x0e\n" +
	"\f_logTraceKeyB\v\n" +
	"\t_changeIDB\n" +
	"\n" +
	"\b_startAt\"8\n" +
	"\x16CreateIncidentResponse\x12\x1e\n" +
	"\n" +
	"incidentID\x18\x01 \x01(\tR\n" +
	"incidentID\"\xa5\x03\n" +
	"\x15UpdateIncidentRequest\x12\x1e\n" +
	"\n" +
	"incidentID\x18\x01 \x01(\tR\n" +
	"incidentID\x12\x1f\n" +
	"\bseverity\x18\x02 \x01(\tH\x00R\bseverity\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01\x129\n" +
	"\astartAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\astartAt\x88\x01\x01\x125\n" +
	"\x05endAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x05endAt\x88\x01\x01\x12\x1d\n" +
	"\atraceID\x18\x06 \x01(\tH\x04R\atraceID\x88\x01\x01\x12%\n" +
	"\vlogTraceKey\x18\a \x01(\tH\x05R\vlogTraceKey\x88\x01\x01\x12\x1f\n" +
	"\bchangeID\x18\b \x01(\tH\x06R\bchangeID\x88\x01\x01B\v\n" +
	"\t_severityB\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_startAtB\b\n" +
	"\x06_endAtB\n" +
	"\n" +
	"\b_traceIDB\x0e\n" +
	"\f_logTraceKeyB\v\n" +
	"\t_changeID\"\x18\n" +
	"\x16UpdateIncidentResponse\"9\n" +
	"\x15DeleteIncidentRequest\x12 \n" +
	"\vincidentIDs\x18\x01 \x03(\tR\vincidentIDs\"\x18\n" +
	"\x16DeleteIncidentResponse\"4\n" +
	"\x12GetIncidentRequest\x12\x1e\n" +
	"\n" +
	"incidentID\x18\x01 \x01(\tR\n" +
	"incidentID\"I\n" +
	"\x13GetIncidentResponse\x122\n" +
	"\bincident\x18\x01 \x01(\v2\x16.apiserver.v1.IncidentR\bincident\"\xa7\x03\n" +
	"\x13ListIncidentRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1d\n" +
	"\aservice\x18\x03 \x01(\tH\x00R\aservice\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x04 \x01(\tH\x01R\tnamespace\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x02R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bseverity\x18\x06 \x01(\tH\x03R\bseverity\x88\x01\x01\x12G\n" +
	"\x0ecreatedAtStart\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x0ecreatedAtStart\x88\x01\x01\x12C\n" +
	"\fcreatedAtEnd\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x05R\fcreatedAtEnd\x88\x01\x01B\n" +
	"\n" +
	"\b_serviceB\f\n" +
	"\n" +
	"_namespaceB\t\n" +
	"\a_statusB\v\n" +
	"\t_severityB\x11\n" +
	"\x0f_createdAtStartB\x0f\n" +
	"\r_createdAtEnd\"m\n" +
	"\x14ListIncidentResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x124\n" +
	"\tincidents\x18\x02 \x03(\v2\x16.apiserver.v1.IncidentR\tincidentsB*Z(zk8s.com/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_incident_proto_rawDescOnce sync.Once
	file_apiserver_v1_incident_proto_rawDescData []byte
)

func file_apiserver_v1_incident_proto_rawDescGZIP() []byte {
	file_apiserver_v1_incident_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_incident_proto_rawDesc), len(file_apiserver_v1_incident_proto_rawDesc)))
	})
	return file_apiserver_v1_incident_proto_rawDescData
}

var file_apiserver_v1_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_incident_proto_goTypes = []any{
	(*Incident)(nil),               // 0: apiserver.v1.Incident
	(*CreateIncidentRequest)(nil),  // 1: apiserver.v1.CreateIncidentRequest
	(*CreateIncidentResponse)(nil), // 2: apiserver.v1.CreateIncidentResponse
	(*UpdateIncidentRequest)(nil),  // 3: apiserver.v1.UpdateIncidentRequest
	(*UpdateIncidentResponse)(nil), // 4: apiserver.v1.UpdateIncidentResponse
	(*DeleteIncidentRequest)(nil),  // 5: apiserver.v1.DeleteIncidentRequest
	(*DeleteIncidentResponse)(nil), // 6: apiserver.v1.DeleteIncidentResponse
	(*GetIncidentRequest)(nil),     // 7: apiserver.v1.GetIncidentRequest
	(*GetIncidentResponse)(nil),    // 8: apiserver.v1.GetIncidentResponse
	(*ListIncidentRequest)(nil),    // 9: apiserver.v1.ListIncidentRequest
	(*ListIncidentResponse)(nil),   // 10: apiserver.v1.ListIncidentResponse
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
}
var file_apiserver_v1_incident_proto_depIdxs = []int32{
	11, // 0: apiserver.v1.Incident.startAt:type_name -> google.protobuf.Timestamp
	11, // 1: apiserver.v1.Incident.endAt:type_name -> google.protobuf.Timestamp
	11, // 2: apiserver.v1.Incident.createdAt:type_name -> google.protobuf.Timestamp
	11, // 3: apiserver.v1.Incident.updatedAt:type_name -> google.protobuf.Timestamp
	11, // 4: apiserver.v1.CreateIncidentRequest.startAt:type_name -> google.protobuf.Timestamp
	11, // 5: apiserver.v1.UpdateIncidentRequest.startAt:type_name -> google.protobuf.Timestamp
	11, // 6: apiserver.v1.UpdateIncidentRequest.endAt:type_name -> google.protobuf.Timestamp
	0,  // 7: apiserver.v1.GetIncidentResponse.incident:type_name -> apiserver.v1.Incident
	11, // 8: apiserver.v1.ListIncidentRequest.createdAtStart:type_name -> google.protobuf.Timestamp
	11, // 9: apiserver.v1.ListIncidentRequest.createdAtEnd:type_name -> google.protobuf.Timestamp
	0,  // 10: apiserver.v1.ListIncidentResponse.incidents:type_name -> apiserver.v1.Incident
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_apiserver_v1_incident_proto_init() }
func file_apiserver_v1_incident_proto_init() {
	if File_apiserver_v1_incident_proto != nil {
		return
	}
	file_apiserver_v1_incident_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_incident_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_incident_proto_msgTypes[3].OneofWrappers = []any{}
	file_apiserver_v1_incident_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_incident_proto_rawDesc), len(file_apiserver_v1_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_incident_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_incident_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_incident_proto_msgTypes,
	}.Build()
	File_apiserver_v1_incident_proto = out.File
	file_apiserver_v1_incident_proto_goTypes = nil
	file_apiserver_v1_incident_proto_depIdxs = nil
}
