// KB Entry API 定义：知识库条目的请求和响应消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apiserver/v1/kb_entry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KBEntry 表示知识库条目（可复用的根因知识条目）
type KBEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示数据库主键 ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// kbID 表示知识库条目业务 ID（如 kb-xxxxxx）
	KbID string `protobuf:"bytes,2,opt,name=kbID,proto3" json:"kbID,omitempty"`
	// namespace 表示 K8s 命名空间
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// service 表示服务名（微服务维度）
	Service string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	// rootCauseType 表示根因类型
	RootCauseType string `protobuf:"bytes,5,opt,name=rootCauseType,proto3" json:"rootCauseType,omitempty"`
	// rootCauseSummary 表示根因摘要（一句话结论）
	RootCauseSummary string `protobuf:"bytes,6,opt,name=rootCauseSummary,proto3" json:"rootCauseSummary,omitempty"`
	// patternsJSON 表示模式匹配规则 JSON
	PatternsJSON string `protobuf:"bytes,7,opt,name=patternsJSON,proto3" json:"patternsJSON,omitempty"`
	// patternsHash 表示模式哈希（用于去重）
	PatternsHash string `protobuf:"bytes,8,opt,name=patternsHash,proto3" json:"patternsHash,omitempty"`
	// evidenceSignatureJSON 表示证据签名 JSON（可选）
	EvidenceSignatureJSON *string `protobuf:"bytes,9,opt,name=evidenceSignatureJSON,proto3,oneof" json:"evidenceSignatureJSON,omitempty"`
	// confidence 表示置信度（0-1）
	Confidence float64 `protobuf:"fixed64,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// hitCount 表示命中次数
	HitCount int64 `protobuf:"varint,11,opt,name=hitCount,proto3" json:"hitCount,omitempty"`
	// lastHitAt 表示最后命中时间（可选）
	LastHitAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=lastHitAt,proto3,oneof" json:"lastHitAt,omitempty"`
	// createdAt 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KBEntry) Reset() {
	*x = KBEntry{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KBEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KBEntry) ProtoMessage() {}

func (x *KBEntry) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KBEntry.ProtoReflect.Descriptor instead.
func (*KBEntry) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{0}
}

func (x *KBEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KBEntry) GetKbID() string {
	if x != nil {
		return x.KbID
	}
	return ""
}

func (x *KBEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KBEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *KBEntry) GetRootCauseType() string {
	if x != nil {
		return x.RootCauseType
	}
	return ""
}

func (x *KBEntry) GetRootCauseSummary() string {
	if x != nil {
		return x.RootCauseSummary
	}
	return ""
}

func (x *KBEntry) GetPatternsJSON() string {
	if x != nil {
		return x.PatternsJSON
	}
	return ""
}

func (x *KBEntry) GetPatternsHash() string {
	if x != nil {
		return x.PatternsHash
	}
	return ""
}

func (x *KBEntry) GetEvidenceSignatureJSON() string {
	if x != nil && x.EvidenceSignatureJSON != nil {
		return *x.EvidenceSignatureJSON
	}
	return ""
}

func (x *KBEntry) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *KBEntry) GetHitCount() int64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *KBEntry) GetLastHitAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHitAt
	}
	return nil
}

func (x *KBEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KBEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateKBEntryRequest 表示创建知识库条目请求
type CreateKBEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kbID 表示知识库条目业务 ID（可选，自动生成）
	KbID *string `protobuf:"bytes,1,opt,name=kbID,proto3,oneof" json:"kbID,omitempty"`
	// namespace 表示 K8s 命名空间
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// service 表示服务名
	Service string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	// rootCauseType 表示根因类型
	RootCauseType string `protobuf:"bytes,4,opt,name=rootCauseType,proto3" json:"rootCauseType,omitempty"`
	// rootCauseSummary 表示根因摘要
	RootCauseSummary string `protobuf:"bytes,5,opt,name=rootCauseSummary,proto3" json:"rootCauseSummary,omitempty"`
	// patternsJSON 表示模式匹配规则 JSON
	PatternsJSON string `protobuf:"bytes,6,opt,name=patternsJSON,proto3" json:"patternsJSON,omitempty"`
	// patternsHash 表示模式哈希（可选，自动计算）
	PatternsHash *string `protobuf:"bytes,7,opt,name=patternsHash,proto3,oneof" json:"patternsHash,omitempty"`
	// evidenceSignatureJSON 表示证据签名 JSON（可选）
	EvidenceSignatureJSON *string `protobuf:"bytes,8,opt,name=evidenceSignatureJSON,proto3,oneof" json:"evidenceSignatureJSON,omitempty"`
	// confidence 表示置信度（可选，默认 0.7）
	Confidence    *float64 `protobuf:"fixed64,9,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKBEntryRequest) Reset() {
	*x = CreateKBEntryRequest{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKBEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKBEntryRequest) ProtoMessage() {}

func (x *CreateKBEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKBEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateKBEntryRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKBEntryRequest) GetKbID() string {
	if x != nil && x.KbID != nil {
		return *x.KbID
	}
	return ""
}

func (x *CreateKBEntryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateKBEntryRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CreateKBEntryRequest) GetRootCauseType() string {
	if x != nil {
		return x.RootCauseType
	}
	return ""
}

func (x *CreateKBEntryRequest) GetRootCauseSummary() string {
	if x != nil {
		return x.RootCauseSummary
	}
	return ""
}

func (x *CreateKBEntryRequest) GetPatternsJSON() string {
	if x != nil {
		return x.PatternsJSON
	}
	return ""
}

func (x *CreateKBEntryRequest) GetPatternsHash() string {
	if x != nil && x.PatternsHash != nil {
		return *x.PatternsHash
	}
	return ""
}

func (x *CreateKBEntryRequest) GetEvidenceSignatureJSON() string {
	if x != nil && x.EvidenceSignatureJSON != nil {
		return *x.EvidenceSignatureJSON
	}
	return ""
}

func (x *CreateKBEntryRequest) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

// CreateKBEntryResponse 表示创建知识库条目响应
type CreateKBEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kbEntry 表示创建的知识库条目
	KbEntry       *KBEntry `protobuf:"bytes,1,opt,name=kbEntry,proto3" json:"kbEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKBEntryResponse) Reset() {
	*x = CreateKBEntryResponse{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKBEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKBEntryResponse) ProtoMessage() {}

func (x *CreateKBEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKBEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateKBEntryResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKBEntryResponse) GetKbEntry() *KBEntry {
	if x != nil {
		return x.KbEntry
	}
	return nil
}

// GetKBEntryRequest 表示获取知识库条目请求
type GetKBEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kbID 表示要获取的知识库条目 ID
	// @gotags: uri:"kbID"
	KbID          string `protobuf:"bytes,1,opt,name=kbID,proto3" json:"kbID,omitempty" uri:"kbID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKBEntryRequest) Reset() {
	*x = GetKBEntryRequest{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKBEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKBEntryRequest) ProtoMessage() {}

func (x *GetKBEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKBEntryRequest.ProtoReflect.Descriptor instead.
func (*GetKBEntryRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{3}
}

func (x *GetKBEntryRequest) GetKbID() string {
	if x != nil {
		return x.KbID
	}
	return ""
}

// GetKBEntryResponse 表示获取知识库条目响应
type GetKBEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kbEntry 表示返回的知识库条目信息
	KbEntry       *KBEntry `protobuf:"bytes,1,opt,name=kbEntry,proto3" json:"kbEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKBEntryResponse) Reset() {
	*x = GetKBEntryResponse{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKBEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKBEntryResponse) ProtoMessage() {}

func (x *GetKBEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKBEntryResponse.ProtoReflect.Descriptor instead.
func (*GetKBEntryResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{4}
}

func (x *GetKBEntryResponse) GetKbEntry() *KBEntry {
	if x != nil {
		return x.KbEntry
	}
	return nil
}

// UpdateKBEntryRequest 表示更新知识库条目请求
type UpdateKBEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kbID 表示要更新的知识库条目 ID
	// @gotags: uri:"kbID"
	KbID string `protobuf:"bytes,1,opt,name=kbID,proto3" json:"kbID,omitempty" uri:"kbID"`
	// rootCauseSummary 表示更新后的根因摘要（可选）
	RootCauseSummary *string `protobuf:"bytes,2,opt,name=rootCauseSummary,proto3,oneof" json:"rootCauseSummary,omitempty"`
	// patternsJSON 表示更新后的模式匹配规则 JSON（可选）
	PatternsJSON *string `protobuf:"bytes,3,opt,name=patternsJSON,proto3,oneof" json:"patternsJSON,omitempty"`
	// patternsHash 表示更新后的模式哈希（可选，自动计算）
	PatternsHash *string `protobuf:"bytes,4,opt,name=patternsHash,proto3,oneof" json:"patternsHash,omitempty"`
	// evidenceSignatureJSON 表示更新后的证据签名 JSON（可选）
	EvidenceSignatureJSON *string `protobuf:"bytes,5,opt,name=evidenceSignatureJSON,proto3,oneof" json:"evidenceSignatureJSON,omitempty"`
	// confidence 表示更新后的置信度（可选）
	Confidence    *float64 `protobuf:"fixed64,6,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKBEntryRequest) Reset() {
	*x = UpdateKBEntryRequest{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKBEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKBEntryRequest) ProtoMessage() {}

func (x *UpdateKBEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKBEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateKBEntryRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateKBEntryRequest) GetKbID() string {
	if x != nil {
		return x.KbID
	}
	return ""
}

func (x *UpdateKBEntryRequest) GetRootCauseSummary() string {
	if x != nil && x.RootCauseSummary != nil {
		return *x.RootCauseSummary
	}
	return ""
}

func (x *UpdateKBEntryRequest) GetPatternsJSON() string {
	if x != nil && x.PatternsJSON != nil {
		return *x.PatternsJSON
	}
	return ""
}

func (x *UpdateKBEntryRequest) GetPatternsHash() string {
	if x != nil && x.PatternsHash != nil {
		return *x.PatternsHash
	}
	return ""
}

func (x *UpdateKBEntryRequest) GetEvidenceSignatureJSON() string {
	if x != nil && x.EvidenceSignatureJSON != nil {
		return *x.EvidenceSignatureJSON
	}
	return ""
}

func (x *UpdateKBEntryRequest) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

// UpdateKBEntryResponse 表示更新知识库条目响应
type UpdateKBEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kbEntry 表示更新后的知识库条目
	KbEntry       *KBEntry `protobuf:"bytes,1,opt,name=kbEntry,proto3" json:"kbEntry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKBEntryResponse) Reset() {
	*x = UpdateKBEntryResponse{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKBEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKBEntryResponse) ProtoMessage() {}

func (x *UpdateKBEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKBEntryResponse.ProtoReflect.Descriptor instead.
func (*UpdateKBEntryResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateKBEntryResponse) GetKbEntry() *KBEntry {
	if x != nil {
		return x.KbEntry
	}
	return nil
}

// DeleteKBEntryRequest 表示删除知识库条目请求
type DeleteKBEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kbID 表示要删除的知识库条目 ID
	// @gotags: uri:"kbID"
	KbID          string `protobuf:"bytes,1,opt,name=kbID,proto3" json:"kbID,omitempty" uri:"kbID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKBEntryRequest) Reset() {
	*x = DeleteKBEntryRequest{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKBEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKBEntryRequest) ProtoMessage() {}

func (x *DeleteKBEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKBEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteKBEntryRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKBEntryRequest) GetKbID() string {
	if x != nil {
		return x.KbID
	}
	return ""
}

// DeleteKBEntryResponse 表示删除知识库条目响应
type DeleteKBEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKBEntryResponse) Reset() {
	*x = DeleteKBEntryResponse{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKBEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKBEntryResponse) ProtoMessage() {}

func (x *DeleteKBEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKBEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteKBEntryResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{8}
}

// ListKBEntriesRequest 表示获取知识库条目列表请求
type ListKBEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// namespace 表示可选的命名空间过滤
	Namespace *string `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	// service 表示可选的服务过滤
	Service *string `protobuf:"bytes,4,opt,name=service,proto3,oneof" json:"service,omitempty"`
	// rootCauseType 表示可选的根因类型过滤
	RootCauseType *string `protobuf:"bytes,5,opt,name=rootCauseType,proto3,oneof" json:"rootCauseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKBEntriesRequest) Reset() {
	*x = ListKBEntriesRequest{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKBEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKBEntriesRequest) ProtoMessage() {}

func (x *ListKBEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKBEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListKBEntriesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{9}
}

func (x *ListKBEntriesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListKBEntriesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListKBEntriesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ListKBEntriesRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *ListKBEntriesRequest) GetRootCauseType() string {
	if x != nil && x.RootCauseType != nil {
		return *x.RootCauseType
	}
	return ""
}

// ListKBEntriesResponse 表示获取知识库条目列表响应
type ListKBEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示总条目数
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// kbEntries 表示知识库条目列表
	KbEntries     []*KBEntry `protobuf:"bytes,2,rep,name=kbEntries,proto3" json:"kbEntries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKBEntriesResponse) Reset() {
	*x = ListKBEntriesResponse{}
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKBEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKBEntriesResponse) ProtoMessage() {}

func (x *ListKBEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_kb_entry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKBEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListKBEntriesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_kb_entry_proto_rawDescGZIP(), []int{10}
}

func (x *ListKBEntriesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListKBEntriesResponse) GetKbEntries() []*KBEntry {
	if x != nil {
		return x.KbEntries
	}
	return nil
}

var File_apiserver_v1_kb_entry_proto protoreflect.FileDescriptor

const file_apiserver_v1_kb_entry_proto_rawDesc = "" +
	"\n" +
	"\x1bapiserver/v1/kb_entry.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x04\n" +
	"\aKBEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04kbID\x18\x02 \x01(\tR\x04kbID\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12$\n" +
	"\rrootCauseType\x18\x05 \x01(\tR\rrootCauseType\x12*\n" +
	"\x10rootCauseSummary\x18\x06 \x01(\tR\x10rootCauseSummary\x12\"\n" +
	"\fpatternsJSON\x18\a \x01(\tR\fpatternsJSON\x12\"\n" +
	"\fpatternsHash\x18\b \x01(\tR\fpatternsHash\x129\n" +
	"\x15evidenceSignatureJSON\x18\t \x01(\tH\x00R\x15evidenceSignatureJSON\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bhitCount\x18\v \x01(\x03R\bhitCount\x12=\n" +
	"\tlastHitAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tlastHitAt\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x18\n" +
	"\x16_evidenceSignatureJSONB\f\n" +
	"\n" +
	"_lastHitAt\"\xa9\x03\n" +
	"\x14CreateKBEntryRequest\x12\x17\n" +
	"\x04kbID\x18\x01 \x01(\tH\x00R\x04kbID\x88\x01\x01\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12$\n" +
	"\rrootCauseType\x18\x04 \x01(\tR\rrootCauseType\x12*\n" +
	"\x10rootCauseSummary\x18\x05 \x01(\tR\x10rootCauseSummary\x12\"\n" +
	"\fpatternsJSON\x18\x06 \x01(\tR\fpatternsJSON\x12'\n" +
	"\fpatternsHash\x18\a \x01(\tH\x01R\fpatternsHash\x88\x01\x01\x129\n" +
	"\x15evidenceSignatureJSON\x18\b \x01(\tH\x02R\x15evidenceSignatureJSON\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\t \x01(\x01H\x03R\n" +
	"confidence\x88\x01\x01B\a\n" +
	"\x05_kbIDB\x0f\n" +
	"\r_patternsHashB\x18\n" +
	"\x16_evidenceSignatureJSONB\r\n" +
	"\v_confidence\"H\n" +
	"\x15CreateKBEntryResponse\x12/\n" +
	"\akbEntry\x18\x01 \x01(\v2\x15.apiserver.v1.KBEntryR\akbEntry\"'\n" +
	"\x11GetKBEntryRequest\x12\x12\n" +
	"\x04kbID\x18\x01 \x01(\tR\x04kbID\"E\n" +
	"\x12GetKBEntryResponse\x12/\n" +
	"\akbEntry\x18\x01 \x01(\v2\x15.apiserver.v1.KBEntryR\akbEntry\"\xed\x02\n" +
	"\x14UpdateKBEntryRequest\x12\x12\n" +
	"\x04kbID\x18\x01 \x01(\tR\x04kbID\x12/\n" +
	"\x10rootCauseSummary\x18\x02 \x01(\tH\x00R\x10rootCauseSummary\x88\x01\x01\x12'\n" +
	"\fpatternsJSON\x18\x03 \x01(\tH\x01R\fpatternsJSON\x88\x01\x01\x12'\n" +
	"\fpatternsHash\x18\x04 \x01(\tH\x02R\fpatternsHash\x88\x01\x01\x129\n" +
	"\x15evidenceSignatureJSON\x18\x05 \x01(\tH\x03R\x15evidenceSignatureJSON\x88\x01\x01\x12#\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01H\x04R\n" +
	"confidence\x88\x01\x01B\x13\n" +
	"\x11_rootCauseSummaryB\x0f\n" +
	"\r_patternsJSONB\x0f\n" +
	"\r_patternsHashB\x18\n" +
	"\x16_evidenceSignatureJSONB\r\n" +
	"\v_confidence\"H\n" +
	"\x15UpdateKBEntryResponse\x12/\n" +
	"\akbEntry\x18\x01 \x01(\v2\x15.apiserver.v1.KBEntryR\akbEntry\"*\n" +
	"\x14DeleteKBEntryRequest\x12\x12\n" +
	"\x04kbID\x18\x01 \x01(\tR\x04kbID\"\x17\n" +
	"\x15DeleteKBEntryResponse\"\xdd\x01\n" +
	"\x14ListKBEntriesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12\x1d\n" +
	"\aservice\x18\x04 \x01(\tH\x01R\aservice\x88\x01\x01\x12)\n" +
	"\rrootCauseType\x18\x05 \x01(\tH\x02R\rrootCauseType\x88\x01\x01B\f\n" +
	"\n" +
	"_namespaceB\n" +
	"\n" +
	"\b_serviceB\x10\n" +
	"\x0e_rootCauseType\"l\n" +
	"\x15ListKBEntriesResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x123\n" +
	"\tkbEntries\x18\x02 \x03(\v2\x15.apiserver.v1.KBEntryR\tkbEntriesB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_kb_entry_proto_rawDescOnce sync.Once
	file_apiserver_v1_kb_entry_proto_rawDescData []byte
)

func file_apiserver_v1_kb_entry_proto_rawDescGZIP() []byte {
	file_apiserver_v1_kb_entry_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_kb_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_kb_entry_proto_rawDesc), len(file_apiserver_v1_kb_entry_proto_rawDesc)))
	})
	return file_apiserver_v1_kb_entry_proto_rawDescData
}

var file_apiserver_v1_kb_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_kb_entry_proto_goTypes = []any{
	(*KBEntry)(nil),               // 0: apiserver.v1.KBEntry
	(*CreateKBEntryRequest)(nil),  // 1: apiserver.v1.CreateKBEntryRequest
	(*CreateKBEntryResponse)(nil), // 2: apiserver.v1.CreateKBEntryResponse
	(*GetKBEntryRequest)(nil),     // 3: apiserver.v1.GetKBEntryRequest
	(*GetKBEntryResponse)(nil),    // 4: apiserver.v1.GetKBEntryResponse
	(*UpdateKBEntryRequest)(nil),  // 5: apiserver.v1.UpdateKBEntryRequest
	(*UpdateKBEntryResponse)(nil), // 6: apiserver.v1.UpdateKBEntryResponse
	(*DeleteKBEntryRequest)(nil),  // 7: apiserver.v1.DeleteKBEntryRequest
	(*DeleteKBEntryResponse)(nil), // 8: apiserver.v1.DeleteKBEntryResponse
	(*ListKBEntriesRequest)(nil),  // 9: apiserver.v1.ListKBEntriesRequest
	(*ListKBEntriesResponse)(nil), // 10: apiserver.v1.ListKBEntriesResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_apiserver_v1_kb_entry_proto_depIdxs = []int32{
	11, // 0: apiserver.v1.KBEntry.lastHitAt:type_name -> google.protobuf.Timestamp
	11, // 1: apiserver.v1.KBEntry.createdAt:type_name -> google.protobuf.Timestamp
	11, // 2: apiserver.v1.KBEntry.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: apiserver.v1.CreateKBEntryResponse.kbEntry:type_name -> apiserver.v1.KBEntry
	0,  // 4: apiserver.v1.GetKBEntryResponse.kbEntry:type_name -> apiserver.v1.KBEntry
	0,  // 5: apiserver.v1.UpdateKBEntryResponse.kbEntry:type_name -> apiserver.v1.KBEntry
	0,  // 6: apiserver.v1.ListKBEntriesResponse.kbEntries:type_name -> apiserver.v1.KBEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_apiserver_v1_kb_entry_proto_init() }
func file_apiserver_v1_kb_entry_proto_init() {
	if File_apiserver_v1_kb_entry_proto != nil {
		return
	}
	file_apiserver_v1_kb_entry_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_kb_entry_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_kb_entry_proto_msgTypes[5].OneofWrappers = []any{}
	file_apiserver_v1_kb_entry_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_kb_entry_proto_rawDesc), len(file_apiserver_v1_kb_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_kb_entry_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_kb_entry_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_kb_entry_proto_msgTypes,
	}.Build()
	File_apiserver_v1_kb_entry_proto = out.File
	file_apiserver_v1_kb_entry_proto_goTypes = nil
	file_apiserver_v1_kb_entry_proto_depIdxs = nil
}
