// McpServer API 定义：MCP 服务器的请求和响应消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apiserver/v1/mcp_server.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// McpServer 表示一个外部 MCP 服务器注册信息
// External MCP servers are called by the orchestrator via MCP protocol.
type McpServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mcpServerID 表示 MCP 服务器业务 ID
	McpServerID string `protobuf:"bytes,1,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty"`
	// name 表示 MCP 服务器名称（唯一标识）
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// displayName 表示显示名称
	DisplayName *string `protobuf:"bytes,3,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	// description 表示描述信息
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// baseURL 表示 MCP 服务器地址
	BaseURL string `protobuf:"bytes,5,opt,name=baseURL,proto3" json:"baseURL,omitempty"`
	// authType 表示认证类型（none/bearer/basic/apikey）
	AuthType string `protobuf:"bytes,6,opt,name=authType,proto3" json:"authType,omitempty"`
	// authSecretRef 表示认证密钥引用
	AuthSecretRef *string `protobuf:"bytes,7,opt,name=authSecretRef,proto3,oneof" json:"authSecretRef,omitempty"`
	// allowedToolsJSON 表示允许的工具列表（JSON array）
	AllowedToolsJSON *string `protobuf:"bytes,8,opt,name=allowedToolsJSON,proto3,oneof" json:"allowedToolsJSON,omitempty"`
	// timeoutSec 表示超时时间（秒）
	TimeoutSec int32 `protobuf:"varint,9,opt,name=timeoutSec,proto3" json:"timeoutSec,omitempty"`
	// scopes 表示权限范围
	Scopes *string `protobuf:"bytes,10,opt,name=scopes,proto3,oneof" json:"scopes,omitempty"`
	// status 表示状态（active/inactive）
	Status string `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	// createdBy 表示创建者
	CreatedBy *string `protobuf:"bytes,12,opt,name=createdBy,proto3,oneof" json:"createdBy,omitempty"`
	// createdAt 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpServer) Reset() {
	*x = McpServer{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpServer) ProtoMessage() {}

func (x *McpServer) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpServer.ProtoReflect.Descriptor instead.
func (*McpServer) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{0}
}

func (x *McpServer) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

func (x *McpServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *McpServer) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *McpServer) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *McpServer) GetBaseURL() string {
	if x != nil {
		return x.BaseURL
	}
	return ""
}

func (x *McpServer) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *McpServer) GetAuthSecretRef() string {
	if x != nil && x.AuthSecretRef != nil {
		return *x.AuthSecretRef
	}
	return ""
}

func (x *McpServer) GetAllowedToolsJSON() string {
	if x != nil && x.AllowedToolsJSON != nil {
		return *x.AllowedToolsJSON
	}
	return ""
}

func (x *McpServer) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *McpServer) GetScopes() string {
	if x != nil && x.Scopes != nil {
		return *x.Scopes
	}
	return ""
}

func (x *McpServer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *McpServer) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *McpServer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *McpServer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateMcpServerRequest 表示创建 MCP 服务器请求
type CreateMcpServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 表示 MCP 服务器名称（必填）
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// displayName 表示显示名称
	DisplayName *string `protobuf:"bytes,2,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	// description 表示描述信息
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// baseURL 表示 MCP 服务器地址（必填）
	BaseURL string `protobuf:"bytes,4,opt,name=baseURL,proto3" json:"baseURL,omitempty"`
	// authType 表示认证类型（默认 none）
	AuthType *string `protobuf:"bytes,5,opt,name=authType,proto3,oneof" json:"authType,omitempty"`
	// authSecretRef 表示认证密钥引用
	AuthSecretRef *string `protobuf:"bytes,6,opt,name=authSecretRef,proto3,oneof" json:"authSecretRef,omitempty"`
	// allowedToolsJSON 表示允许的工具列表（JSON array）
	AllowedToolsJSON *string `protobuf:"bytes,7,opt,name=allowedToolsJSON,proto3,oneof" json:"allowedToolsJSON,omitempty"`
	// timeoutSec 表示超时时间（秒，默认 10）
	TimeoutSec *int32 `protobuf:"varint,8,opt,name=timeoutSec,proto3,oneof" json:"timeoutSec,omitempty"`
	// scopes 表示权限范围
	Scopes        *string `protobuf:"bytes,9,opt,name=scopes,proto3,oneof" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMcpServerRequest) Reset() {
	*x = CreateMcpServerRequest{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMcpServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMcpServerRequest) ProtoMessage() {}

func (x *CreateMcpServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMcpServerRequest.ProtoReflect.Descriptor instead.
func (*CreateMcpServerRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMcpServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMcpServerRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *CreateMcpServerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateMcpServerRequest) GetBaseURL() string {
	if x != nil {
		return x.BaseURL
	}
	return ""
}

func (x *CreateMcpServerRequest) GetAuthType() string {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return ""
}

func (x *CreateMcpServerRequest) GetAuthSecretRef() string {
	if x != nil && x.AuthSecretRef != nil {
		return *x.AuthSecretRef
	}
	return ""
}

func (x *CreateMcpServerRequest) GetAllowedToolsJSON() string {
	if x != nil && x.AllowedToolsJSON != nil {
		return *x.AllowedToolsJSON
	}
	return ""
}

func (x *CreateMcpServerRequest) GetTimeoutSec() int32 {
	if x != nil && x.TimeoutSec != nil {
		return *x.TimeoutSec
	}
	return 0
}

func (x *CreateMcpServerRequest) GetScopes() string {
	if x != nil && x.Scopes != nil {
		return *x.Scopes
	}
	return ""
}

// CreateMcpServerResponse 表示创建 MCP 服务器响应
type CreateMcpServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mcpServer 表示创建的 MCP 服务器信息
	McpServer     *McpServer `protobuf:"bytes,1,opt,name=mcpServer,proto3" json:"mcpServer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMcpServerResponse) Reset() {
	*x = CreateMcpServerResponse{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMcpServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMcpServerResponse) ProtoMessage() {}

func (x *CreateMcpServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMcpServerResponse.ProtoReflect.Descriptor instead.
func (*CreateMcpServerResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMcpServerResponse) GetMcpServer() *McpServer {
	if x != nil {
		return x.McpServer
	}
	return nil
}

// GetMcpServerRequest 表示获取 MCP 服务器请求
type GetMcpServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mcpServerID 表示要获取的 MCP 服务器 ID
	// @gotags: uri:"mcpServerID"
	McpServerID   string `protobuf:"bytes,1,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty" uri:"mcpServerID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpServerRequest) Reset() {
	*x = GetMcpServerRequest{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpServerRequest) ProtoMessage() {}

func (x *GetMcpServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpServerRequest.ProtoReflect.Descriptor instead.
func (*GetMcpServerRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetMcpServerRequest) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

// GetMcpServerResponse 表示获取 MCP 服务器响应
type GetMcpServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mcpServer 表示返回的 MCP 服务器信息
	McpServer     *McpServer `protobuf:"bytes,1,opt,name=mcpServer,proto3" json:"mcpServer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpServerResponse) Reset() {
	*x = GetMcpServerResponse{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpServerResponse) ProtoMessage() {}

func (x *GetMcpServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpServerResponse.ProtoReflect.Descriptor instead.
func (*GetMcpServerResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetMcpServerResponse) GetMcpServer() *McpServer {
	if x != nil {
		return x.McpServer
	}
	return nil
}

// ListMcpServersRequest 表示获取 MCP 服务器列表请求
type ListMcpServersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// name 表示可选的名称过滤
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// status 表示可选的状态过滤
	Status        *string `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMcpServersRequest) Reset() {
	*x = ListMcpServersRequest{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMcpServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMcpServersRequest) ProtoMessage() {}

func (x *ListMcpServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMcpServersRequest.ProtoReflect.Descriptor instead.
func (*ListMcpServersRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{5}
}

func (x *ListMcpServersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMcpServersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMcpServersRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListMcpServersRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// ListMcpServersResponse 表示获取 MCP 服务器列表响应
type ListMcpServersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示总数
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// mcpServers 表示 MCP 服务器列表
	McpServers    []*McpServer `protobuf:"bytes,2,rep,name=mcpServers,proto3" json:"mcpServers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMcpServersResponse) Reset() {
	*x = ListMcpServersResponse{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMcpServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMcpServersResponse) ProtoMessage() {}

func (x *ListMcpServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMcpServersResponse.ProtoReflect.Descriptor instead.
func (*ListMcpServersResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{6}
}

func (x *ListMcpServersResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMcpServersResponse) GetMcpServers() []*McpServer {
	if x != nil {
		return x.McpServers
	}
	return nil
}

// UpdateMcpServerRequest 表示更新 MCP 服务器请求
type UpdateMcpServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mcpServerID 表示要更新的 MCP 服务器 ID
	// @gotags: uri:"mcpServerID"
	McpServerID string `protobuf:"bytes,1,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty" uri:"mcpServerID"`
	// displayName 表示显示名称
	DisplayName *string `protobuf:"bytes,2,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	// description 表示描述信息
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// baseURL 表示 MCP 服务器地址
	BaseURL *string `protobuf:"bytes,4,opt,name=baseURL,proto3,oneof" json:"baseURL,omitempty"`
	// authType 表示认证类型
	AuthType *string `protobuf:"bytes,5,opt,name=authType,proto3,oneof" json:"authType,omitempty"`
	// authSecretRef 表示认证密钥引用
	AuthSecretRef *string `protobuf:"bytes,6,opt,name=authSecretRef,proto3,oneof" json:"authSecretRef,omitempty"`
	// allowedToolsJSON 表示允许的工具列表（JSON array）
	AllowedToolsJSON *string `protobuf:"bytes,7,opt,name=allowedToolsJSON,proto3,oneof" json:"allowedToolsJSON,omitempty"`
	// timeoutSec 表示超时时间（秒）
	TimeoutSec *int32 `protobuf:"varint,8,opt,name=timeoutSec,proto3,oneof" json:"timeoutSec,omitempty"`
	// scopes 表示权限范围
	Scopes *string `protobuf:"bytes,9,opt,name=scopes,proto3,oneof" json:"scopes,omitempty"`
	// status 表示状态
	Status        *string `protobuf:"bytes,10,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMcpServerRequest) Reset() {
	*x = UpdateMcpServerRequest{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMcpServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMcpServerRequest) ProtoMessage() {}

func (x *UpdateMcpServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMcpServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateMcpServerRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMcpServerRequest) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetBaseURL() string {
	if x != nil && x.BaseURL != nil {
		return *x.BaseURL
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetAuthType() string {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetAuthSecretRef() string {
	if x != nil && x.AuthSecretRef != nil {
		return *x.AuthSecretRef
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetAllowedToolsJSON() string {
	if x != nil && x.AllowedToolsJSON != nil {
		return *x.AllowedToolsJSON
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetTimeoutSec() int32 {
	if x != nil && x.TimeoutSec != nil {
		return *x.TimeoutSec
	}
	return 0
}

func (x *UpdateMcpServerRequest) GetScopes() string {
	if x != nil && x.Scopes != nil {
		return *x.Scopes
	}
	return ""
}

func (x *UpdateMcpServerRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// UpdateMcpServerResponse 表示更新 MCP 服务器响应
type UpdateMcpServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mcpServer 表示更新后的 MCP 服务器信息
	McpServer     *McpServer `protobuf:"bytes,1,opt,name=mcpServer,proto3" json:"mcpServer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMcpServerResponse) Reset() {
	*x = UpdateMcpServerResponse{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMcpServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMcpServerResponse) ProtoMessage() {}

func (x *UpdateMcpServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMcpServerResponse.ProtoReflect.Descriptor instead.
func (*UpdateMcpServerResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMcpServerResponse) GetMcpServer() *McpServer {
	if x != nil {
		return x.McpServer
	}
	return nil
}

// DeleteMcpServerRequest 表示删除 MCP 服务器请求
type DeleteMcpServerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mcpServerID 表示要删除的 MCP 服务器 ID
	// @gotags: uri:"mcpServerID"
	McpServerID   string `protobuf:"bytes,1,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty" uri:"mcpServerID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMcpServerRequest) Reset() {
	*x = DeleteMcpServerRequest{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMcpServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMcpServerRequest) ProtoMessage() {}

func (x *DeleteMcpServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMcpServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteMcpServerRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMcpServerRequest) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

// DeleteMcpServerResponse 表示删除 MCP 服务器响应
type DeleteMcpServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMcpServerResponse) Reset() {
	*x = DeleteMcpServerResponse{}
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMcpServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMcpServerResponse) ProtoMessage() {}

func (x *DeleteMcpServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_mcp_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMcpServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteMcpServerResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_mcp_server_proto_rawDescGZIP(), []int{10}
}

var File_apiserver_v1_mcp_server_proto protoreflect.FileDescriptor

const file_apiserver_v1_mcp_server_proto_rawDesc = "" +
	"\n" +
	"\x1dapiserver/v1/mcp_server.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x04\n" +
	"\tMcpServer\x12 \n" +
	"\vmcpServerID\x18\x01 \x01(\tR\vmcpServerID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdisplayName\x18\x03 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x18\n" +
	"\abaseURL\x18\x05 \x01(\tR\abaseURL\x12\x1a\n" +
	"\bauthType\x18\x06 \x01(\tR\bauthType\x12)\n" +
	"\rauthSecretRef\x18\a \x01(\tH\x02R\rauthSecretRef\x88\x01\x01\x12/\n" +
	"\x10allowedToolsJSON\x18\b \x01(\tH\x03R\x10allowedToolsJSON\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"timeoutSec\x18\t \x01(\x05R\n" +
	"timeoutSec\x12\x1b\n" +
	"\x06scopes\x18\n" +
	" \x01(\tH\x04R\x06scopes\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12!\n" +
	"\tcreatedBy\x18\f \x01(\tH\x05R\tcreatedBy\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_displayNameB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_authSecretRefB\x13\n" +
	"\x11_allowedToolsJSONB\t\n" +
	"\a_scopesB\f\n" +
	"\n" +
	"_createdBy\"\xc1\x03\n" +
	"\x16CreateMcpServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdisplayName\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x18\n" +
	"\abaseURL\x18\x04 \x01(\tR\abaseURL\x12\x1f\n" +
	"\bauthType\x18\x05 \x01(\tH\x02R\bauthType\x88\x01\x01\x12)\n" +
	"\rauthSecretRef\x18\x06 \x01(\tH\x03R\rauthSecretRef\x88\x01\x01\x12/\n" +
	"\x10allowedToolsJSON\x18\a \x01(\tH\x04R\x10allowedToolsJSON\x88\x01\x01\x12#\n" +
	"\n" +
	"timeoutSec\x18\b \x01(\x05H\x05R\n" +
	"timeoutSec\x88\x01\x01\x12\x1b\n" +
	"\x06scopes\x18\t \x01(\tH\x06R\x06scopes\x88\x01\x01B\x0e\n" +
	"\f_displayNameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_authTypeB\x10\n" +
	"\x0e_authSecretRefB\x13\n" +
	"\x11_allowedToolsJSONB\r\n" +
	"\v_timeoutSecB\t\n" +
	"\a_scopes\"P\n" +
	"\x17CreateMcpServerResponse\x125\n" +
	"\tmcpServer\x18\x01 \x01(\v2\x17.apiserver.v1.McpServerR\tmcpServer\"7\n" +
	"\x13GetMcpServerRequest\x12 \n" +
	"\vmcpServerID\x18\x01 \x01(\tR\vmcpServerID\"M\n" +
	"\x14GetMcpServerResponse\x125\n" +
	"\tmcpServer\x18\x01 \x01(\v2\x17.apiserver.v1.McpServerR\tmcpServer\"\x8f\x01\n" +
	"\x15ListMcpServersRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x01R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_status\"q\n" +
	"\x16ListMcpServersResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x127\n" +
	"\n" +
	"mcpServers\x18\x02 \x03(\v2\x17.apiserver.v1.McpServerR\n" +
	"mcpServers\"\x88\x04\n" +
	"\x16UpdateMcpServerRequest\x12 \n" +
	"\vmcpServerID\x18\x01 \x01(\tR\vmcpServerID\x12%\n" +
	"\vdisplayName\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\abaseURL\x18\x04 \x01(\tH\x02R\abaseURL\x88\x01\x01\x12\x1f\n" +
	"\bauthType\x18\x05 \x01(\tH\x03R\bauthType\x88\x01\x01\x12)\n" +
	"\rauthSecretRef\x18\x06 \x01(\tH\x04R\rauthSecretRef\x88\x01\x01\x12/\n" +
	"\x10allowedToolsJSON\x18\a \x01(\tH\x05R\x10allowedToolsJSON\x88\x01\x01\x12#\n" +
	"\n" +
	"timeoutSec\x18\b \x01(\x05H\x06R\n" +
	"timeoutSec\x88\x01\x01\x12\x1b\n" +
	"\x06scopes\x18\t \x01(\tH\aR\x06scopes\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\n" +
	" \x01(\tH\bR\x06status\x88\x01\x01B\x0e\n" +
	"\f_displayNameB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_baseURLB\v\n" +
	"\t_authTypeB\x10\n" +
	"\x0e_authSecretRefB\x13\n" +
	"\x11_allowedToolsJSONB\r\n" +
	"\v_timeoutSecB\t\n" +
	"\a_scopesB\t\n" +
	"\a_status\"P\n" +
	"\x17UpdateMcpServerResponse\x125\n" +
	"\tmcpServer\x18\x01 \x01(\v2\x17.apiserver.v1.McpServerR\tmcpServer\":\n" +
	"\x16DeleteMcpServerRequest\x12 \n" +
	"\vmcpServerID\x18\x01 \x01(\tR\vmcpServerID\"\x19\n" +
	"\x17DeleteMcpServerResponseB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_mcp_server_proto_rawDescOnce sync.Once
	file_apiserver_v1_mcp_server_proto_rawDescData []byte
)

func file_apiserver_v1_mcp_server_proto_rawDescGZIP() []byte {
	file_apiserver_v1_mcp_server_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_mcp_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_mcp_server_proto_rawDesc), len(file_apiserver_v1_mcp_server_proto_rawDesc)))
	})
	return file_apiserver_v1_mcp_server_proto_rawDescData
}

var file_apiserver_v1_mcp_server_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_mcp_server_proto_goTypes = []any{
	(*McpServer)(nil),               // 0: apiserver.v1.McpServer
	(*CreateMcpServerRequest)(nil),  // 1: apiserver.v1.CreateMcpServerRequest
	(*CreateMcpServerResponse)(nil), // 2: apiserver.v1.CreateMcpServerResponse
	(*GetMcpServerRequest)(nil),     // 3: apiserver.v1.GetMcpServerRequest
	(*GetMcpServerResponse)(nil),    // 4: apiserver.v1.GetMcpServerResponse
	(*ListMcpServersRequest)(nil),   // 5: apiserver.v1.ListMcpServersRequest
	(*ListMcpServersResponse)(nil),  // 6: apiserver.v1.ListMcpServersResponse
	(*UpdateMcpServerRequest)(nil),  // 7: apiserver.v1.UpdateMcpServerRequest
	(*UpdateMcpServerResponse)(nil), // 8: apiserver.v1.UpdateMcpServerResponse
	(*DeleteMcpServerRequest)(nil),  // 9: apiserver.v1.DeleteMcpServerRequest
	(*DeleteMcpServerResponse)(nil), // 10: apiserver.v1.DeleteMcpServerResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_apiserver_v1_mcp_server_proto_depIdxs = []int32{
	11, // 0: apiserver.v1.McpServer.createdAt:type_name -> google.protobuf.Timestamp
	11, // 1: apiserver.v1.McpServer.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: apiserver.v1.CreateMcpServerResponse.mcpServer:type_name -> apiserver.v1.McpServer
	0,  // 3: apiserver.v1.GetMcpServerResponse.mcpServer:type_name -> apiserver.v1.McpServer
	0,  // 4: apiserver.v1.ListMcpServersResponse.mcpServers:type_name -> apiserver.v1.McpServer
	0,  // 5: apiserver.v1.UpdateMcpServerResponse.mcpServer:type_name -> apiserver.v1.McpServer
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_apiserver_v1_mcp_server_proto_init() }
func file_apiserver_v1_mcp_server_proto_init() {
	if File_apiserver_v1_mcp_server_proto != nil {
		return
	}
	file_apiserver_v1_mcp_server_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_mcp_server_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_mcp_server_proto_msgTypes[5].OneofWrappers = []any{}
	file_apiserver_v1_mcp_server_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_mcp_server_proto_rawDesc), len(file_apiserver_v1_mcp_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_mcp_server_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_mcp_server_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_mcp_server_proto_msgTypes,
	}.Build()
	File_apiserver_v1_mcp_server_proto = out.File
	file_apiserver_v1_mcp_server_proto_goTypes = nil
	file_apiserver_v1_mcp_server_proto_depIdxs = nil
}
