// Orchestrator skillset resolve API messages (read-only distribution).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apiserver/v1/orchestrator_skillset.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrchestratorSkillRelease defines one resolved skill release entry.
type OrchestratorSkillRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillID       string                 `protobuf:"bytes,1,opt,name=skillID,proto3" json:"skillID,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BundleDigest  string                 `protobuf:"bytes,3,opt,name=bundleDigest,proto3" json:"bundleDigest,omitempty"`
	ArtifactURL   string                 `protobuf:"bytes,4,opt,name=artifactURL,proto3" json:"artifactURL,omitempty"`
	ManifestJSON  *string                `protobuf:"bytes,5,opt,name=manifestJSON,proto3,oneof" json:"manifestJSON,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorSkillRelease) Reset() {
	*x = OrchestratorSkillRelease{}
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorSkillRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorSkillRelease) ProtoMessage() {}

func (x *OrchestratorSkillRelease) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorSkillRelease.ProtoReflect.Descriptor instead.
func (*OrchestratorSkillRelease) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_skillset_proto_rawDescGZIP(), []int{0}
}

func (x *OrchestratorSkillRelease) GetSkillID() string {
	if x != nil {
		return x.SkillID
	}
	return ""
}

func (x *OrchestratorSkillRelease) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OrchestratorSkillRelease) GetBundleDigest() string {
	if x != nil {
		return x.BundleDigest
	}
	return ""
}

func (x *OrchestratorSkillRelease) GetArtifactURL() string {
	if x != nil {
		return x.ArtifactURL
	}
	return ""
}

func (x *OrchestratorSkillRelease) GetManifestJSON() string {
	if x != nil && x.ManifestJSON != nil {
		return *x.ManifestJSON
	}
	return ""
}

func (x *OrchestratorSkillRelease) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// OrchestratorSkillset is one resolved skillset definition.
type OrchestratorSkillset struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	SkillsetID    string                      `protobuf:"bytes,1,opt,name=skillsetID,proto3" json:"skillsetID,omitempty"`
	Skills        []*OrchestratorSkillRelease `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorSkillset) Reset() {
	*x = OrchestratorSkillset{}
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorSkillset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorSkillset) ProtoMessage() {}

func (x *OrchestratorSkillset) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorSkillset.ProtoReflect.Descriptor instead.
func (*OrchestratorSkillset) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_skillset_proto_rawDescGZIP(), []int{1}
}

func (x *OrchestratorSkillset) GetSkillsetID() string {
	if x != nil {
		return x.SkillsetID
	}
	return ""
}

func (x *OrchestratorSkillset) GetSkills() []*OrchestratorSkillRelease {
	if x != nil {
		return x.Skills
	}
	return nil
}

// ResolveOrchestratorSkillsetsRequest resolves skillsets by pipeline.
type ResolveOrchestratorSkillsetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"pipeline"
	Pipeline      *string `protobuf:"bytes,1,opt,name=pipeline,proto3,oneof" json:"pipeline,omitempty" form:"pipeline"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOrchestratorSkillsetsRequest) Reset() {
	*x = ResolveOrchestratorSkillsetsRequest{}
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOrchestratorSkillsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOrchestratorSkillsetsRequest) ProtoMessage() {}

func (x *ResolveOrchestratorSkillsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOrchestratorSkillsetsRequest.ProtoReflect.Descriptor instead.
func (*ResolveOrchestratorSkillsetsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_skillset_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveOrchestratorSkillsetsRequest) GetPipeline() string {
	if x != nil && x.Pipeline != nil {
		return *x.Pipeline
	}
	return ""
}

// ResolveOrchestratorSkillsetsResponse returns normalized pipeline and resolved skillsets.
type ResolveOrchestratorSkillsetsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pipeline      string                  `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Skillsets     []*OrchestratorSkillset `protobuf:"bytes,2,rep,name=skillsets,proto3" json:"skillsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOrchestratorSkillsetsResponse) Reset() {
	*x = ResolveOrchestratorSkillsetsResponse{}
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOrchestratorSkillsetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOrchestratorSkillsetsResponse) ProtoMessage() {}

func (x *ResolveOrchestratorSkillsetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_skillset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOrchestratorSkillsetsResponse.ProtoReflect.Descriptor instead.
func (*ResolveOrchestratorSkillsetsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_skillset_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveOrchestratorSkillsetsResponse) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *ResolveOrchestratorSkillsetsResponse) GetSkillsets() []*OrchestratorSkillset {
	if x != nil {
		return x.Skillsets
	}
	return nil
}

var File_apiserver_v1_orchestrator_skillset_proto protoreflect.FileDescriptor

const file_apiserver_v1_orchestrator_skillset_proto_rawDesc = "" +
	"\n" +
	"(apiserver/v1/orchestrator_skillset.proto\x12\fapiserver.v1\"\xe6\x01\n" +
	"\x18OrchestratorSkillRelease\x12\x18\n" +
	"\askillID\x18\x01 \x01(\tR\askillID\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fbundleDigest\x18\x03 \x01(\tR\fbundleDigest\x12 \n" +
	"\vartifactURL\x18\x04 \x01(\tR\vartifactURL\x12'\n" +
	"\fmanifestJSON\x18\x05 \x01(\tH\x00R\fmanifestJSON\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06statusB\x0f\n" +
	"\r_manifestJSON\"v\n" +
	"\x14OrchestratorSkillset\x12\x1e\n" +
	"\n" +
	"skillsetID\x18\x01 \x01(\tR\n" +
	"skillsetID\x12>\n" +
	"\x06skills\x18\x02 \x03(\v2&.apiserver.v1.OrchestratorSkillReleaseR\x06skills\"S\n" +
	"#ResolveOrchestratorSkillsetsRequest\x12\x1f\n" +
	"\bpipeline\x18\x01 \x01(\tH\x00R\bpipeline\x88\x01\x01B\v\n" +
	"\t_pipeline\"\x84\x01\n" +
	"$ResolveOrchestratorSkillsetsResponse\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\x12@\n" +
	"\tskillsets\x18\x02 \x03(\v2\".apiserver.v1.OrchestratorSkillsetR\tskillsetsB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_orchestrator_skillset_proto_rawDescOnce sync.Once
	file_apiserver_v1_orchestrator_skillset_proto_rawDescData []byte
)

func file_apiserver_v1_orchestrator_skillset_proto_rawDescGZIP() []byte {
	file_apiserver_v1_orchestrator_skillset_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_orchestrator_skillset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_orchestrator_skillset_proto_rawDesc), len(file_apiserver_v1_orchestrator_skillset_proto_rawDesc)))
	})
	return file_apiserver_v1_orchestrator_skillset_proto_rawDescData
}

var file_apiserver_v1_orchestrator_skillset_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apiserver_v1_orchestrator_skillset_proto_goTypes = []any{
	(*OrchestratorSkillRelease)(nil),             // 0: apiserver.v1.OrchestratorSkillRelease
	(*OrchestratorSkillset)(nil),                 // 1: apiserver.v1.OrchestratorSkillset
	(*ResolveOrchestratorSkillsetsRequest)(nil),  // 2: apiserver.v1.ResolveOrchestratorSkillsetsRequest
	(*ResolveOrchestratorSkillsetsResponse)(nil), // 3: apiserver.v1.ResolveOrchestratorSkillsetsResponse
}
var file_apiserver_v1_orchestrator_skillset_proto_depIdxs = []int32{
	0, // 0: apiserver.v1.OrchestratorSkillset.skills:type_name -> apiserver.v1.OrchestratorSkillRelease
	1, // 1: apiserver.v1.ResolveOrchestratorSkillsetsResponse.skillsets:type_name -> apiserver.v1.OrchestratorSkillset
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apiserver_v1_orchestrator_skillset_proto_init() }
func file_apiserver_v1_orchestrator_skillset_proto_init() {
	if File_apiserver_v1_orchestrator_skillset_proto != nil {
		return
	}
	file_apiserver_v1_orchestrator_skillset_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_orchestrator_skillset_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_orchestrator_skillset_proto_rawDesc), len(file_apiserver_v1_orchestrator_skillset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_orchestrator_skillset_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_orchestrator_skillset_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_orchestrator_skillset_proto_msgTypes,
	}.Build()
	File_apiserver_v1_orchestrator_skillset_proto = out.File
	file_apiserver_v1_orchestrator_skillset_proto_goTypes = nil
	file_apiserver_v1_orchestrator_skillset_proto_depIdxs = nil
}
