// Orchestrator template registry API messages (register + list).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apiserver/v1/orchestrator_template.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrchestratorTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateID    string                 `protobuf:"bytes,1,opt,name=templateID,proto3" json:"templateID,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorTemplate) Reset() {
	*x = OrchestratorTemplate{}
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorTemplate) ProtoMessage() {}

func (x *OrchestratorTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorTemplate.ProtoReflect.Descriptor instead.
func (*OrchestratorTemplate) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_template_proto_rawDescGZIP(), []int{0}
}

func (x *OrchestratorTemplate) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *OrchestratorTemplate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterOrchestratorTemplatesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	InstanceID    string                  `protobuf:"bytes,1,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	Templates     []*OrchestratorTemplate `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOrchestratorTemplatesRequest) Reset() {
	*x = RegisterOrchestratorTemplatesRequest{}
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOrchestratorTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOrchestratorTemplatesRequest) ProtoMessage() {}

func (x *RegisterOrchestratorTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOrchestratorTemplatesRequest.ProtoReflect.Descriptor instead.
func (*RegisterOrchestratorTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_template_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterOrchestratorTemplatesRequest) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *RegisterOrchestratorTemplatesRequest) GetTemplates() []*OrchestratorTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type RegisterOrchestratorTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOrchestratorTemplatesResponse) Reset() {
	*x = RegisterOrchestratorTemplatesResponse{}
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOrchestratorTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOrchestratorTemplatesResponse) ProtoMessage() {}

func (x *RegisterOrchestratorTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOrchestratorTemplatesResponse.ProtoReflect.Descriptor instead.
func (*RegisterOrchestratorTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_template_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterOrchestratorTemplatesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListOrchestratorTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrchestratorTemplatesRequest) Reset() {
	*x = ListOrchestratorTemplatesRequest{}
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrchestratorTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrchestratorTemplatesRequest) ProtoMessage() {}

func (x *ListOrchestratorTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrchestratorTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListOrchestratorTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_template_proto_rawDescGZIP(), []int{3}
}

type OrchestratorTemplateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateID    string                 `protobuf:"bytes,1,opt,name=templateID,proto3" json:"templateID,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Instances     []string               `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorTemplateEntry) Reset() {
	*x = OrchestratorTemplateEntry{}
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorTemplateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorTemplateEntry) ProtoMessage() {}

func (x *OrchestratorTemplateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorTemplateEntry.ProtoReflect.Descriptor instead.
func (*OrchestratorTemplateEntry) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_template_proto_rawDescGZIP(), []int{4}
}

func (x *OrchestratorTemplateEntry) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *OrchestratorTemplateEntry) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OrchestratorTemplateEntry) GetInstances() []string {
	if x != nil {
		return x.Instances
	}
	return nil
}

type ListOrchestratorTemplatesResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Templates     []*OrchestratorTemplateEntry `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrchestratorTemplatesResponse) Reset() {
	*x = ListOrchestratorTemplatesResponse{}
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrchestratorTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrchestratorTemplatesResponse) ProtoMessage() {}

func (x *ListOrchestratorTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_orchestrator_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrchestratorTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListOrchestratorTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_orchestrator_template_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrchestratorTemplatesResponse) GetTemplates() []*OrchestratorTemplateEntry {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_apiserver_v1_orchestrator_template_proto protoreflect.FileDescriptor

const file_apiserver_v1_orchestrator_template_proto_rawDesc = "" +
	"\n" +
	"(apiserver/v1/orchestrator_template.proto\x12\fapiserver.v1\"P\n" +
	"\x14OrchestratorTemplate\x12\x1e\n" +
	"\n" +
	"templateID\x18\x01 \x01(\tR\n" +
	"templateID\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x88\x01\n" +
	"$RegisterOrchestratorTemplatesRequest\x12\x1e\n" +
	"\n" +
	"instanceID\x18\x01 \x01(\tR\n" +
	"instanceID\x12@\n" +
	"\ttemplates\x18\x02 \x03(\v2\".apiserver.v1.OrchestratorTemplateR\ttemplates\"=\n" +
	"%RegisterOrchestratorTemplatesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\"\n" +
	" ListOrchestratorTemplatesRequest\"s\n" +
	"\x19OrchestratorTemplateEntry\x12\x1e\n" +
	"\n" +
	"templateID\x18\x01 \x01(\tR\n" +
	"templateID\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tinstances\x18\x03 \x03(\tR\tinstances\"j\n" +
	"!ListOrchestratorTemplatesResponse\x12E\n" +
	"\ttemplates\x18\x01 \x03(\v2'.apiserver.v1.OrchestratorTemplateEntryR\ttemplatesB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_orchestrator_template_proto_rawDescOnce sync.Once
	file_apiserver_v1_orchestrator_template_proto_rawDescData []byte
)

func file_apiserver_v1_orchestrator_template_proto_rawDescGZIP() []byte {
	file_apiserver_v1_orchestrator_template_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_orchestrator_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_orchestrator_template_proto_rawDesc), len(file_apiserver_v1_orchestrator_template_proto_rawDesc)))
	})
	return file_apiserver_v1_orchestrator_template_proto_rawDescData
}

var file_apiserver_v1_orchestrator_template_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apiserver_v1_orchestrator_template_proto_goTypes = []any{
	(*OrchestratorTemplate)(nil),                  // 0: apiserver.v1.OrchestratorTemplate
	(*RegisterOrchestratorTemplatesRequest)(nil),  // 1: apiserver.v1.RegisterOrchestratorTemplatesRequest
	(*RegisterOrchestratorTemplatesResponse)(nil), // 2: apiserver.v1.RegisterOrchestratorTemplatesResponse
	(*ListOrchestratorTemplatesRequest)(nil),      // 3: apiserver.v1.ListOrchestratorTemplatesRequest
	(*OrchestratorTemplateEntry)(nil),             // 4: apiserver.v1.OrchestratorTemplateEntry
	(*ListOrchestratorTemplatesResponse)(nil),     // 5: apiserver.v1.ListOrchestratorTemplatesResponse
}
var file_apiserver_v1_orchestrator_template_proto_depIdxs = []int32{
	0, // 0: apiserver.v1.RegisterOrchestratorTemplatesRequest.templates:type_name -> apiserver.v1.OrchestratorTemplate
	4, // 1: apiserver.v1.ListOrchestratorTemplatesResponse.templates:type_name -> apiserver.v1.OrchestratorTemplateEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apiserver_v1_orchestrator_template_proto_init() }
func file_apiserver_v1_orchestrator_template_proto_init() {
	if File_apiserver_v1_orchestrator_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_orchestrator_template_proto_rawDesc), len(file_apiserver_v1_orchestrator_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_orchestrator_template_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_orchestrator_template_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_orchestrator_template_proto_msgTypes,
	}.Build()
	File_apiserver_v1_orchestrator_template_proto = out.File
	file_apiserver_v1_orchestrator_template_proto_goTypes = nil
	file_apiserver_v1_orchestrator_template_proto_depIdxs = nil
}
