// RBAC API 定义：用户、角色、权限的请求和响应消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apiserver/v1/rbac.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User 表示 RBAC 用户
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示用户唯一标识
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// username 表示用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// team_id 表示团队 ID
	TeamId string `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// status 表示用户状态（active/disabled）
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// created_at 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at 表示更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Role 表示 RBAC 角色
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_id 表示角色唯一标识
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// display_name 表示角色显示名称
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description 表示角色描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// status 表示角色状态（active/disabled）
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// created_at 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at 表示更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Role) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Permission 表示 RBAC 权限
type Permission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission_id 表示权限唯一标识
	PermissionId string `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	// resource 表示资源
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// action 表示操作
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// description 表示权限描述
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// status 表示权限状态（active/disabled）
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// created_at 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at 表示更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *Permission) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Permission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Permission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UserAccess 表示用户访问权限视图
type UserAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示用户 ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// role_ids 表示用户关联的角色 ID 列表
	RoleIds []string `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	// permissions 表示用户拥有的权限列表
	Permissions   []*Permission `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccess) Reset() {
	*x = UserAccess{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccess) ProtoMessage() {}

func (x *UserAccess) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccess.ProtoReflect.Descriptor instead.
func (*UserAccess) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *UserAccess) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAccess) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *UserAccess) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// RoleAccess 表示角色访问权限视图
type RoleAccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_id 表示角色 ID
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// permissions 表示角色拥有的权限列表
	Permissions   []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAccess) Reset() {
	*x = RoleAccess{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAccess) ProtoMessage() {}

func (x *RoleAccess) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAccess.ProtoReflect.Descriptor instead.
func (*RoleAccess) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *RoleAccess) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleAccess) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// LoginProfile 表示登录配置
type LoginProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user 表示用户信息
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// role_ids 表示用户角色 ID 列表
	RoleIds []string `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	// permissions 表示用户权限列表
	Permissions []*Permission `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// effective_actions 表示有效操作列表
	EffectiveActions []string `protobuf:"bytes,4,rep,name=effective_actions,json=effectiveActions,proto3" json:"effective_actions,omitempty"`
	// effective_team_ids 表示有效团队 ID 列表
	EffectiveTeamIds []string `protobuf:"bytes,5,rep,name=effective_team_ids,json=effectiveTeamIds,proto3" json:"effective_team_ids,omitempty"`
	// password_validated 表示密码是否已验证
	PasswordValidated bool `protobuf:"varint,6,opt,name=password_validated,json=passwordValidated,proto3" json:"password_validated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginProfile) Reset() {
	*x = LoginProfile{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginProfile) ProtoMessage() {}

func (x *LoginProfile) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginProfile.ProtoReflect.Descriptor instead.
func (*LoginProfile) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *LoginProfile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginProfile) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *LoginProfile) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *LoginProfile) GetEffectiveActions() []string {
	if x != nil {
		return x.EffectiveActions
	}
	return nil
}

func (x *LoginProfile) GetEffectiveTeamIds() []string {
	if x != nil {
		return x.EffectiveTeamIds
	}
	return nil
}

func (x *LoginProfile) GetPasswordValidated() bool {
	if x != nil {
		return x.PasswordValidated
	}
	return false
}

// ListUsersRequest 表示获取用户列表请求
type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUsersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListUsersResponse 表示获取用户列表响应
type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total 表示总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// items 表示用户列表
	Items         []*User `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetUserRequest 表示获取用户请求
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示要获取的用户 ID
	// @gotags: uri:"id"
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserResponse 表示获取用户响应
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user 表示用户信息
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UpsertUserRequest 表示创建或更新用户请求
type UpsertUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示用户 ID（更新时从 URI 获取）
	// @gotags: uri:"id"
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" uri:"id"`
	// username 表示用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// password 表示密码（可选，用于设置或更新密码）
	Password *string `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// team_id 表示团队 ID
	TeamId string `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// status 表示用户状态
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserRequest) Reset() {
	*x = UpsertUserRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserRequest) ProtoMessage() {}

func (x *UpsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpsertUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UpsertUserRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpsertUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpsertUserResponse 表示创建或更新用户响应
type UpsertUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user 表示用户信息
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserResponse) Reset() {
	*x = UpsertUserResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserResponse) ProtoMessage() {}

func (x *UpsertUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserResponse.ProtoReflect.Descriptor instead.
func (*UpsertUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// DeleteUserRequest 表示删除用户请求
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示要删除的用户 ID
	// @gotags: uri:"id"
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteUserResponse 表示删除用户响应
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{13}
}

// AssignUserRolesRequest 表示分配用户角色请求
type AssignUserRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示用户 ID
	// @gotags: uri:"id"
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" uri:"id"`
	// role_ids 表示要分配的角色 ID 列表
	RoleIds       []string `protobuf:"bytes,2,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserRolesRequest) Reset() {
	*x = AssignUserRolesRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserRolesRequest) ProtoMessage() {}

func (x *AssignUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserRolesRequest.ProtoReflect.Descriptor instead.
func (*AssignUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{14}
}

func (x *AssignUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignUserRolesRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// AssignUserRolesResponse 表示分配用户角色响应
type AssignUserRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_access 表示用户访问权限视图
	UserAccess    *UserAccess `protobuf:"bytes,1,opt,name=user_access,json=userAccess,proto3" json:"user_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignUserRolesResponse) Reset() {
	*x = AssignUserRolesResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignUserRolesResponse) ProtoMessage() {}

func (x *AssignUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignUserRolesResponse.ProtoReflect.Descriptor instead.
func (*AssignUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{15}
}

func (x *AssignUserRolesResponse) GetUserAccess() *UserAccess {
	if x != nil {
		return x.UserAccess
	}
	return nil
}

// GetUserAccessRequest 表示获取用户访问权限请求
type GetUserAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示用户 ID
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAccessRequest) Reset() {
	*x = GetUserAccessRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAccessRequest) ProtoMessage() {}

func (x *GetUserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAccessRequest.ProtoReflect.Descriptor instead.
func (*GetUserAccessRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserAccessResponse 表示获取用户访问权限响应
type GetUserAccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_access 表示用户访问权限视图
	UserAccess    *UserAccess `protobuf:"bytes,1,opt,name=user_access,json=userAccess,proto3" json:"user_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAccessResponse) Reset() {
	*x = GetUserAccessResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAccessResponse) ProtoMessage() {}

func (x *GetUserAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAccessResponse.ProtoReflect.Descriptor instead.
func (*GetUserAccessResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserAccessResponse) GetUserAccess() *UserAccess {
	if x != nil {
		return x.UserAccess
	}
	return nil
}

// ListRolesRequest 表示获取角色列表请求
type ListRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{18}
}

func (x *ListRolesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRolesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListRolesResponse 表示获取角色列表响应
type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total 表示总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// items 表示角色列表
	Items         []*Role `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{19}
}

func (x *ListRolesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRolesResponse) GetItems() []*Role {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetRoleRequest 表示获取角色请求
type GetRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_id 表示要获取的角色 ID
	// @gotags: uri:"id"
	RoleId        string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{20}
}

func (x *GetRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

// GetRoleResponse 表示获取角色响应
type GetRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role 表示角色信息
	Role          *Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{21}
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

// UpsertRoleRequest 表示创建或更新角色请求
type UpsertRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_id 表示角色 ID（更新时从 URI 获取）
	// @gotags: uri:"id"
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty" uri:"id"`
	// display_name 表示角色显示名称
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description 表示角色描述
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// status 表示角色状态
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRoleRequest) Reset() {
	*x = UpsertRoleRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRoleRequest) ProtoMessage() {}

func (x *UpsertRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRoleRequest.ProtoReflect.Descriptor instead.
func (*UpsertRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{22}
}

func (x *UpsertRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UpsertRoleRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpsertRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpsertRoleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpsertRoleResponse 表示创建或更新角色响应
type UpsertRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role 表示角色信息
	Role          *Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRoleResponse) Reset() {
	*x = UpsertRoleResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRoleResponse) ProtoMessage() {}

func (x *UpsertRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRoleResponse.ProtoReflect.Descriptor instead.
func (*UpsertRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{23}
}

func (x *UpsertRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

// DeleteRoleRequest 表示删除角色请求
type DeleteRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_id 表示要删除的角色 ID
	// @gotags: uri:"id"
	RoleId        string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

// DeleteRoleResponse 表示删除角色响应
type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{25}
}

// AssignRolePermissionsRequest 表示分配角色权限请求
type AssignRolePermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_id 表示角色 ID
	// @gotags: uri:"id"
	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty" uri:"id"`
	// permission_ids 表示要分配的权限 ID 列表
	PermissionIds []string `protobuf:"bytes,2,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolePermissionsRequest) Reset() {
	*x = AssignRolePermissionsRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolePermissionsRequest) ProtoMessage() {}

func (x *AssignRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*AssignRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{26}
}

func (x *AssignRolePermissionsRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRolePermissionsRequest) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// AssignRolePermissionsResponse 表示分配角色权限响应
type AssignRolePermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_access 表示角色访问权限视图
	RoleAccess    *RoleAccess `protobuf:"bytes,1,opt,name=role_access,json=roleAccess,proto3" json:"role_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolePermissionsResponse) Reset() {
	*x = AssignRolePermissionsResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolePermissionsResponse) ProtoMessage() {}

func (x *AssignRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*AssignRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{27}
}

func (x *AssignRolePermissionsResponse) GetRoleAccess() *RoleAccess {
	if x != nil {
		return x.RoleAccess
	}
	return nil
}

// ListPermissionsRequest 表示获取权限列表请求
type ListPermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{28}
}

func (x *ListPermissionsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListPermissionsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListPermissionsResponse 表示获取权限列表响应
type ListPermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total 表示总数
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// items 表示权限列表
	Items         []*Permission `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{29}
}

func (x *ListPermissionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPermissionsResponse) GetItems() []*Permission {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetPermissionRequest 表示获取权限请求
type GetPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission_id 表示要获取的权限 ID
	// @gotags: uri:"id"
	PermissionId  string `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{30}
}

func (x *GetPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

// GetPermissionResponse 表示获取权限响应
type GetPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission 表示权限信息
	Permission    *Permission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{31}
}

func (x *GetPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

// UpsertPermissionRequest 表示创建或更新权限请求
type UpsertPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission_id 表示权限 ID（更新时从 URI 获取）
	// @gotags: uri:"id"
	PermissionId string `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty" uri:"id"`
	// resource 表示资源
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// action 表示操作
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// description 表示权限描述
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// status 表示权限状态
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPermissionRequest) Reset() {
	*x = UpsertPermissionRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPermissionRequest) ProtoMessage() {}

func (x *UpsertPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPermissionRequest.ProtoReflect.Descriptor instead.
func (*UpsertPermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{32}
}

func (x *UpsertPermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *UpsertPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UpsertPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpsertPermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpsertPermissionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpsertPermissionResponse 表示创建或更新权限响应
type UpsertPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission 表示权限信息
	Permission    *Permission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPermissionResponse) Reset() {
	*x = UpsertPermissionResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPermissionResponse) ProtoMessage() {}

func (x *UpsertPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPermissionResponse.ProtoReflect.Descriptor instead.
func (*UpsertPermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{33}
}

func (x *UpsertPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

// DeletePermissionRequest 表示删除权限请求
type DeletePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission_id 表示要删除的权限 ID
	// @gotags: uri:"id"
	PermissionId  string `protobuf:"bytes,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty" uri:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{34}
}

func (x *DeletePermissionRequest) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

// DeletePermissionResponse 表示删除权限响应
type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{35}
}

// ResolveLoginProfileRequest 表示解析登录配置请求
type ResolveLoginProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id 表示用户 ID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// password 表示密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// skip_password_check 表示是否跳过密码检查
	SkipPasswordCheck bool `protobuf:"varint,3,opt,name=skip_password_check,json=skipPasswordCheck,proto3" json:"skip_password_check,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveLoginProfileRequest) Reset() {
	*x = ResolveLoginProfileRequest{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLoginProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLoginProfileRequest) ProtoMessage() {}

func (x *ResolveLoginProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLoginProfileRequest.ProtoReflect.Descriptor instead.
func (*ResolveLoginProfileRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{36}
}

func (x *ResolveLoginProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolveLoginProfileRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResolveLoginProfileRequest) GetSkipPasswordCheck() bool {
	if x != nil {
		return x.SkipPasswordCheck
	}
	return false
}

// ResolveLoginProfileResponse 表示解析登录配置响应
type ResolveLoginProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// login_profile 表示登录配置
	LoginProfile  *LoginProfile `protobuf:"bytes,1,opt,name=login_profile,json=loginProfile,proto3" json:"login_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLoginProfileResponse) Reset() {
	*x = ResolveLoginProfileResponse{}
	mi := &file_apiserver_v1_rbac_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLoginProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLoginProfileResponse) ProtoMessage() {}

func (x *ResolveLoginProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_rbac_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLoginProfileResponse.ProtoReflect.Descriptor instead.
func (*ResolveLoginProfileResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_rbac_proto_rawDescGZIP(), []int{37}
}

func (x *ResolveLoginProfileResponse) GetLoginProfile() *LoginProfile {
	if x != nil {
		return x.LoginProfile
	}
	return nil
}

var File_apiserver_v1_rbac_proto protoreflect.FileDescriptor

const file_apiserver_v1_rbac_proto_rawDesc = "" +
	"\n" +
	"\x17apiserver/v1/rbac.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf2\x01\n" +
	"\x04Role\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x95\x02\n" +
	"\n" +
	"Permission\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"|\n" +
	"\n" +
	"UserAccess\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\x12:\n" +
	"\vpermissions\x18\x03 \x03(\v2\x18.apiserver.v1.PermissionR\vpermissions\"a\n" +
	"\n" +
	"RoleAccess\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12:\n" +
	"\vpermissions\x18\x02 \x03(\v2\x18.apiserver.v1.PermissionR\vpermissions\"\x97\x02\n" +
	"\fLoginProfile\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.apiserver.v1.UserR\x04user\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\x12:\n" +
	"\vpermissions\x18\x03 \x03(\v2\x18.apiserver.v1.PermissionR\vpermissions\x12+\n" +
	"\x11effective_actions\x18\x04 \x03(\tR\x10effectiveActions\x12,\n" +
	"\x12effective_team_ids\x18\x05 \x03(\tR\x10effectiveTeamIds\x12-\n" +
	"\x12password_validated\x18\x06 \x01(\bR\x11passwordValidated\"@\n" +
	"\x10ListUsersRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"S\n" +
	"\x11ListUsersResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.apiserver.v1.UserR\x05items\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x0fGetUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.apiserver.v1.UserR\x04user\"\xa7\x01\n" +
	"\x11UpsertUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tH\x00R\bpassword\x88\x01\x01\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\tR\x06teamId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06statusB\v\n" +
	"\t_password\"<\n" +
	"\x12UpsertUserResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.apiserver.v1.UserR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x14\n" +
	"\x12DeleteUserResponse\"L\n" +
	"\x16AssignUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\tR\aroleIds\"T\n" +
	"\x17AssignUserRolesResponse\x129\n" +
	"\vuser_access\x18\x01 \x01(\v2\x18.apiserver.v1.UserAccessR\n" +
	"userAccess\"/\n" +
	"\x14GetUserAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x15GetUserAccessResponse\x129\n" +
	"\vuser_access\x18\x01 \x01(\v2\x18.apiserver.v1.UserAccessR\n" +
	"userAccess\"@\n" +
	"\x10ListRolesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"S\n" +
	"\x11ListRolesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.apiserver.v1.RoleR\x05items\")\n" +
	"\x0eGetRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"9\n" +
	"\x0fGetRoleResponse\x12&\n" +
	"\x04role\x18\x01 \x01(\v2\x12.apiserver.v1.RoleR\x04role\"\x89\x01\n" +
	"\x11UpsertRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"<\n" +
	"\x12UpsertRoleResponse\x12&\n" +
	"\x04role\x18\x01 \x01(\v2\x12.apiserver.v1.RoleR\x04role\",\n" +
	"\x11DeleteRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"\x14\n" +
	"\x12DeleteRoleResponse\"^\n" +
	"\x1cAssignRolePermissionsRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\tR\rpermissionIds\"Z\n" +
	"\x1dAssignRolePermissionsResponse\x129\n" +
	"\vrole_access\x18\x01 \x01(\v2\x18.apiserver.v1.RoleAccessR\n" +
	"roleAccess\"F\n" +
	"\x16ListPermissionsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"_\n" +
	"\x17ListPermissionsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.apiserver.v1.PermissionR\x05items\";\n" +
	"\x14GetPermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\"Q\n" +
	"\x15GetPermissionResponse\x128\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x18.apiserver.v1.PermissionR\n" +
	"permission\"\xac\x01\n" +
	"\x17UpsertPermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"T\n" +
	"\x18UpsertPermissionResponse\x128\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x18.apiserver.v1.PermissionR\n" +
	"permission\">\n" +
	"\x17DeletePermissionRequest\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\tR\fpermissionId\"\x1a\n" +
	"\x18DeletePermissionResponse\"\x81\x01\n" +
	"\x1aResolveLoginProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12.\n" +
	"\x13skip_password_check\x18\x03 \x01(\bR\x11skipPasswordCheck\"^\n" +
	"\x1bResolveLoginProfileResponse\x12?\n" +
	"\rlogin_profile\x18\x01 \x01(\v2\x1a.apiserver.v1.LoginProfileR\floginProfileB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_rbac_proto_rawDescOnce sync.Once
	file_apiserver_v1_rbac_proto_rawDescData []byte
)

func file_apiserver_v1_rbac_proto_rawDescGZIP() []byte {
	file_apiserver_v1_rbac_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_rbac_proto_rawDesc), len(file_apiserver_v1_rbac_proto_rawDesc)))
	})
	return file_apiserver_v1_rbac_proto_rawDescData
}

var file_apiserver_v1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_apiserver_v1_rbac_proto_goTypes = []any{
	(*User)(nil),                          // 0: apiserver.v1.User
	(*Role)(nil),                          // 1: apiserver.v1.Role
	(*Permission)(nil),                    // 2: apiserver.v1.Permission
	(*UserAccess)(nil),                    // 3: apiserver.v1.UserAccess
	(*RoleAccess)(nil),                    // 4: apiserver.v1.RoleAccess
	(*LoginProfile)(nil),                  // 5: apiserver.v1.LoginProfile
	(*ListUsersRequest)(nil),              // 6: apiserver.v1.ListUsersRequest
	(*ListUsersResponse)(nil),             // 7: apiserver.v1.ListUsersResponse
	(*GetUserRequest)(nil),                // 8: apiserver.v1.GetUserRequest
	(*GetUserResponse)(nil),               // 9: apiserver.v1.GetUserResponse
	(*UpsertUserRequest)(nil),             // 10: apiserver.v1.UpsertUserRequest
	(*UpsertUserResponse)(nil),            // 11: apiserver.v1.UpsertUserResponse
	(*DeleteUserRequest)(nil),             // 12: apiserver.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 13: apiserver.v1.DeleteUserResponse
	(*AssignUserRolesRequest)(nil),        // 14: apiserver.v1.AssignUserRolesRequest
	(*AssignUserRolesResponse)(nil),       // 15: apiserver.v1.AssignUserRolesResponse
	(*GetUserAccessRequest)(nil),          // 16: apiserver.v1.GetUserAccessRequest
	(*GetUserAccessResponse)(nil),         // 17: apiserver.v1.GetUserAccessResponse
	(*ListRolesRequest)(nil),              // 18: apiserver.v1.ListRolesRequest
	(*ListRolesResponse)(nil),             // 19: apiserver.v1.ListRolesResponse
	(*GetRoleRequest)(nil),                // 20: apiserver.v1.GetRoleRequest
	(*GetRoleResponse)(nil),               // 21: apiserver.v1.GetRoleResponse
	(*UpsertRoleRequest)(nil),             // 22: apiserver.v1.UpsertRoleRequest
	(*UpsertRoleResponse)(nil),            // 23: apiserver.v1.UpsertRoleResponse
	(*DeleteRoleRequest)(nil),             // 24: apiserver.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),            // 25: apiserver.v1.DeleteRoleResponse
	(*AssignRolePermissionsRequest)(nil),  // 26: apiserver.v1.AssignRolePermissionsRequest
	(*AssignRolePermissionsResponse)(nil), // 27: apiserver.v1.AssignRolePermissionsResponse
	(*ListPermissionsRequest)(nil),        // 28: apiserver.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),       // 29: apiserver.v1.ListPermissionsResponse
	(*GetPermissionRequest)(nil),          // 30: apiserver.v1.GetPermissionRequest
	(*GetPermissionResponse)(nil),         // 31: apiserver.v1.GetPermissionResponse
	(*UpsertPermissionRequest)(nil),       // 32: apiserver.v1.UpsertPermissionRequest
	(*UpsertPermissionResponse)(nil),      // 33: apiserver.v1.UpsertPermissionResponse
	(*DeletePermissionRequest)(nil),       // 34: apiserver.v1.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),      // 35: apiserver.v1.DeletePermissionResponse
	(*ResolveLoginProfileRequest)(nil),    // 36: apiserver.v1.ResolveLoginProfileRequest
	(*ResolveLoginProfileResponse)(nil),   // 37: apiserver.v1.ResolveLoginProfileResponse
	(*timestamppb.Timestamp)(nil),         // 38: google.protobuf.Timestamp
}
var file_apiserver_v1_rbac_proto_depIdxs = []int32{
	38, // 0: apiserver.v1.User.created_at:type_name -> google.protobuf.Timestamp
	38, // 1: apiserver.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	38, // 2: apiserver.v1.Role.created_at:type_name -> google.protobuf.Timestamp
	38, // 3: apiserver.v1.Role.updated_at:type_name -> google.protobuf.Timestamp
	38, // 4: apiserver.v1.Permission.created_at:type_name -> google.protobuf.Timestamp
	38, // 5: apiserver.v1.Permission.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 6: apiserver.v1.UserAccess.permissions:type_name -> apiserver.v1.Permission
	2,  // 7: apiserver.v1.RoleAccess.permissions:type_name -> apiserver.v1.Permission
	0,  // 8: apiserver.v1.LoginProfile.user:type_name -> apiserver.v1.User
	2,  // 9: apiserver.v1.LoginProfile.permissions:type_name -> apiserver.v1.Permission
	0,  // 10: apiserver.v1.ListUsersResponse.items:type_name -> apiserver.v1.User
	0,  // 11: apiserver.v1.GetUserResponse.user:type_name -> apiserver.v1.User
	0,  // 12: apiserver.v1.UpsertUserResponse.user:type_name -> apiserver.v1.User
	3,  // 13: apiserver.v1.AssignUserRolesResponse.user_access:type_name -> apiserver.v1.UserAccess
	3,  // 14: apiserver.v1.GetUserAccessResponse.user_access:type_name -> apiserver.v1.UserAccess
	1,  // 15: apiserver.v1.ListRolesResponse.items:type_name -> apiserver.v1.Role
	1,  // 16: apiserver.v1.GetRoleResponse.role:type_name -> apiserver.v1.Role
	1,  // 17: apiserver.v1.UpsertRoleResponse.role:type_name -> apiserver.v1.Role
	4,  // 18: apiserver.v1.AssignRolePermissionsResponse.role_access:type_name -> apiserver.v1.RoleAccess
	2,  // 19: apiserver.v1.ListPermissionsResponse.items:type_name -> apiserver.v1.Permission
	2,  // 20: apiserver.v1.GetPermissionResponse.permission:type_name -> apiserver.v1.Permission
	2,  // 21: apiserver.v1.UpsertPermissionResponse.permission:type_name -> apiserver.v1.Permission
	5,  // 22: apiserver.v1.ResolveLoginProfileResponse.login_profile:type_name -> apiserver.v1.LoginProfile
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_apiserver_v1_rbac_proto_init() }
func file_apiserver_v1_rbac_proto_init() {
	if File_apiserver_v1_rbac_proto != nil {
		return
	}
	file_apiserver_v1_rbac_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_rbac_proto_rawDesc), len(file_apiserver_v1_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_rbac_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_rbac_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_rbac_proto_msgTypes,
	}.Build()
	File_apiserver_v1_rbac_proto = out.File
	file_apiserver_v1_rbac_proto_goTypes = nil
	file_apiserver_v1_rbac_proto_depIdxs = nil
}
