// Silence API messages for P1-1 suppression/maintenance window.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apiserver/v1/silence.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SilenceMatcher defines one exact-match condition in P1-1.
type SilenceMatcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key supports: fingerprint|service|workloadKind|workloadName|severity.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// op supports only "=" in P1-1.
	Op            string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SilenceMatcher) Reset() {
	*x = SilenceMatcher{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SilenceMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SilenceMatcher) ProtoMessage() {}

func (x *SilenceMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SilenceMatcher.ProtoReflect.Descriptor instead.
func (*SilenceMatcher) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{0}
}

func (x *SilenceMatcher) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SilenceMatcher) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *SilenceMatcher) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Silence represents one suppression rule in a time window.
type Silence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SilenceID     string                 `protobuf:"bytes,1,opt,name=silenceID,proto3" json:"silenceID,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=startsAt,proto3" json:"startsAt,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=endsAt,proto3" json:"endsAt,omitempty"`
	Reason        *string                `protobuf:"bytes,6,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,7,opt,name=createdBy,proto3,oneof" json:"createdBy,omitempty"`
	Matchers      []*SilenceMatcher      `protobuf:"bytes,8,rep,name=matchers,proto3" json:"matchers,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Silence) Reset() {
	*x = Silence{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Silence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Silence) ProtoMessage() {}

func (x *Silence) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Silence.ProtoReflect.Descriptor instead.
func (*Silence) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{1}
}

func (x *Silence) GetSilenceID() string {
	if x != nil {
		return x.SilenceID
	}
	return ""
}

func (x *Silence) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Silence) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Silence) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Silence) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Silence) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Silence) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *Silence) GetMatchers() []*SilenceMatcher {
	if x != nil {
		return x.Matchers
	}
	return nil
}

func (x *Silence) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Silence) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateSilenceRequest creates one silence.
type CreateSilenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Enabled       *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=startsAt,proto3" json:"startsAt,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=endsAt,proto3" json:"endsAt,omitempty"`
	Reason        *string                `protobuf:"bytes,5,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,6,opt,name=createdBy,proto3,oneof" json:"createdBy,omitempty"`
	Matchers      []*SilenceMatcher      `protobuf:"bytes,7,rep,name=matchers,proto3" json:"matchers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSilenceRequest) Reset() {
	*x = CreateSilenceRequest{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSilenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSilenceRequest) ProtoMessage() {}

func (x *CreateSilenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSilenceRequest.ProtoReflect.Descriptor instead.
func (*CreateSilenceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSilenceRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *CreateSilenceRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *CreateSilenceRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *CreateSilenceRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *CreateSilenceRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *CreateSilenceRequest) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *CreateSilenceRequest) GetMatchers() []*SilenceMatcher {
	if x != nil {
		return x.Matchers
	}
	return nil
}

// CreateSilenceResponse returns created silence details.
type CreateSilenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Silence       *Silence               `protobuf:"bytes,1,opt,name=silence,proto3" json:"silence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSilenceResponse) Reset() {
	*x = CreateSilenceResponse{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSilenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSilenceResponse) ProtoMessage() {}

func (x *CreateSilenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSilenceResponse.ProtoReflect.Descriptor instead.
func (*CreateSilenceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSilenceResponse) GetSilence() *Silence {
	if x != nil {
		return x.Silence
	}
	return nil
}

// GetSilenceRequest fetches one silence.
type GetSilenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"silenceID"
	SilenceID     string `protobuf:"bytes,1,opt,name=silenceID,proto3" json:"silenceID,omitempty" uri:"silenceID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSilenceRequest) Reset() {
	*x = GetSilenceRequest{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSilenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSilenceRequest) ProtoMessage() {}

func (x *GetSilenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSilenceRequest.ProtoReflect.Descriptor instead.
func (*GetSilenceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{4}
}

func (x *GetSilenceRequest) GetSilenceID() string {
	if x != nil {
		return x.SilenceID
	}
	return ""
}

// GetSilenceResponse returns one silence.
type GetSilenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Silence       *Silence               `protobuf:"bytes,1,opt,name=silence,proto3" json:"silence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSilenceResponse) Reset() {
	*x = GetSilenceResponse{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSilenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSilenceResponse) ProtoMessage() {}

func (x *GetSilenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSilenceResponse.ProtoReflect.Descriptor instead.
func (*GetSilenceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{5}
}

func (x *GetSilenceResponse) GetSilence() *Silence {
	if x != nil {
		return x.Silence
	}
	return nil
}

// ListSilencesRequest lists silences with optional filters.
type ListSilencesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// @gotags: form:"limit"
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	// @gotags: form:"namespace"
	Namespace *string `protobuf:"bytes,3,opt,name=namespace,proto3,oneof" json:"namespace,omitempty" form:"namespace"`
	// @gotags: form:"enabled"
	Enabled *bool `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty" form:"enabled"`
	// @gotags: form:"active"
	Active        *bool `protobuf:"varint,5,opt,name=active,proto3,oneof" json:"active,omitempty" form:"active"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSilencesRequest) Reset() {
	*x = ListSilencesRequest{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSilencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSilencesRequest) ProtoMessage() {}

func (x *ListSilencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSilencesRequest.ProtoReflect.Descriptor instead.
func (*ListSilencesRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{6}
}

func (x *ListSilencesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListSilencesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSilencesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ListSilencesRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ListSilencesRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

// ListSilencesResponse returns silence list.
type ListSilencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Silences      []*Silence             `protobuf:"bytes,2,rep,name=silences,proto3" json:"silences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSilencesResponse) Reset() {
	*x = ListSilencesResponse{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSilencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSilencesResponse) ProtoMessage() {}

func (x *ListSilencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSilencesResponse.ProtoReflect.Descriptor instead.
func (*ListSilencesResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{7}
}

func (x *ListSilencesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListSilencesResponse) GetSilences() []*Silence {
	if x != nil {
		return x.Silences
	}
	return nil
}

// PatchSilenceRequest updates minimal mutable fields.
type PatchSilenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"silenceID"
	SilenceID     string                 `protobuf:"bytes,1,opt,name=silenceID,proto3" json:"silenceID,omitempty" uri:"silenceID"`
	Enabled       *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endsAt,proto3,oneof" json:"endsAt,omitempty"`
	Reason        *string                `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchSilenceRequest) Reset() {
	*x = PatchSilenceRequest{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchSilenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchSilenceRequest) ProtoMessage() {}

func (x *PatchSilenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchSilenceRequest.ProtoReflect.Descriptor instead.
func (*PatchSilenceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{8}
}

func (x *PatchSilenceRequest) GetSilenceID() string {
	if x != nil {
		return x.SilenceID
	}
	return ""
}

func (x *PatchSilenceRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *PatchSilenceRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *PatchSilenceRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// PatchSilenceResponse indicates update success.
type PatchSilenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchSilenceResponse) Reset() {
	*x = PatchSilenceResponse{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchSilenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchSilenceResponse) ProtoMessage() {}

func (x *PatchSilenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchSilenceResponse.ProtoReflect.Descriptor instead.
func (*PatchSilenceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{9}
}

// DeleteSilenceRequest soft-disables one silence.
type DeleteSilenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"silenceID"
	SilenceID     string `protobuf:"bytes,1,opt,name=silenceID,proto3" json:"silenceID,omitempty" uri:"silenceID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSilenceRequest) Reset() {
	*x = DeleteSilenceRequest{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSilenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSilenceRequest) ProtoMessage() {}

func (x *DeleteSilenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSilenceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSilenceRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSilenceRequest) GetSilenceID() string {
	if x != nil {
		return x.SilenceID
	}
	return ""
}

// DeleteSilenceResponse indicates delete(successful disable) result.
type DeleteSilenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSilenceResponse) Reset() {
	*x = DeleteSilenceResponse{}
	mi := &file_apiserver_v1_silence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSilenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSilenceResponse) ProtoMessage() {}

func (x *DeleteSilenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_silence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSilenceResponse.ProtoReflect.Descriptor instead.
func (*DeleteSilenceResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_silence_proto_rawDescGZIP(), []int{11}
}

var File_apiserver_v1_silence_proto protoreflect.FileDescriptor

const file_apiserver_v1_silence_proto_rawDesc = "" +
	"\n" +
	"\x1aapiserver/v1/silence.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x0eSilenceMatcher\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xd2\x03\n" +
	"\aSilence\x12\x1c\n" +
	"\tsilenceID\x18\x01 \x01(\tR\tsilenceID\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x126\n" +
	"\bstartsAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x122\n" +
	"\x06endsAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x1b\n" +
	"\x06reason\x18\x06 \x01(\tH\x00R\x06reason\x88\x01\x01\x12!\n" +
	"\tcreatedBy\x18\a \x01(\tH\x01R\tcreatedBy\x88\x01\x01\x128\n" +
	"\bmatchers\x18\b \x03(\v2\x1c.apiserver.v1.SilenceMatcherR\bmatchers\x128\n" +
	"\tcreatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\t\n" +
	"\a_reasonB\f\n" +
	"\n" +
	"_createdBy\"\xf1\x02\n" +
	"\x14CreateSilenceRequest\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x01R\aenabled\x88\x01\x01\x126\n" +
	"\bstartsAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x122\n" +
	"\x06endsAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x1b\n" +
	"\x06reason\x18\x05 \x01(\tH\x02R\x06reason\x88\x01\x01\x12!\n" +
	"\tcreatedBy\x18\x06 \x01(\tH\x03R\tcreatedBy\x88\x01\x01\x128\n" +
	"\bmatchers\x18\a \x03(\v2\x1c.apiserver.v1.SilenceMatcherR\bmatchersB\f\n" +
	"\n" +
	"_namespaceB\n" +
	"\n" +
	"\b_enabledB\t\n" +
	"\a_reasonB\f\n" +
	"\n" +
	"_createdBy\"H\n" +
	"\x15CreateSilenceResponse\x12/\n" +
	"\asilence\x18\x01 \x01(\v2\x15.apiserver.v1.SilenceR\asilence\"1\n" +
	"\x11GetSilenceRequest\x12\x1c\n" +
	"\tsilenceID\x18\x01 \x01(\tR\tsilenceID\"E\n" +
	"\x12GetSilenceResponse\x12/\n" +
	"\asilence\x18\x01 \x01(\v2\x15.apiserver.v1.SilenceR\asilence\"\xc7\x01\n" +
	"\x13ListSilencesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12!\n" +
	"\tnamespace\x18\x03 \x01(\tH\x00R\tnamespace\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x04 \x01(\bH\x01R\aenabled\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x05 \x01(\bH\x02R\x06active\x88\x01\x01B\f\n" +
	"\n" +
	"_namespaceB\n" +
	"\n" +
	"\b_enabledB\t\n" +
	"\a_active\"i\n" +
	"\x14ListSilencesResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x121\n" +
	"\bsilences\x18\x02 \x03(\v2\x15.apiserver.v1.SilenceR\bsilences\"\xca\x01\n" +
	"\x13PatchSilenceRequest\x12\x1c\n" +
	"\tsilenceID\x18\x01 \x01(\tR\tsilenceID\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x00R\aenabled\x88\x01\x01\x127\n" +
	"\x06endsAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06endsAt\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x04 \x01(\tH\x02R\x06reason\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\t\n" +
	"\a_endsAtB\t\n" +
	"\a_reason\"\x16\n" +
	"\x14PatchSilenceResponse\"4\n" +
	"\x14DeleteSilenceRequest\x12\x1c\n" +
	"\tsilenceID\x18\x01 \x01(\tR\tsilenceID\"\x17\n" +
	"\x15DeleteSilenceResponseB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_silence_proto_rawDescOnce sync.Once
	file_apiserver_v1_silence_proto_rawDescData []byte
)

func file_apiserver_v1_silence_proto_rawDescGZIP() []byte {
	file_apiserver_v1_silence_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_silence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_silence_proto_rawDesc), len(file_apiserver_v1_silence_proto_rawDesc)))
	})
	return file_apiserver_v1_silence_proto_rawDescData
}

var file_apiserver_v1_silence_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_apiserver_v1_silence_proto_goTypes = []any{
	(*SilenceMatcher)(nil),        // 0: apiserver.v1.SilenceMatcher
	(*Silence)(nil),               // 1: apiserver.v1.Silence
	(*CreateSilenceRequest)(nil),  // 2: apiserver.v1.CreateSilenceRequest
	(*CreateSilenceResponse)(nil), // 3: apiserver.v1.CreateSilenceResponse
	(*GetSilenceRequest)(nil),     // 4: apiserver.v1.GetSilenceRequest
	(*GetSilenceResponse)(nil),    // 5: apiserver.v1.GetSilenceResponse
	(*ListSilencesRequest)(nil),   // 6: apiserver.v1.ListSilencesRequest
	(*ListSilencesResponse)(nil),  // 7: apiserver.v1.ListSilencesResponse
	(*PatchSilenceRequest)(nil),   // 8: apiserver.v1.PatchSilenceRequest
	(*PatchSilenceResponse)(nil),  // 9: apiserver.v1.PatchSilenceResponse
	(*DeleteSilenceRequest)(nil),  // 10: apiserver.v1.DeleteSilenceRequest
	(*DeleteSilenceResponse)(nil), // 11: apiserver.v1.DeleteSilenceResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_apiserver_v1_silence_proto_depIdxs = []int32{
	12, // 0: apiserver.v1.Silence.startsAt:type_name -> google.protobuf.Timestamp
	12, // 1: apiserver.v1.Silence.endsAt:type_name -> google.protobuf.Timestamp
	0,  // 2: apiserver.v1.Silence.matchers:type_name -> apiserver.v1.SilenceMatcher
	12, // 3: apiserver.v1.Silence.createdAt:type_name -> google.protobuf.Timestamp
	12, // 4: apiserver.v1.Silence.updatedAt:type_name -> google.protobuf.Timestamp
	12, // 5: apiserver.v1.CreateSilenceRequest.startsAt:type_name -> google.protobuf.Timestamp
	12, // 6: apiserver.v1.CreateSilenceRequest.endsAt:type_name -> google.protobuf.Timestamp
	0,  // 7: apiserver.v1.CreateSilenceRequest.matchers:type_name -> apiserver.v1.SilenceMatcher
	1,  // 8: apiserver.v1.CreateSilenceResponse.silence:type_name -> apiserver.v1.Silence
	1,  // 9: apiserver.v1.GetSilenceResponse.silence:type_name -> apiserver.v1.Silence
	1,  // 10: apiserver.v1.ListSilencesResponse.silences:type_name -> apiserver.v1.Silence
	12, // 11: apiserver.v1.PatchSilenceRequest.endsAt:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_apiserver_v1_silence_proto_init() }
func file_apiserver_v1_silence_proto_init() {
	if File_apiserver_v1_silence_proto != nil {
		return
	}
	file_apiserver_v1_silence_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_silence_proto_msgTypes[2].OneofWrappers = []any{}
	file_apiserver_v1_silence_proto_msgTypes[6].OneofWrappers = []any{}
	file_apiserver_v1_silence_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_silence_proto_rawDesc), len(file_apiserver_v1_silence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_silence_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_silence_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_silence_proto_msgTypes,
	}.Build()
	File_apiserver_v1_silence_proto = out.File
	file_apiserver_v1_silence_proto_goTypes = nil
	file_apiserver_v1_silence_proto_depIdxs = nil
}
