// Silence API messages for P1-1 suppression/maintenance window.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *SilenceMatcher) Default() {
}

func (x *Silence) Default() {
}

func (x *CreateSilenceRequest) Default() {
}

func (x *CreateSilenceResponse) Default() {
}

func (x *GetSilenceRequest) Default() {
}

func (x *GetSilenceResponse) Default() {
}

func (x *ListSilencesRequest) Default() {
}

func (x *ListSilencesResponse) Default() {
}

func (x *PatchSilenceRequest) Default() {
}

func (x *PatchSilenceResponse) Default() {
}

func (x *DeleteSilenceRequest) Default() {
}

func (x *DeleteSilenceResponse) Default() {
}
