// ToolsetProviderBinding API definition: toolset-to-provider binding management.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apiserver/v1/toolset_provider_binding.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolsetProviderBinding represents one binding between a toolset and an MCP server provider.
type ToolsetProviderBinding struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ToolsetName      string                 `protobuf:"bytes,2,opt,name=toolsetName,proto3" json:"toolsetName,omitempty"`
	McpServerID      string                 `protobuf:"bytes,3,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty"`
	AllowedToolsJSON *string                `protobuf:"bytes,4,opt,name=allowedToolsJSON,proto3,oneof" json:"allowedToolsJSON,omitempty"`
	Priority         int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled          bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolsetProviderBinding) Reset() {
	*x = ToolsetProviderBinding{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsetProviderBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsetProviderBinding) ProtoMessage() {}

func (x *ToolsetProviderBinding) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsetProviderBinding.ProtoReflect.Descriptor instead.
func (*ToolsetProviderBinding) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{0}
}

func (x *ToolsetProviderBinding) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToolsetProviderBinding) GetToolsetName() string {
	if x != nil {
		return x.ToolsetName
	}
	return ""
}

func (x *ToolsetProviderBinding) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

func (x *ToolsetProviderBinding) GetAllowedToolsJSON() string {
	if x != nil && x.AllowedToolsJSON != nil {
		return *x.AllowedToolsJSON
	}
	return ""
}

func (x *ToolsetProviderBinding) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ToolsetProviderBinding) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ToolsetProviderBinding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ToolsetProviderBinding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateToolsetProviderBindingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ToolsetName      string                 `protobuf:"bytes,1,opt,name=toolsetName,proto3" json:"toolsetName,omitempty"`
	McpServerID      string                 `protobuf:"bytes,2,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty"`
	AllowedToolsJSON *string                `protobuf:"bytes,3,opt,name=allowedToolsJSON,proto3,oneof" json:"allowedToolsJSON,omitempty"`
	Priority         *int32                 `protobuf:"varint,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Enabled          *bool                  `protobuf:"varint,5,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateToolsetProviderBindingRequest) Reset() {
	*x = CreateToolsetProviderBindingRequest{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToolsetProviderBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolsetProviderBindingRequest) ProtoMessage() {}

func (x *CreateToolsetProviderBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolsetProviderBindingRequest.ProtoReflect.Descriptor instead.
func (*CreateToolsetProviderBindingRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{1}
}

func (x *CreateToolsetProviderBindingRequest) GetToolsetName() string {
	if x != nil {
		return x.ToolsetName
	}
	return ""
}

func (x *CreateToolsetProviderBindingRequest) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

func (x *CreateToolsetProviderBindingRequest) GetAllowedToolsJSON() string {
	if x != nil && x.AllowedToolsJSON != nil {
		return *x.AllowedToolsJSON
	}
	return ""
}

func (x *CreateToolsetProviderBindingRequest) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *CreateToolsetProviderBindingRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type CreateToolsetProviderBindingResponse struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	ToolsetProviderBinding *ToolsetProviderBinding `protobuf:"bytes,1,opt,name=toolsetProviderBinding,proto3" json:"toolsetProviderBinding,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateToolsetProviderBindingResponse) Reset() {
	*x = CreateToolsetProviderBindingResponse{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToolsetProviderBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolsetProviderBindingResponse) ProtoMessage() {}

func (x *CreateToolsetProviderBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolsetProviderBindingResponse.ProtoReflect.Descriptor instead.
func (*CreateToolsetProviderBindingResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{2}
}

func (x *CreateToolsetProviderBindingResponse) GetToolsetProviderBinding() *ToolsetProviderBinding {
	if x != nil {
		return x.ToolsetProviderBinding
	}
	return nil
}

type GetToolsetProviderBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"toolsetName"
	ToolsetName string `protobuf:"bytes,1,opt,name=toolsetName,proto3" json:"toolsetName,omitempty" uri:"toolsetName"`
	// @gotags: uri:"mcpServerID"
	McpServerID   string `protobuf:"bytes,2,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty" uri:"mcpServerID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolsetProviderBindingRequest) Reset() {
	*x = GetToolsetProviderBindingRequest{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolsetProviderBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolsetProviderBindingRequest) ProtoMessage() {}

func (x *GetToolsetProviderBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolsetProviderBindingRequest.ProtoReflect.Descriptor instead.
func (*GetToolsetProviderBindingRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{3}
}

func (x *GetToolsetProviderBindingRequest) GetToolsetName() string {
	if x != nil {
		return x.ToolsetName
	}
	return ""
}

func (x *GetToolsetProviderBindingRequest) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

type GetToolsetProviderBindingResponse struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	ToolsetProviderBinding *ToolsetProviderBinding `protobuf:"bytes,1,opt,name=toolsetProviderBinding,proto3" json:"toolsetProviderBinding,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetToolsetProviderBindingResponse) Reset() {
	*x = GetToolsetProviderBindingResponse{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolsetProviderBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolsetProviderBindingResponse) ProtoMessage() {}

func (x *GetToolsetProviderBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolsetProviderBindingResponse.ProtoReflect.Descriptor instead.
func (*GetToolsetProviderBindingResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{4}
}

func (x *GetToolsetProviderBindingResponse) GetToolsetProviderBinding() *ToolsetProviderBinding {
	if x != nil {
		return x.ToolsetProviderBinding
	}
	return nil
}

type ListToolsetProviderBindingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// @gotags: form:"limit"
	Limit         int64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	ToolsetName   *string `protobuf:"bytes,3,opt,name=toolsetName,proto3,oneof" json:"toolsetName,omitempty"`
	McpServerID   *string `protobuf:"bytes,4,opt,name=mcpServerID,proto3,oneof" json:"mcpServerID,omitempty"`
	Enabled       *bool   `protobuf:"varint,5,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsetProviderBindingsRequest) Reset() {
	*x = ListToolsetProviderBindingsRequest{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsetProviderBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsetProviderBindingsRequest) ProtoMessage() {}

func (x *ListToolsetProviderBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsetProviderBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsetProviderBindingsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{5}
}

func (x *ListToolsetProviderBindingsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListToolsetProviderBindingsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListToolsetProviderBindingsRequest) GetToolsetName() string {
	if x != nil && x.ToolsetName != nil {
		return *x.ToolsetName
	}
	return ""
}

func (x *ListToolsetProviderBindingsRequest) GetMcpServerID() string {
	if x != nil && x.McpServerID != nil {
		return *x.McpServerID
	}
	return ""
}

func (x *ListToolsetProviderBindingsRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type ListToolsetProviderBindingsResponse struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	TotalCount              int64                     `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	ToolsetProviderBindings []*ToolsetProviderBinding `protobuf:"bytes,2,rep,name=toolsetProviderBindings,proto3" json:"toolsetProviderBindings,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListToolsetProviderBindingsResponse) Reset() {
	*x = ListToolsetProviderBindingsResponse{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsetProviderBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsetProviderBindingsResponse) ProtoMessage() {}

func (x *ListToolsetProviderBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsetProviderBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsetProviderBindingsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{6}
}

func (x *ListToolsetProviderBindingsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListToolsetProviderBindingsResponse) GetToolsetProviderBindings() []*ToolsetProviderBinding {
	if x != nil {
		return x.ToolsetProviderBindings
	}
	return nil
}

type UpdateToolsetProviderBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"toolsetName"
	ToolsetName string `protobuf:"bytes,1,opt,name=toolsetName,proto3" json:"toolsetName,omitempty" uri:"toolsetName"`
	// @gotags: uri:"mcpServerID"
	McpServerID      string  `protobuf:"bytes,2,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty" uri:"mcpServerID"`
	AllowedToolsJSON *string `protobuf:"bytes,3,opt,name=allowedToolsJSON,proto3,oneof" json:"allowedToolsJSON,omitempty"`
	Priority         *int32  `protobuf:"varint,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Enabled          *bool   `protobuf:"varint,5,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateToolsetProviderBindingRequest) Reset() {
	*x = UpdateToolsetProviderBindingRequest{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateToolsetProviderBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToolsetProviderBindingRequest) ProtoMessage() {}

func (x *UpdateToolsetProviderBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToolsetProviderBindingRequest.ProtoReflect.Descriptor instead.
func (*UpdateToolsetProviderBindingRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateToolsetProviderBindingRequest) GetToolsetName() string {
	if x != nil {
		return x.ToolsetName
	}
	return ""
}

func (x *UpdateToolsetProviderBindingRequest) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

func (x *UpdateToolsetProviderBindingRequest) GetAllowedToolsJSON() string {
	if x != nil && x.AllowedToolsJSON != nil {
		return *x.AllowedToolsJSON
	}
	return ""
}

func (x *UpdateToolsetProviderBindingRequest) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *UpdateToolsetProviderBindingRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type UpdateToolsetProviderBindingResponse struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	ToolsetProviderBinding *ToolsetProviderBinding `protobuf:"bytes,1,opt,name=toolsetProviderBinding,proto3" json:"toolsetProviderBinding,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateToolsetProviderBindingResponse) Reset() {
	*x = UpdateToolsetProviderBindingResponse{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateToolsetProviderBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToolsetProviderBindingResponse) ProtoMessage() {}

func (x *UpdateToolsetProviderBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToolsetProviderBindingResponse.ProtoReflect.Descriptor instead.
func (*UpdateToolsetProviderBindingResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateToolsetProviderBindingResponse) GetToolsetProviderBinding() *ToolsetProviderBinding {
	if x != nil {
		return x.ToolsetProviderBinding
	}
	return nil
}

type DeleteToolsetProviderBindingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"toolsetName"
	ToolsetName string `protobuf:"bytes,1,opt,name=toolsetName,proto3" json:"toolsetName,omitempty" uri:"toolsetName"`
	// @gotags: uri:"mcpServerID"
	McpServerID   string `protobuf:"bytes,2,opt,name=mcpServerID,proto3" json:"mcpServerID,omitempty" uri:"mcpServerID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteToolsetProviderBindingRequest) Reset() {
	*x = DeleteToolsetProviderBindingRequest{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteToolsetProviderBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToolsetProviderBindingRequest) ProtoMessage() {}

func (x *DeleteToolsetProviderBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToolsetProviderBindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteToolsetProviderBindingRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteToolsetProviderBindingRequest) GetToolsetName() string {
	if x != nil {
		return x.ToolsetName
	}
	return ""
}

func (x *DeleteToolsetProviderBindingRequest) GetMcpServerID() string {
	if x != nil {
		return x.McpServerID
	}
	return ""
}

type DeleteToolsetProviderBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteToolsetProviderBindingResponse) Reset() {
	*x = DeleteToolsetProviderBindingResponse{}
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteToolsetProviderBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToolsetProviderBindingResponse) ProtoMessage() {}

func (x *DeleteToolsetProviderBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_toolset_provider_binding_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToolsetProviderBindingResponse.ProtoReflect.Descriptor instead.
func (*DeleteToolsetProviderBindingResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP(), []int{10}
}

var File_apiserver_v1_toolset_provider_binding_proto protoreflect.FileDescriptor

const file_apiserver_v1_toolset_provider_binding_proto_rawDesc = "" +
	"\n" +
	"+apiserver/v1/toolset_provider_binding.proto\x12\fapiserver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n" +
	"\x16ToolsetProviderBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vtoolsetName\x18\x02 \x01(\tR\vtoolsetName\x12 \n" +
	"\vmcpServerID\x18\x03 \x01(\tR\vmcpServerID\x12/\n" +
	"\x10allowedToolsJSON\x18\x04 \x01(\tH\x00R\x10allowedToolsJSON\x88\x01\x01\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x128\n" +
	"\tcreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x13\n" +
	"\x11_allowedToolsJSON\"\x88\x02\n" +
	"#CreateToolsetProviderBindingRequest\x12 \n" +
	"\vtoolsetName\x18\x01 \x01(\tR\vtoolsetName\x12 \n" +
	"\vmcpServerID\x18\x02 \x01(\tR\vmcpServerID\x12/\n" +
	"\x10allowedToolsJSON\x18\x03 \x01(\tH\x00R\x10allowedToolsJSON\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\x05H\x01R\bpriority\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x05 \x01(\bH\x02R\aenabled\x88\x01\x01B\x13\n" +
	"\x11_allowedToolsJSONB\v\n" +
	"\t_priorityB\n" +
	"\n" +
	"\b_enabled\"\x84\x01\n" +
	"$CreateToolsetProviderBindingResponse\x12\\\n" +
	"\x16toolsetProviderBinding\x18\x01 \x01(\v2$.apiserver.v1.ToolsetProviderBindingR\x16toolsetProviderBinding\"f\n" +
	" GetToolsetProviderBindingRequest\x12 \n" +
	"\vtoolsetName\x18\x01 \x01(\tR\vtoolsetName\x12 \n" +
	"\vmcpServerID\x18\x02 \x01(\tR\vmcpServerID\"\x81\x01\n" +
	"!GetToolsetProviderBindingResponse\x12\\\n" +
	"\x16toolsetProviderBinding\x18\x01 \x01(\v2$.apiserver.v1.ToolsetProviderBindingR\x16toolsetProviderBinding\"\xeb\x01\n" +
	"\"ListToolsetProviderBindingsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12%\n" +
	"\vtoolsetName\x18\x03 \x01(\tH\x00R\vtoolsetName\x88\x01\x01\x12%\n" +
	"\vmcpServerID\x18\x04 \x01(\tH\x01R\vmcpServerID\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x05 \x01(\bH\x02R\aenabled\x88\x01\x01B\x0e\n" +
	"\f_toolsetNameB\x0e\n" +
	"\f_mcpServerIDB\n" +
	"\n" +
	"\b_enabled\"\xa5\x01\n" +
	"#ListToolsetProviderBindingsResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12^\n" +
	"\x17toolsetProviderBindings\x18\x02 \x03(\v2$.apiserver.v1.ToolsetProviderBindingR\x17toolsetProviderBindings\"\x88\x02\n" +
	"#UpdateToolsetProviderBindingRequest\x12 \n" +
	"\vtoolsetName\x18\x01 \x01(\tR\vtoolsetName\x12 \n" +
	"\vmcpServerID\x18\x02 \x01(\tR\vmcpServerID\x12/\n" +
	"\x10allowedToolsJSON\x18\x03 \x01(\tH\x00R\x10allowedToolsJSON\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\x05H\x01R\bpriority\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x05 \x01(\bH\x02R\aenabled\x88\x01\x01B\x13\n" +
	"\x11_allowedToolsJSONB\v\n" +
	"\t_priorityB\n" +
	"\n" +
	"\b_enabled\"\x84\x01\n" +
	"$UpdateToolsetProviderBindingResponse\x12\\\n" +
	"\x16toolsetProviderBinding\x18\x01 \x01(\v2$.apiserver.v1.ToolsetProviderBindingR\x16toolsetProviderBinding\"i\n" +
	"#DeleteToolsetProviderBindingRequest\x12 \n" +
	"\vtoolsetName\x18\x01 \x01(\tR\vtoolsetName\x12 \n" +
	"\vmcpServerID\x18\x02 \x01(\tR\vmcpServerID\"&\n" +
	"$DeleteToolsetProviderBindingResponseB4Z2github.com/aiopsre/rca-api/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_toolset_provider_binding_proto_rawDescOnce sync.Once
	file_apiserver_v1_toolset_provider_binding_proto_rawDescData []byte
)

func file_apiserver_v1_toolset_provider_binding_proto_rawDescGZIP() []byte {
	file_apiserver_v1_toolset_provider_binding_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_toolset_provider_binding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_toolset_provider_binding_proto_rawDesc), len(file_apiserver_v1_toolset_provider_binding_proto_rawDesc)))
	})
	return file_apiserver_v1_toolset_provider_binding_proto_rawDescData
}

var file_apiserver_v1_toolset_provider_binding_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_toolset_provider_binding_proto_goTypes = []any{
	(*ToolsetProviderBinding)(nil),               // 0: apiserver.v1.ToolsetProviderBinding
	(*CreateToolsetProviderBindingRequest)(nil),  // 1: apiserver.v1.CreateToolsetProviderBindingRequest
	(*CreateToolsetProviderBindingResponse)(nil), // 2: apiserver.v1.CreateToolsetProviderBindingResponse
	(*GetToolsetProviderBindingRequest)(nil),     // 3: apiserver.v1.GetToolsetProviderBindingRequest
	(*GetToolsetProviderBindingResponse)(nil),    // 4: apiserver.v1.GetToolsetProviderBindingResponse
	(*ListToolsetProviderBindingsRequest)(nil),   // 5: apiserver.v1.ListToolsetProviderBindingsRequest
	(*ListToolsetProviderBindingsResponse)(nil),  // 6: apiserver.v1.ListToolsetProviderBindingsResponse
	(*UpdateToolsetProviderBindingRequest)(nil),  // 7: apiserver.v1.UpdateToolsetProviderBindingRequest
	(*UpdateToolsetProviderBindingResponse)(nil), // 8: apiserver.v1.UpdateToolsetProviderBindingResponse
	(*DeleteToolsetProviderBindingRequest)(nil),  // 9: apiserver.v1.DeleteToolsetProviderBindingRequest
	(*DeleteToolsetProviderBindingResponse)(nil), // 10: apiserver.v1.DeleteToolsetProviderBindingResponse
	(*timestamppb.Timestamp)(nil),                // 11: google.protobuf.Timestamp
}
var file_apiserver_v1_toolset_provider_binding_proto_depIdxs = []int32{
	11, // 0: apiserver.v1.ToolsetProviderBinding.createdAt:type_name -> google.protobuf.Timestamp
	11, // 1: apiserver.v1.ToolsetProviderBinding.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: apiserver.v1.CreateToolsetProviderBindingResponse.toolsetProviderBinding:type_name -> apiserver.v1.ToolsetProviderBinding
	0,  // 3: apiserver.v1.GetToolsetProviderBindingResponse.toolsetProviderBinding:type_name -> apiserver.v1.ToolsetProviderBinding
	0,  // 4: apiserver.v1.ListToolsetProviderBindingsResponse.toolsetProviderBindings:type_name -> apiserver.v1.ToolsetProviderBinding
	0,  // 5: apiserver.v1.UpdateToolsetProviderBindingResponse.toolsetProviderBinding:type_name -> apiserver.v1.ToolsetProviderBinding
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_apiserver_v1_toolset_provider_binding_proto_init() }
func file_apiserver_v1_toolset_provider_binding_proto_init() {
	if File_apiserver_v1_toolset_provider_binding_proto != nil {
		return
	}
	file_apiserver_v1_toolset_provider_binding_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_toolset_provider_binding_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_toolset_provider_binding_proto_msgTypes[5].OneofWrappers = []any{}
	file_apiserver_v1_toolset_provider_binding_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_toolset_provider_binding_proto_rawDesc), len(file_apiserver_v1_toolset_provider_binding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_toolset_provider_binding_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_toolset_provider_binding_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_toolset_provider_binding_proto_msgTypes,
	}.Build()
	File_apiserver_v1_toolset_provider_binding_proto = out.File
	file_apiserver_v1_toolset_provider_binding_proto_goTypes = nil
	file_apiserver_v1_toolset_provider_binding_proto_depIdxs = nil
}
