// ToolsetProviderBinding API definition: toolset-to-provider binding management.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *ToolsetProviderBinding) Default() {
}

func (x *CreateToolsetProviderBindingRequest) Default() {
}

func (x *CreateToolsetProviderBindingResponse) Default() {
}

func (x *GetToolsetProviderBindingRequest) Default() {
}

func (x *GetToolsetProviderBindingResponse) Default() {
}

func (x *ListToolsetProviderBindingsRequest) Default() {
}

func (x *ListToolsetProviderBindingsResponse) Default() {
}

func (x *UpdateToolsetProviderBindingRequest) Default() {
}

func (x *UpdateToolsetProviderBindingResponse) Default() {
}

func (x *DeleteToolsetProviderBindingRequest) Default() {
}

func (x *DeleteToolsetProviderBindingResponse) Default() {
}
